-- TSK-07-01 design.md §1·§2·§6.0 — 05 영역(마스터데이터) 원장 7테이블(MSSQL).
-- Flyway 버전: V10. 당초 팀장 배정 V7 이었으나 dev 에 V8·V9 가 먼저 머지되어 2026-09-24 팀장 정정으로 머지 뒤 최대 버전+1 로 재채번했다.
-- 1차 텍스트는 docs/mdm/erd/05-master-data.mssql.sql(TSK-02-03) 이며, 이 Task 가 갈라지는 지점은
-- TB_MDM_DATA_CATE 에 CK_TB_MDM_DATA_CATE_TARGET 을 추가하는 것 하나뿐이다(F18). 그 외 칼럼·타입·
-- NULL 여부·기본값·콜레이션·FK 배치는 ERD 원문을 그대로 옮긴다(불변 규칙 1·8). 실행·실측하지 않는다(F20).
-- 순환 FK 가 없으므로 단순 순서로 인라인 FK 를 건다. CASCADE 는 쓰지 않는다.

CREATE TABLE TB_MDM_DATA (
    MARU_DATA_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    MARU_DATA_NAME NVARCHAR(100) NOT NULL,
    STATUS VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL CONSTRAINT DF_TB_MDM_DATA_STATUS DEFAULT ('INUSE'),
    SOURCE_KIND VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    SOURCE_SYSTEM VARCHAR(20) COLLATE Latin1_General_100_BIN2 NULL,
    CODE_PATTERN VARCHAR(MAX) NOT NULL CONSTRAINT DF_TB_MDM_DATA_CODE_PATTERN DEFAULT ('^[0-9A-Z]{1,20}$'),
    DESCRIPTION NVARCHAR(MAX) NULL,
    ATTR01_NAME NVARCHAR(100) NULL, ATTR02_NAME NVARCHAR(100) NULL, ATTR03_NAME NVARCHAR(100) NULL,
    ATTR04_NAME NVARCHAR(100) NULL, ATTR05_NAME NVARCHAR(100) NULL, ATTR06_NAME NVARCHAR(100) NULL,
    ATTR07_NAME NVARCHAR(100) NULL, ATTR08_NAME NVARCHAR(100) NULL, ATTR09_NAME NVARCHAR(100) NULL,
    ATTR10_NAME NVARCHAR(100) NULL,
    LVL_CNT INT NOT NULL CONSTRAINT DF_TB_MDM_DATA_LVL_CNT DEFAULT (0),
    CLOSED_AT DATETIME2(0) NULL,
    LAST_CHG_SEQ BIGINT NOT NULL CONSTRAINT DF_TB_MDM_DATA_LAST_CHG_SEQ DEFAULT (0),
    CHG_SEQ BIGINT NOT NULL CONSTRAINT DF_TB_MDM_DATA_CHG_SEQ DEFAULT (0),
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_DATA PRIMARY KEY (MARU_DATA_ID),
    CONSTRAINT FK_TB_MDM_DATA_SYSTEM_SRC FOREIGN KEY (SOURCE_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_DATA_STATUS CHECK (STATUS IN ('INUSE','DEPRECATED')),
    CONSTRAINT CK_TB_MDM_DATA_SRC_KIND CHECK (SOURCE_KIND IN ('MDM','EXTERNAL')),
    CONSTRAINT CK_TB_MDM_DATA_SRC_SYS CHECK ((SOURCE_KIND = 'EXTERNAL' AND SOURCE_SYSTEM IS NOT NULL) OR (SOURCE_KIND = 'MDM' AND SOURCE_SYSTEM IS NULL)),
    CONSTRAINT CK_TB_MDM_DATA_LVL_CNT CHECK (LVL_CNT BETWEEN 0 AND 5)
);

CREATE TABLE TB_MDM_DATA_SYSTEM (
    MARU_DATA_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    SYSTEM_CODE VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DESCRIPTION NVARCHAR(MAX) NULL,
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_DATA_SYSTEM PRIMARY KEY (MARU_DATA_ID, SYSTEM_CODE),
    CONSTRAINT FK_TB_MDM_DATA_SYSTEM_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID),
    CONSTRAINT FK_TB_MDM_DATA_SYSTEM_SYSTEM FOREIGN KEY (SYSTEM_CODE) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE)
);

CREATE TABLE TB_MDM_DATA_ITEM (
    MARU_DATA_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CODE VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VALID_FROM DATETIME2(0) NOT NULL,
    NAME NVARCHAR(100) NOT NULL,
    ALTER_NAME NVARCHAR(100) NULL,
    SEQ INT NULL,
    DESCRIPTION NVARCHAR(MAX) NULL,
    VALID_TO DATETIME2(0) NOT NULL CONSTRAINT DF_TB_MDM_DATA_ITEM_VALID_TO DEFAULT ('9999-12-31 00:00:00'),
    ROW_VERSION INT NOT NULL CONSTRAINT DF_TB_MDM_DATA_ITEM_ROW_VERSION DEFAULT (0),
    CHG_SEQ BIGINT NOT NULL CONSTRAINT DF_TB_MDM_DATA_ITEM_CHG_SEQ DEFAULT (0),
    LVL1 VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL, LVL2 VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    LVL3 VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL, LVL4 VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    LVL5 VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    ATTR01 NVARCHAR(500) NULL, ATTR02 NVARCHAR(500) NULL, ATTR03 NVARCHAR(500) NULL, ATTR04 NVARCHAR(500) NULL,
    ATTR05 NVARCHAR(500) NULL, ATTR06 NVARCHAR(500) NULL, ATTR07 NVARCHAR(500) NULL, ATTR08 NVARCHAR(500) NULL,
    ATTR09 NVARCHAR(500) NULL, ATTR10 NVARCHAR(500) NULL,
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_DATA_ITEM PRIMARY KEY (MARU_DATA_ID, CODE, VALID_FROM),
    CONSTRAINT FK_TB_MDM_DATA_ITEM_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID)
);
CREATE INDEX IX_TB_MDM_DATA_ITEM_NAME ON TB_MDM_DATA_ITEM (MARU_DATA_ID, NAME);

-- CK_TB_MDM_DATA_CATE_TARGET(F18 신설) — SQLite 파일과 값 목록을 문자열로 같게 유지한다(§3.3′-B 항목 9).
CREATE TABLE TB_MDM_DATA_CATE (
    MARU_DATA_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CATE_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VALID_FROM DATETIME2(0) NOT NULL,
    CATE_NAME NVARCHAR(100) NULL,
    DEF_KIND VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DEF_EXPR VARCHAR(MAX) NULL,
    DEF_TARGET VARCHAR(20) COLLATE Latin1_General_100_BIN2 NULL,
    DESCRIPTION NVARCHAR(MAX) NULL,
    VALID_TO DATETIME2(0) NOT NULL CONSTRAINT DF_TB_MDM_DATA_CATE_VALID_TO DEFAULT ('9999-12-31 00:00:00'),
    CHG_SEQ BIGINT NOT NULL CONSTRAINT DF_TB_MDM_DATA_CATE_CHG_SEQ DEFAULT (0),
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_DATA_CATE PRIMARY KEY (MARU_DATA_ID, CATE_ID, VALID_FROM),
    CONSTRAINT FK_TB_MDM_DATA_CATE_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID),
    CONSTRAINT CK_TB_MDM_DATA_CATE_KIND CHECK (DEF_KIND IN ('REGEX','TABLE')),
    CONSTRAINT CK_TB_MDM_DATA_CATE_DEF CHECK ((DEF_KIND = 'REGEX' AND DEF_EXPR IS NOT NULL AND DEF_TARGET IS NOT NULL) OR (DEF_KIND = 'TABLE' AND DEF_EXPR IS NULL AND DEF_TARGET IS NULL)),
    CONSTRAINT CK_TB_MDM_DATA_CATE_TARGET CHECK (DEF_TARGET IS NULL OR DEF_TARGET IN ('KEY','LVL1','LVL2','LVL3','LVL4','LVL5','ATTR01','ATTR02','ATTR03','ATTR04','ATTR05','ATTR06','ATTR07','ATTR08','ATTR09','ATTR10'))
);

CREATE TABLE TB_MDM_DATA_CATE_ITEM (
    MARU_DATA_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CATE_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CODE VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VALID_FROM DATETIME2(0) NOT NULL,
    VALID_TO DATETIME2(0) NOT NULL CONSTRAINT DF_TB_MDM_DATA_CATE_ITEM_VALID_TO DEFAULT ('9999-12-31 00:00:00'),
    CHG_SEQ BIGINT NOT NULL CONSTRAINT DF_TB_MDM_DATA_CATE_ITEM_CHG_SEQ DEFAULT (0),
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_DATA_CATE_ITEM PRIMARY KEY (MARU_DATA_ID, CATE_ID, CODE, VALID_FROM),
    CONSTRAINT FK_TB_MDM_DATA_CATE_ITEM_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID)
);

CREATE TABLE TB_MDM_DATA_RECV (
    RECV_ID BIGINT IDENTITY(1,1) NOT NULL,
    MARU_DATA_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    SOURCE_SYSTEM VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    SOURCE_REF VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    RECEIVED_AT DATETIME2(0) NOT NULL,
    BODY NVARCHAR(MAX) NOT NULL,
    ROW_COUNT INT NOT NULL CONSTRAINT DF_TB_MDM_DATA_RECV_ROW_COUNT DEFAULT (0),
    [RESULT] VARCHAR(20) COLLATE Latin1_General_100_BIN2 NULL,
    RESULT_DETAIL NVARCHAR(MAX) NULL,
    CHG_SEQ BIGINT NULL,
    PROCESSED_AT DATETIME2(0) NULL,
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_DATA_RECV PRIMARY KEY (RECV_ID),
    CONSTRAINT FK_TB_MDM_DATA_RECV_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID),
    CONSTRAINT FK_TB_MDM_DATA_RECV_SYSTEM FOREIGN KEY (SOURCE_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_DATA_RECV_RESULT CHECK ([RESULT] IS NULL OR [RESULT] IN ('OK','REJECTED','FAILED'))
);

CREATE TABLE TB_MDM_DATA_RECV_ITEM (
    RECV_ID BIGINT NOT NULL,
    SEQ INT NOT NULL,
    CODE VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    [ACTION] VARCHAR(20) COLLATE Latin1_General_100_BIN2 NULL,
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_DATA_RECV_ITEM PRIMARY KEY (RECV_ID, SEQ),
    CONSTRAINT FK_TB_MDM_DATA_RECV_ITEM_RECV FOREIGN KEY (RECV_ID) REFERENCES TB_MDM_DATA_RECV (RECV_ID),
    CONSTRAINT CK_TB_MDM_DATA_RECV_ITEM_ACTION CHECK ([ACTION] IS NULL OR [ACTION] IN ('INSERT','UPDATE','CLOSE','REOPEN','NONE'))
);
