-- TSK-05-03 design.md §6.5·D2 — 레이아웃 스냅샷 버전 이력(MSSQL). 저장해 스냅샷이 바뀔 때마다 한 행이다.
-- 상태·승인·소유자는 두지 않는다(03:72). 배포는 보류(PRD §2 규칙 7) — 배포 Task 가 SNAPSHOT_JSON 을 싣는다.
-- 예약어 칼럼을 새로 만들지 않는다(naming-dialect-rules §1 — VERSION 대신 LAYOUT_VERSION). JSON 은 NVARCHAR(MAX) + ISJSON(§3 #3),
-- 코드 칼럼은 BIN2(§3 #18), 한글이 들어가는 칼럼은 NVARCHAR(§3 #19). 저장 일시·저장자는 감사 C_AT·C_USR_ID. CASCADE 없음.
CREATE TABLE TB_MDM_LAYOUT_VER (
    LAYOUT_ID BIGINT NOT NULL,
    LAYOUT_VERSION BIGINT NOT NULL,
    TOTAL_LENGTH INT NOT NULL,
    SWITCH_MODE VARCHAR(20) COLLATE Latin1_General_100_BIN2 NULL,
    CHANGE_KINDS VARCHAR(200) COLLATE Latin1_General_100_BIN2 NULL,
    CHANGE_SUMMARY NVARCHAR(1000) NULL,
    SNAPSHOT_JSON NVARCHAR(MAX) NOT NULL CONSTRAINT CK_TB_MDM_LAYOUT_VER_SNAPSHOT_JSON CHECK (ISJSON(SNAPSHOT_JSON) = 1),
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_LAYOUT_VER PRIMARY KEY (LAYOUT_ID, LAYOUT_VERSION),
    CONSTRAINT FK_TB_MDM_LAYOUT_VER_LAYOUT FOREIGN KEY (LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID),
    CONSTRAINT CK_TB_MDM_LAYOUT_VER_SWITCH CHECK (SWITCH_MODE IS NULL OR SWITCH_MODE IN ('SEQUENTIAL','SIMULTANEOUS'))
);
