-- TSK-04-01 design.md §1·§2 — 02 영역(용어·도메인·컬럼) 7테이블(MSSQL).
-- 1차 텍스트는 docs/mdm/erd/02-term-domain-column.mssql.sql(TSK-02-03) 이되, 이 Task 가 실측·재확인한
-- 지점에서 명시적으로 갈라진다(불변 규칙 §5):
--   ① FK_TB_MDM_DOMAIN_CODE(02→04, TB_MDM_CODE) 를 이번 V3 어디에도 걸지 않는다 — D1(ERD 원문도 이미 제외).
--   ② TB_MDM_TERM 에 EMBEDDING(VARBINARY(4096))·EMBEDDING_MODEL(VARCHAR(100)) 을 추가한다 — D7, F10.
-- SYSTEM_CODE 콜레이션(BIN2, F17)을 포함해 그 밖의 모든 칼럼·타입·제약은 ERD 원문을 그대로 옮긴다(불변 규칙 1).

CREATE TABLE TB_MDM_UNIT (
    UNIT_CODE VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DIMENSION VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    BASE_UNIT VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    FACTOR DECIMAL(18,9) NOT NULL,
    CHG_SEQ BIGINT NOT NULL CONSTRAINT DF_TB_MDM_UNIT_CHG_SEQ DEFAULT (0),
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_UNIT PRIMARY KEY (UNIT_CODE)
);

CREATE TABLE TB_MDM_TERM (
    TERM_ID BIGINT IDENTITY(1,1) NOT NULL,
    TERM_NAME NVARCHAR(100) NOT NULL,
    SENSE_NO INT NOT NULL,
    DEFINITION NVARCHAR(MAX) NOT NULL,
    CONTEXT NVARCHAR(100) NULL,
    ENG_NAME NVARCHAR(100) NULL,
    ENG_ABBR VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    SYNONYMS NVARCHAR(MAX) NULL,
    ALIASES NVARCHAR(MAX) NULL,
    SYSTEMS NVARCHAR(MAX) NULL,
    STD_BASIS NVARCHAR(MAX) NULL,
    OWNER_DEPT NVARCHAR(100) NULL,
    OWNER_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    SRC_ORIGIN NVARCHAR(200) NULL,
    EMBEDDING VARBINARY(4096) NULL,
    EMBEDDING_MODEL VARCHAR(100) NULL,
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_TERM PRIMARY KEY (TERM_ID),
    CONSTRAINT CK_TB_MDM_TERM_SYNONYMS_JSON CHECK (SYNONYMS IS NULL OR ISJSON(SYNONYMS) = 1),
    CONSTRAINT CK_TB_MDM_TERM_ALIASES_JSON CHECK (ALIASES IS NULL OR ISJSON(ALIASES) = 1),
    CONSTRAINT CK_TB_MDM_TERM_SYSTEMS_JSON CHECK (SYSTEMS IS NULL OR ISJSON(SYSTEMS) = 1)
);
CREATE UNIQUE INDEX UX_TB_MDM_TERM_NAME_SENSE ON TB_MDM_TERM (TERM_NAME, SENSE_NO);
CREATE UNIQUE INDEX UX_TB_MDM_TERM_ABBR ON TB_MDM_TERM (ENG_ABBR) WHERE ENG_ABBR IS NOT NULL;

CREATE TABLE TB_MDM_DOMAIN (
    DOMAIN_ID BIGINT IDENTITY(1,1) NOT NULL,
    DOMAIN_NAME NVARCHAR(100) NOT NULL,
    STD_NAME VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PARENT_DOMAIN_ID BIGINT NULL,
    DOMAIN_KIND VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DATA_TYPE VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    LENGTH INT NULL,
    SCALE INT NULL,
    UNIT_CODE VARCHAR(20) COLLATE Latin1_General_100_BIN2 NULL,
    MARU_CODE_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    CATE_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    STD_RULE VARCHAR(MAX) NULL,
    STD_AST NVARCHAR(MAX) NULL,
    BIZ_RULE VARCHAR(MAX) NULL,
    BIZ_AST NVARCHAR(MAX) NULL,
    DESCRIPTION NVARCHAR(MAX) NULL,
    EXAMPLES NVARCHAR(MAX) NULL,
    TEST_CASES NVARCHAR(MAX) NULL,
    CHG_SEQ BIGINT NOT NULL CONSTRAINT DF_TB_MDM_DOMAIN_CHG_SEQ DEFAULT (0),
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_DOMAIN PRIMARY KEY (DOMAIN_ID),
    CONSTRAINT FK_TB_MDM_DOMAIN_DOMAIN FOREIGN KEY (PARENT_DOMAIN_ID) REFERENCES TB_MDM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_TB_MDM_DOMAIN_UNIT FOREIGN KEY (UNIT_CODE) REFERENCES TB_MDM_UNIT (UNIT_CODE),
    CONSTRAINT CK_TB_MDM_DOMAIN_CODE CHECK (DOMAIN_KIND <> 'CODE' OR STD_RULE IS NULL),
    CONSTRAINT CK_TB_MDM_DOMAIN_FLAG CHECK (DOMAIN_KIND <> 'FLAG' OR PARENT_DOMAIN_ID IS NOT NULL OR STD_RULE IS NOT NULL),
    CONSTRAINT CK_TB_MDM_DOMAIN_STD_AST_JSON CHECK (STD_AST IS NULL OR ISJSON(STD_AST) = 1),
    CONSTRAINT CK_TB_MDM_DOMAIN_BIZ_AST_JSON CHECK (BIZ_AST IS NULL OR ISJSON(BIZ_AST) = 1),
    CONSTRAINT CK_TB_MDM_DOMAIN_EXAMPLES_JSON CHECK (EXAMPLES IS NULL OR ISJSON(EXAMPLES) = 1),
    CONSTRAINT CK_TB_MDM_DOMAIN_TEST_CASES_JSON CHECK (TEST_CASES IS NULL OR ISJSON(TEST_CASES) = 1)
    -- FK_TB_MDM_DOMAIN_CODE(MARU_CODE_ID→TB_MDM_CODE) 는 이번 V3 에 걸지 않는다(D1). TSK-06-01 이 후행 ALTER 로 추가한다.
);
CREATE INDEX IX_TB_MDM_DOMAIN_PARENT ON TB_MDM_DOMAIN (PARENT_DOMAIN_ID);

CREATE TABLE TB_MDM_COLUMN (
    COLUMN_ID BIGINT IDENTITY(1,1) NOT NULL,
    COLUMN_NAME NVARCHAR(100) NOT NULL,
    LABEL_LONG NVARCHAR(24) NULL,
    LABEL_MID NVARCHAR(12) NULL,
    LABEL_SHORT NVARCHAR(6) NULL,
    PHYS_NAME VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DESCRIPTION NVARCHAR(MAX) NULL,
    DOMAIN_ID BIGINT NOT NULL,
    REQUIRED BIT NOT NULL CONSTRAINT DF_TB_MDM_COLUMN_REQUIRED DEFAULT (0),
    DEFAULT_VALUE VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    REF_KIND VARCHAR(20) COLLATE Latin1_General_100_BIN2 NULL,
    REF_TARGET VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    REF_CATE_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    TERM_IDS NVARCHAR(MAX) NULL,
    USAGE_NOTE NVARCHAR(MAX) NULL,
    CHG_SEQ BIGINT NOT NULL CONSTRAINT DF_TB_MDM_COLUMN_CHG_SEQ DEFAULT (0),
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_COLUMN PRIMARY KEY (COLUMN_ID),
    CONSTRAINT FK_TB_MDM_COLUMN_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES TB_MDM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_TB_MDM_COLUMN_TERM_IDS_JSON CHECK (TERM_IDS IS NULL OR ISJSON(TERM_IDS) = 1)
    -- REQUIRED 는 BIT 라 CK 불필요(SQLite 만 CK_TB_MDM_COLUMN_REQUIRED 를 둔다, §6.0 BOOLEAN 비대칭)
);
CREATE UNIQUE INDEX UX_TB_MDM_COLUMN_NAME ON TB_MDM_COLUMN (COLUMN_NAME);
CREATE UNIQUE INDEX UX_TB_MDM_COLUMN_PHYS_NAME ON TB_MDM_COLUMN (PHYS_NAME);

CREATE TABLE TB_MDM_COLUMN_SYSTEM (
    COLUMN_ID BIGINT NOT NULL,
    SYSTEM_CODE VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PHYS_NAME VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    TRANSFORM VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    NOTE NVARCHAR(MAX) NULL,
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_COLUMN_SYSTEM PRIMARY KEY (COLUMN_ID, SYSTEM_CODE, PHYS_NAME),
    CONSTRAINT FK_TB_MDM_COLUMN_SYSTEM_COLUMN FOREIGN KEY (COLUMN_ID) REFERENCES TB_MDM_COLUMN (COLUMN_ID),
    CONSTRAINT FK_TB_MDM_COLUMN_SYSTEM_SYSTEM FOREIGN KEY (SYSTEM_CODE) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE)
);
CREATE INDEX IX_TB_MDM_COLUMN_SYSTEM_SYS_PHYS ON TB_MDM_COLUMN_SYSTEM (SYSTEM_CODE, PHYS_NAME);

-- 보류 테이블(배포 안 함, D2·D-019·D-031 계승). 엔티티·리포지토리를 붙이지 않는다. 감사 9칼럼 예외 — 두지 않는다.
CREATE TABLE TB_MDM_DICT_SEQ (
    DICT_CODE VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    LAST_CHG_SEQ BIGINT NOT NULL CONSTRAINT DF_TB_MDM_DICT_SEQ_LAST_CHG_SEQ DEFAULT (0),
    CONSTRAINT PK_TB_MDM_DICT_SEQ PRIMARY KEY (DICT_CODE),
    CONSTRAINT CK_TB_MDM_DICT_SEQ_CODE CHECK (DICT_CODE = 'DOMAIN')
);
INSERT INTO TB_MDM_DICT_SEQ (DICT_CODE, LAST_CHG_SEQ) VALUES ('DOMAIN', 0);

-- 보류 테이블(배포 안 함, D2·D-019·D-031 계승). 엔티티·리포지토리를 붙이지 않는다.
CREATE TABLE TB_MDM_DICT_SYSTEM (
    DICT_CODE VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    SYSTEM_CODE VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    NOTE NVARCHAR(MAX) NULL,
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_DICT_SYSTEM PRIMARY KEY (DICT_CODE, SYSTEM_CODE),
    CONSTRAINT FK_TB_MDM_DICT_SYSTEM_DICT_SEQ FOREIGN KEY (DICT_CODE) REFERENCES TB_MDM_DICT_SEQ (DICT_CODE),
    CONSTRAINT FK_TB_MDM_DICT_SYSTEM_SYSTEM FOREIGN KEY (SYSTEM_CODE) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_DICT_SYSTEM_CODE CHECK (DICT_CODE = 'DOMAIN')
);
