-- TSK-06-01 design.md §1·§2·§6.0 — 04 영역(마스터코드) 7테이블(MSSQL) + FK_TB_MDM_DOMAIN_CODE 후행 추가.
-- 버전 번호는 팀장 배정 V6 이다(D1 — V5 는 다른 Task 몫이라 비워 둔다).
-- 1차 텍스트는 docs/mdm/erd/04-master-code.mssql.sql(TSK-02-03) 이되, 이 Task 가 실측·원천 대조로 갈라진
-- 지점만 바꾼다(§6.0 G1~G5):
--   G1 (SQLite 전용 — 감사 카운터 BIGINT) MSSQL ERD 는 이미 BIGINT 다.
--   G2 TB_MDM_CODE_VER.ROW_VERSION 은 INT 가 아니라 BIGINT — D5(TSK-01-03 §7 ② 인계, VersionConventions long).
--   G3 CK_TB_MDM_CODE_VER_APPLY 는 REQUESTED 행(apply_from 만 있고 apply_to NULL)을 받는다 — D4(원천 04:999-1000).
--   G4 TB_MDM_CODE_CATE.DEF_EXPR 는 VARCHAR(MAX) 가 아니라 NVARCHAR(MAX) — D6(REGEX 대상 ATTR 칸의 한글 정규식).
--   G5 파일 끝에서 ALTER TABLE TB_MDM_DOMAIN ADD CONSTRAINT FK_TB_MDM_DOMAIN_CODE — D3(TSK-04-01 D1 인계,
--      ERD 99-cross-area-fk.mssql.sql 의 문장). 부모 TB_MDM_CODE 가 먼저 생긴 뒤에 건다.
-- 생성 순서: CODE → CODE_SYSTEM → CODE_VER → CODE_ITEM → CODE_CATE → CODE_CATE_ITEM → CODE_RECV → FK ALTER.
-- 부모 TB_MDM_SYSTEM(V2)·TB_MDM_DOMAIN(V3)은 이미 있고 FK 칼럼 타입·COLLATE 가 같다(VARCHAR(20)/VARCHAR(50) BIN2).
-- CASCADE 는 어디에도 쓰지 않는다(불변 규칙 8).

CREATE TABLE TB_MDM_CODE (
    MARU_CODE_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    MARU_CODE_NAME NVARCHAR(100) NOT NULL,
    STATUS VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL CONSTRAINT DF_TB_MDM_CODE_STATUS DEFAULT ('CREATED'),
    SOURCE_KIND VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    SOURCE_SYSTEM VARCHAR(20) COLLATE Latin1_General_100_BIN2 NULL,
    DESCRIPTION NVARCHAR(MAX) NULL,
    ATTR01_NAME NVARCHAR(100) NULL, ATTR02_NAME NVARCHAR(100) NULL, ATTR03_NAME NVARCHAR(100) NULL,
    ATTR04_NAME NVARCHAR(100) NULL, ATTR05_NAME NVARCHAR(100) NULL, ATTR06_NAME NVARCHAR(100) NULL,
    ATTR07_NAME NVARCHAR(100) NULL, ATTR08_NAME NVARCHAR(100) NULL, ATTR09_NAME NVARCHAR(100) NULL,
    ATTR10_NAME NVARCHAR(100) NULL,
    LVL_CNT INT NOT NULL CONSTRAINT DF_TB_MDM_CODE_LVL_CNT DEFAULT (0),
    LAST_CHG_SEQ BIGINT NOT NULL CONSTRAINT DF_TB_MDM_CODE_LAST_CHG_SEQ DEFAULT (0),
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_CODE PRIMARY KEY (MARU_CODE_ID),
    CONSTRAINT FK_TB_MDM_CODE_SYSTEM_SRC FOREIGN KEY (SOURCE_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_CODE_STATUS CHECK (STATUS IN ('CREATED','INUSE','DEPRECATED')),
    CONSTRAINT CK_TB_MDM_CODE_SRC_KIND CHECK (SOURCE_KIND IN ('MDM','EXTERNAL')),
    CONSTRAINT CK_TB_MDM_CODE_SRC_SYS CHECK ((SOURCE_KIND = 'EXTERNAL' AND SOURCE_SYSTEM IS NOT NULL) OR (SOURCE_KIND = 'MDM' AND SOURCE_SYSTEM IS NULL)),
    CONSTRAINT CK_TB_MDM_CODE_LVL_CNT CHECK (LVL_CNT BETWEEN 0 AND 5)
);

-- 보류 테이블(배포 안 함, D-019·ADR-0002 D7). 엔티티·리포지토리를 붙이지 않는다(D2).
CREATE TABLE TB_MDM_CODE_SYSTEM (
    MARU_CODE_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    SYSTEM_CODE VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DESCRIPTION NVARCHAR(MAX) NULL,
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_CODE_SYSTEM PRIMARY KEY (MARU_CODE_ID, SYSTEM_CODE),
    CONSTRAINT FK_TB_MDM_CODE_SYSTEM_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID),
    CONSTRAINT FK_TB_MDM_CODE_SYSTEM_SYSTEM FOREIGN KEY (SYSTEM_CODE) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE)
);

-- 업무 칼럼 VER 과 감사 카운터가 이름이 겹쳐 감사 카운터만 AUD_VER 로 둔다(D-034).
CREATE TABLE TB_MDM_CODE_VER (
    MARU_CODE_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VER DECIMAL(7,3) NOT NULL,
    VER_KIND VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    RESTORED_FROM DECIMAL(7,3) NULL,
    STATUS VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL CONSTRAINT DF_TB_MDM_CODE_VER_STATUS DEFAULT ('DRAFT'),
    OWNER_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    APPLY_FROM DATETIME2(0) NULL,
    APPLY_TO DATETIME2(0) NULL,
    DESCRIPTION NVARCHAR(MAX) NULL,
    REQUESTED_BY VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    REQUESTED_AT DATETIME2(0) NULL,
    EMERGENCY_YN VARCHAR(1) COLLATE Latin1_General_100_BIN2 NOT NULL CONSTRAINT DF_TB_MDM_CODE_VER_EMERGENCY_YN DEFAULT ('N'),
    EMERGENCY_REASON NVARCHAR(MAX) NULL,
    APPROVED_BY VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    APPROVED_AT DATETIME2(0) NULL,
    REJECT_REASON NVARCHAR(MAX) NULL,
    RELEASED_AT DATETIME2(0) NULL,
    CANCELLED_AT DATETIME2(0) NULL,
    CANCEL_REASON NVARCHAR(MAX) NULL,
    ROW_VERSION BIGINT NOT NULL CONSTRAINT DF_TB_MDM_CODE_VER_ROW_VERSION DEFAULT (0),
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    AUD_VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_CODE_VER PRIMARY KEY (MARU_CODE_ID, VER),
    CONSTRAINT FK_TB_MDM_CODE_VER_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID),
    CONSTRAINT CK_TB_MDM_CODE_VER_KIND CHECK (VER_KIND IN ('MAJOR','MINOR')),
    CONSTRAINT CK_TB_MDM_CODE_VER_STATUS CHECK (STATUS IN ('DRAFT','REQUESTED','APPROVED','RELEASED','CANCELLED')),
    CONSTRAINT CK_TB_MDM_CODE_VER_APPLY CHECK (STATUS = 'DRAFT' OR (APPLY_FROM IS NOT NULL AND (STATUS = 'REQUESTED' OR APPLY_TO IS NOT NULL))),
    CONSTRAINT CK_TB_MDM_CODE_VER_EMERGENCY_YN CHECK (EMERGENCY_YN IN ('Y','N'))
);

CREATE TABLE TB_MDM_CODE_ITEM (
    MARU_CODE_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CODE VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    FROM_VER DECIMAL(7,3) NOT NULL,
    TO_VER DECIMAL(7,3) NOT NULL CONSTRAINT DF_TB_MDM_CODE_ITEM_TO_VER DEFAULT (9999),
    NAME NVARCHAR(100) NULL,
    ALTER_NAME NVARCHAR(100) NULL,
    SEQ INT NULL,
    DESCRIPTION NVARCHAR(MAX) NULL,
    LVL1 VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL, LVL2 VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    LVL3 VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL, LVL4 VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    LVL5 VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    ATTR01 NVARCHAR(500) NULL, ATTR02 NVARCHAR(500) NULL, ATTR03 NVARCHAR(500) NULL, ATTR04 NVARCHAR(500) NULL,
    ATTR05 NVARCHAR(500) NULL, ATTR06 NVARCHAR(500) NULL, ATTR07 NVARCHAR(500) NULL, ATTR08 NVARCHAR(500) NULL,
    ATTR09 NVARCHAR(500) NULL, ATTR10 NVARCHAR(500) NULL,
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_CODE_ITEM PRIMARY KEY (MARU_CODE_ID, CODE, FROM_VER),
    CONSTRAINT FK_TB_MDM_CODE_ITEM_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID),
    CONSTRAINT FK_TB_MDM_CODE_ITEM_VER FOREIGN KEY (MARU_CODE_ID, FROM_VER) REFERENCES TB_MDM_CODE_VER (MARU_CODE_ID, VER),
    CONSTRAINT CK_TB_MDM_CODE_ITEM_CODE CHECK (CODE NOT LIKE '% %' AND CODE NOT LIKE '%,%')
);

CREATE TABLE TB_MDM_CODE_CATE (
    MARU_CODE_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CATE_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    FROM_VER DECIMAL(7,3) NOT NULL,
    TO_VER DECIMAL(7,3) NOT NULL CONSTRAINT DF_TB_MDM_CODE_CATE_TO_VER DEFAULT (9999),
    CATE_NAME NVARCHAR(100) NULL,
    DEF_KIND VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DEF_EXPR NVARCHAR(MAX) NULL,
    DEF_TARGET VARCHAR(20) COLLATE Latin1_General_100_BIN2 NULL,
    DESCRIPTION NVARCHAR(MAX) NULL,
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_CODE_CATE PRIMARY KEY (MARU_CODE_ID, CATE_ID, FROM_VER),
    CONSTRAINT FK_TB_MDM_CODE_CATE_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID),
    CONSTRAINT FK_TB_MDM_CODE_CATE_VER FOREIGN KEY (MARU_CODE_ID, FROM_VER) REFERENCES TB_MDM_CODE_VER (MARU_CODE_ID, VER),
    CONSTRAINT CK_TB_MDM_CODE_CATE_KIND CHECK (DEF_KIND IN ('REGEX','TABLE')),
    CONSTRAINT CK_TB_MDM_CODE_CATE_DEF CHECK ((DEF_KIND = 'REGEX' AND DEF_EXPR IS NOT NULL AND DEF_TARGET IS NOT NULL) OR (DEF_KIND = 'TABLE' AND DEF_EXPR IS NULL AND DEF_TARGET IS NULL))
);

-- CATE_ID·CODE 자체는 FK 없음(불변 규칙 7 — 저장 시·상신 시 앱 검사). TO_VER 도 FK 없음(04:958).
CREATE TABLE TB_MDM_CODE_CATE_ITEM (
    MARU_CODE_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CATE_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CODE VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    FROM_VER DECIMAL(7,3) NOT NULL,
    TO_VER DECIMAL(7,3) NOT NULL CONSTRAINT DF_TB_MDM_CODE_CATE_ITEM_TO_VER DEFAULT (9999),
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_CODE_CATE_ITEM PRIMARY KEY (MARU_CODE_ID, CATE_ID, CODE, FROM_VER),
    CONSTRAINT FK_TB_MDM_CODE_CATE_ITEM_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID),
    CONSTRAINT FK_TB_MDM_CODE_CATE_ITEM_VER FOREIGN KEY (MARU_CODE_ID, FROM_VER) REFERENCES TB_MDM_CODE_VER (MARU_CODE_ID, VER)
);

-- 보류 테이블(수신 로그, D-019·ADR-0002 D7). 엔티티·리포지토리를 붙이지 않는다(D2). RECV_ID 는 서버 채번(규칙표 #2).
CREATE TABLE TB_MDM_CODE_RECV (
    RECV_ID BIGINT IDENTITY(1,1) NOT NULL,
    MARU_CODE_ID VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    SOURCE_SYSTEM VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    SOURCE_REF VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    REQ_KIND VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    RECEIVED_AT DATETIME2(0) NOT NULL,
    BODY NVARCHAR(MAX) NOT NULL,
    [RESULT] VARCHAR(20) COLLATE Latin1_General_100_BIN2 NULL,
    RESULT_DETAIL NVARCHAR(MAX) NULL,
    VER DECIMAL(7,3) NULL,
    CHG_SEQ BIGINT NULL,
    PROCESSED_AT DATETIME2(0) NULL,
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    AUD_VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_CODE_RECV PRIMARY KEY (RECV_ID),
    CONSTRAINT FK_TB_MDM_CODE_RECV_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID),
    CONSTRAINT FK_TB_MDM_CODE_RECV_SYSTEM FOREIGN KEY (SOURCE_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_CODE_RECV_REQ CHECK (REQ_KIND IN ('VERSION','CANCEL','DEPRECATE')),
    CONSTRAINT CK_TB_MDM_CODE_RECV_RESULT CHECK ([RESULT] IS NULL OR [RESULT] IN ('OK','REJECTED','FAILED'))
);

-- G5: 02→04 교차 FK(D3). SQLite 는 같은 이름의 FK 를 TB_MDM_DOMAIN 재생성으로 건다.
ALTER TABLE TB_MDM_DOMAIN
    ADD CONSTRAINT FK_TB_MDM_DOMAIN_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID);
