// node --test scripts/widget-registry-lib.test.mjs — 위젯 등록부 생성 규칙.
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import { collectWidgets, keyToId, renderRegistry } from "./widget-registry-lib.mjs";

async function makeWidget(root, group, name, { id = `${group}.${name}`, body = true } = {}) {
  const dir = path.join(root, group, name);
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, "widget.meta.ts"), `export const meta = { id: "${id}", title: "t", defaultSize: { w: 6, h: 6 } };\n`);
  if (body) await writeFile(path.join(dir, "widget.tsx"), "export default function W() { return null; }\n");
}

test("keyToId 는 group/name 을 group.name 으로 바꾼다", () => {
  assert.equal(keyToId("home/notice"), "home.notice");
});

test("collectWidgets 는 meta·본체 짝이 있는 2단 폴더만 이름순으로 모은다", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "wreg-"));
  await makeWidget(root, "home", "notice");
  await makeWidget(root, "home", "alarms");
  await makeWidget(root, "_shared", "skip");
  const result = await collectWidgets(root);
  assert.deepEqual(result.map((w) => w.key), ["home/alarms", "home/notice"]);
});

test("본체(widget.tsx)가 없으면 오류", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "wreg-"));
  await makeWidget(root, "home", "notice", { body: false });
  await assert.rejects(() => collectWidgets(root), /widget\.tsx/);
});

test("meta 의 id 가 폴더와 다르면 오류", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "wreg-"));
  await makeWidget(root, "home", "notice", { id: "home.news" });
  await assert.rejects(() => collectWidgets(root), /home\.notice/);
});

test("renderRegistry 는 meta 정적 import 와 본체 지연 import 리터럴을 쓴다", () => {
  const out = renderRegistry([
    { id: "home.alarms", metaImport: "@/widgets/home/alarms/widget.meta", bodyImport: "@/widgets/home/alarms/widget" },
    { id: "home.notice", metaImport: "@/widgets/home/notice/widget.meta", bodyImport: "@/widgets/home/notice/widget" },
  ]);
  assert.match(out, /^\/\/ AUTO-GENERATED by scripts\/generate-widget-registry\.mjs/);
  assert.match(out, /import \{ meta as m0 \} from "@\/widgets\/home\/alarms\/widget\.meta";/);
  assert.match(out, /"home\.notice": \{ meta: m1, load: \(\) => import\("@\/widgets\/home\/notice\/widget"\) \},/);
  assert.match(out, /export const WIDGET_REGISTRY: WidgetRegistry = \{/);
});

test("renderRegistry 는 같은 id 가 두 번이면 오류", () => {
  assert.throws(
    () =>
      renderRegistry([
        { id: "home.a", metaImport: "x", bodyImport: "y" },
        { id: "home.a", metaImport: "x2", bodyImport: "y2" },
      ]),
    /중복/
  );
});
