// node --test scripts/widget-registry-lib.test.mjs — 위젯 등록부 생성 규칙.
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import { collectWidgetTypes, collectWidgets, keyToId, renderRegistry, renderTypeRegistry } from "./widget-registry-lib.mjs";

async function makeWidget(root, group, name, { id = `${group}.${name}`, body = true } = {}) {
  const dir = path.join(root, group, name);
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, "widget.meta.ts"), `export const meta = { id: "${id}", title: "t", defaultSize: { w: 6, h: 6 } };\n`);
  if (body) await writeFile(path.join(dir, "widget.tsx"), "export default function W() { return null; }\n");
}

test("keyToId 는 group/name 을 group.name 으로 바꾼다", () => {
  assert.equal(keyToId("home/notice"), "home.notice");
});

test("collectWidgets 는 meta·본체 짝이 있는 2단 폴더만 이름순으로 모은다", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "wreg-"));
  await makeWidget(root, "home", "notice");
  await makeWidget(root, "home", "alarms");
  await makeWidget(root, "_shared", "skip");
  const result = await collectWidgets(root);
  assert.deepEqual(result.map((w) => w.key), ["home/alarms", "home/notice"]);
});

test("본체(widget.tsx)가 없으면 오류", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "wreg-"));
  await makeWidget(root, "home", "notice", { body: false });
  await assert.rejects(() => collectWidgets(root), /widget\.tsx/);
});

test("meta 의 id 가 폴더와 다르면 오류", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "wreg-"));
  await makeWidget(root, "home", "notice", { id: "home.news" });
  await assert.rejects(() => collectWidgets(root), /home\.notice/);
});

test("renderRegistry 는 meta 정적 import 와 본체 지연 import 리터럴을 쓴다", () => {
  const out = renderRegistry([
    { id: "home.alarms", metaImport: "@/widgets/home/alarms/widget.meta", bodyImport: "@/widgets/home/alarms/widget" },
    { id: "home.notice", metaImport: "@/widgets/home/notice/widget.meta", bodyImport: "@/widgets/home/notice/widget" },
  ]);
  assert.match(out, /^\/\/ AUTO-GENERATED by scripts\/generate-widget-registry\.mjs/);
  assert.match(out, /import \{ meta as m0 \} from "@\/widgets\/home\/alarms\/widget\.meta";/);
  assert.match(out, /"home\.notice": \{ meta: m1, load: \(\) => import\("@\/widgets\/home\/notice\/widget"\) \},/);
  assert.match(out, /export const WIDGET_REGISTRY: WidgetRegistry = \{/);
});

test("renderRegistry 는 같은 id 가 두 번이면 오류", () => {
  assert.throws(
    () =>
      renderRegistry([
        { id: "home.a", metaImport: "x", bodyImport: "y" },
        { id: "home.a", metaImport: "x2", bodyImport: "y2" },
      ]),
    /중복/
  );
});

// ── 위젯 유형 등록부(스펙 2026-10-02-widget-admin-generic §3) ──────────────────────────────

async function makeType(root, name, { id = name, files = ["type.meta.ts", "renderer.tsx", "editor.tsx"] } = {}) {
  const dir = path.join(root, name);
  await mkdir(dir, { recursive: true });
  for (const f of files) {
    const body =
      f === "type.meta.ts"
        ? `export const meta = { id: "${id}", title: "t", defaultSize: { w: 6, h: 6 }, initialConfig: {} };\n`
        : "export default function X() { return null; }\n";
    await writeFile(path.join(dir, f), body);
  }
}

test("collectWidgetTypes 는 세 파일이 다 있는 유형 폴더만 이름순으로 모으고 _ 폴더는 건너뛴다", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "wtype-"));
  await makeType(root, "query-table");
  await makeType(root, "markdown");
  await mkdir(path.join(root, "_shared"), { recursive: true });
  const result = await collectWidgetTypes(root);
  assert.deepEqual(result.map((t) => t.id), ["markdown", "query-table"]);
});

test("collectWidgetTypes 는 폴더가 없으면 빈 목록", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "wtype-"));
  assert.deepEqual(await collectWidgetTypes(path.join(root, "none")), []);
});

test("유형 파일이 빠지면 오류", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "wtype-"));
  await makeType(root, "markdown", { files: ["type.meta.ts", "renderer.tsx"] });
  await assert.rejects(() => collectWidgetTypes(root), /editor\.tsx/);
});

test("type.meta 의 id 가 폴더와 다르면 오류", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "wtype-"));
  await makeType(root, "markdown", { id: "md" });
  await assert.rejects(() => collectWidgetTypes(root), /"markdown"/);
});

test("유형 폴더 이름이 규칙(소문자·숫자·하이픈)을 어기면 오류", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "wtype-"));
  await makeType(root, "QueryTable");
  await assert.rejects(() => collectWidgetTypes(root), /소문자/);
});

test("renderTypeRegistry 는 meta 정적 import 와 렌더러·편집기 지연 import 리터럴을 쓴다", () => {
  const out = renderTypeRegistry([{ id: "markdown" }, { id: "query-table" }]);
  assert.match(out, /import \{ meta as t1 \} from "@\/widget-types\/query-table\/type\.meta";/);
  assert.match(out, /loadRenderer: \(\) => import\("@\/widget-types\/markdown\/renderer"\)/);
  assert.match(out, /loadEditor: \(\) => import\("@\/widget-types\/query-table\/editor"\)/);
  assert.match(out, /export const WIDGET_TYPE_REGISTRY: WidgetTypeRegistry = \{/);
  assert.throws(() => renderTypeRegistry([{ id: "a" }, { id: "a" }]), /중복/);
});
