-- 샘플 공통 코드 초기 스키마 (템플릿 플레이스홀더).
-- 식별자 자동 증가 구문은 방언마다 다르므로(MSSQL: IDENTITY(1,1), PostgreSQL: GENERATED BY DEFAULT AS IDENTITY,
-- H2: AUTO_INCREMENT) 실제 프로젝트에서 사용하는 방언에 맞춰 조정한다.
-- 후속 마이그레이션 채번은 `/flyway-migration-add` 스킬을 사용한다.

CREATE TABLE sample_master_code
(
    id         BIGINT       NOT NULL PRIMARY KEY,
    code_group VARCHAR(50)  NOT NULL,
    code_value VARCHAR(50)  NOT NULL,
    label      VARCHAR(200) NOT NULL,
    sort_order INTEGER      NOT NULL DEFAULT 0,
    use_yn     CHAR(1)      NOT NULL DEFAULT 'Y'
);

CREATE UNIQUE INDEX ux_sample_master_code_group_value ON sample_master_code (code_group, code_value);
