-- mqc Oracle 기준선 (초안, 2026-10-07 oracle-1007 ora-platform p3). 소유 사용자 MQCAPUSER, 스키마 접두 없음.
-- result 는 예약어가 아니지만 엔티티와 같은 이름을 유지한다. remark 는 NULL 허용(Oracle 은 빈 문자열을 NULL 로 저장).
CREATE TABLE sample_inspection_result (
    id           NUMBER(19)          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_no       VARCHAR2(50 CHAR)   NOT NULL,
    inspected_at TIMESTAMP(6)        NOT NULL,
    result       VARCHAR2(10 CHAR)   NOT NULL,
    remark       VARCHAR2(500 CHAR)
);
