-- aps-core Oracle 기준선 (초안, 2026-10-07 oracle-1007 ora-platform p3). 소유 사용자는 APSAPUSER 로 가정한다.
-- SampleItem 엔티티는 IDENTITY 를 쓰므로 id 를 IDENTITY 로 둔다(기존 SQL 은 BIGINT 직접 채번이었다).
CREATE TABLE sample_item (
    id         NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR2(50 CHAR)  NOT NULL,
    name       VARCHAR2(200 CHAR) NOT NULL,
    status     VARCHAR2(20 CHAR)  NOT NULL,
    created_at TIMESTAMP(6)       NOT NULL
);

CREATE UNIQUE INDEX ux_sample_item_code ON sample_item (code);
