-- ============================================================
-- V2: 테이블·칼럼 주석 채우기
-- ============================================================
--
-- 대상 스키마: MCAAPUSER   위치: oracle/mcaapuser
-- 이 파일은 그 스키마 주인으로 접속해 실행된다(앱 Flyway 또는 pdb.mjs template-schema, 운영은 DBA).
--
-- 배경 (사용자 요청, 2026-10-09):
--   DB 뷰어 칼럼명은 MDM 컬럼 사전 이름, 없으면 Oracle 칼럼 주석이다. 주석이 없던 칼럼 39개와 테이블 2개에 주석을 넣는다.
--   이름 근거는 docs/db/column-comments-2026-10-09.md 에 있다. 주석만 바꾸며 데이터·구조는 건드리지 않는다.
-- ============================================================

COMMENT ON TABLE TB_MCA_RULE_COL_LIST IS '업무기준 항목 목록';
COMMENT ON TABLE TB_MCA_RULE_MASTER IS '업무기준 마스터';

COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.COL_ID IS '항목 영문명';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.COL_LEN IS '총길이';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.COL_NM IS '항목 한글명';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.COL_PREC_LEN IS '소수점 길이';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.COL_SEQ IS '열 순번';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.COL_TYPE IS '항목 유형';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.C_AT IS '생성일시';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.C_PGM_ID IS '생성 프로그램 아이디';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.C_SVC_ID IS '생성 서비스 아이디';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.C_USR_ID IS '생성자 아이디';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.IO_FLAG IS '입출력 구분';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.MASTER_CODE_DIV IS '코드 여부';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.MES_COL_ID IS 'MES 항목 아이디';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.OLD_COL_ID IS '이전 항목 아이디';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.RULE_ID IS '업무기준 아이디';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.RULE_VER IS '업무기준 버전';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.U_AT IS '수정일시';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.U_PGM_ID IS '수정 프로그램 아이디';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.U_SVC_ID IS '수정 서비스 아이디';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.U_USR_ID IS '수정자 아이디';
COMMENT ON COLUMN TB_MCA_RULE_COL_LIST.VER IS '버전';

COMMENT ON COLUMN TB_MCA_RULE_MASTER.C_AT IS '생성일시';
COMMENT ON COLUMN TB_MCA_RULE_MASTER.C_PGM_ID IS '생성 프로그램 아이디';
COMMENT ON COLUMN TB_MCA_RULE_MASTER.C_SVC_ID IS '생성 서비스 아이디';
COMMENT ON COLUMN TB_MCA_RULE_MASTER.C_USR_ID IS '생성자 아이디';
COMMENT ON COLUMN TB_MCA_RULE_MASTER.OLD_RULE_ID IS '이전 업무기준 아이디';
COMMENT ON COLUMN TB_MCA_RULE_MASTER.RULE_DESC IS '업무기준 설명';
COMMENT ON COLUMN TB_MCA_RULE_MASTER.RULE_ID IS '업무기준 아이디';
COMMENT ON COLUMN TB_MCA_RULE_MASTER.RULE_NM IS '업무기준 명';
COMMENT ON COLUMN TB_MCA_RULE_MASTER.RULE_OWNER_DEPT_NM IS '업무기준 담당 부서명';
COMMENT ON COLUMN TB_MCA_RULE_MASTER.RULE_OWNER_EMP_NO IS '업무기준 담당 사원번호';
COMMENT ON COLUMN TB_MCA_RULE_MASTER.RULE_TP IS '업무기준 유형';
COMMENT ON COLUMN TB_MCA_RULE_MASTER.RULE_VER IS '업무기준 버전';
COMMENT ON COLUMN TB_MCA_RULE_MASTER.USE_TP IS '사용 구분';
COMMENT ON COLUMN TB_MCA_RULE_MASTER.U_AT IS '수정일시';
COMMENT ON COLUMN TB_MCA_RULE_MASTER.U_PGM_ID IS '수정 프로그램 아이디';
COMMENT ON COLUMN TB_MCA_RULE_MASTER.U_SVC_ID IS '수정 서비스 아이디';
COMMENT ON COLUMN TB_MCA_RULE_MASTER.U_USR_ID IS '수정자 아이디';
COMMENT ON COLUMN TB_MCA_RULE_MASTER.VER IS '버전';
