import { defineConfig } from "tsup";

export default defineConfig((options) => ({
  entry: {
    index: "src/index.ts",
    http: "src/http/index.ts",
    "secure-storage": "src/secure-storage/index.ts",
    snapshot: "src/snapshot/index.ts",
    "portal-shell-core": "src/portal-shell/core.ts",
    "portal-shell": "src/portal-shell/index.ts",
    "portal-menu": "src/portal-menu/index.ts",
    "auth-cookies": "src/auth/cookies.ts",
    "auth-proxy": "src/auth/proxy.ts",
    "auth-server": "src/auth/server.ts",
    "auth-routes": "src/auth/routes.ts",
    "auth-rbac-policy": "src/auth/rbac-policy.ts",
    "auth-login-form": "src/auth/login-form.tsx",
    "auth-login-page": "src/auth/login-page.tsx",
    layout: "src/layout/index.ts",
    "pages/home-page": "src/pages/home-page.tsx",
    utils: "src/utils/index.ts",
    "error-boundary": "src/components/error-boundary.tsx",
    "use-form-validation": "src/hooks/use-form-validation.ts",
    "use-api-call": "src/hooks/use-api-call.ts",
    modal: "src/components/modal.tsx",
    "message-provider": "src/components/message-provider.tsx",
    "ui-provider": "src/ui-provider/index.tsx",
    variables: "src/styles/variables.css",
    form: "src/components/form/index.ts",
    grid: "src/components/grid/index.ts",
    tree: "src/components/tree/index.ts",
    tabs: "src/components/tabs/index.ts",
    charts: "src/components/charts/index.ts",
    "matrix-table": "src/components/matrix-table/index.ts",
    lookup: "src/components/lookup/index.ts",
    oasis: "src/oasis/index.ts",
    "oasis-proxy": "src/oasis-proxy/index.ts",
    lib: "src/lib/index.ts",
  },
  format: ["esm"],
  target: "es2022",
  // .d.ts 생성(가장 오래 걸리는 단계)은 기본으로 켠다. 소비 패키지의 tsc(lint)를 돌리지 않는 단위 테스트 게이트만
  // TSUP_DTS=0 으로 끈다(next dev·vitest 는 .d.ts 를 쓰지 않는다. perf-audit (B) 표).
  dts: process.env.TSUP_DTS !== "0",
  sourcemap: true,
  clean: !options.watch,
  splitting: false,
  external: [
    "react",
    "react-dom",
    "next",
    "next/navigation",
    "next/server",
    "next-auth",
    "next-auth/jwt",
    "next-auth/react",
    "next-auth/providers/credentials",
    "ag-grid-react",
    "ag-grid-community",
    "@mantine/core",
    "@mantine/hooks",
    "@mantine/dates",
    "@mantine/notifications",
    "@mantine/modals",
    "dayjs",
    "@tabler/icons-react",
    "clsx",
    "xlsx",
  ],
  loader: {
    ".svg": "dataurl",
  },
}));
