import { defineConfig } from "tsup";

export default defineConfig((options) => ({
  entry: {
    index: "src/index.ts",
    http: "src/http/index.ts",
    "secure-storage": "src/secure-storage/index.ts",
    snapshot: "src/snapshot/index.ts",
    "portal-shell-core": "src/portal-shell/core.ts",
    "portal-shell": "src/portal-shell/index.ts",
    "portal-menu": "src/portal-menu/index.ts",
    "auth-cookies": "src/auth/cookies.ts",
    "auth-proxy": "src/auth/proxy.ts",
    "auth-server": "src/auth/server.ts",
    "auth-routes": "src/auth/routes.ts",
    "auth-rbac-policy": "src/auth/rbac-policy.ts",
    "auth-login-form": "src/auth/login-form.tsx",
    "auth-login-page": "src/auth/login-page.tsx",
    layout: "src/layout/index.ts",
    "pages/home-page": "src/pages/home-page.tsx",
    utils: "src/utils/index.ts",
    "error-boundary": "src/components/error-boundary.tsx",
    "use-form-validation": "src/hooks/use-form-validation.ts",
    "use-api-call": "src/hooks/use-api-call.ts",
    modal: "src/components/modal.tsx",
    "message-provider": "src/components/message-provider.tsx",
    "ui-provider": "src/ui-provider/index.tsx",
    variables: "src/styles/variables.css",
    form: "src/components/form/index.ts",
    grid: "src/components/grid/index.ts",
    tree: "src/components/tree/index.ts",
    tabs: "src/components/tabs/index.ts",
    charts: "src/components/charts/index.ts",
    "matrix-table": "src/components/matrix-table/index.ts",
    lookup: "src/components/lookup/index.ts",
    "markdown-editor": "src/components/markdown-editor/index.ts",
    "notice-body-view": "src/components/notice-body-view/index.ts",
    "detail-popover": "src/components/detail-popover/index.ts",
    "json-view": "src/components/json-view/index.ts",
    dashboard: "src/components/dashboard/index.ts",
    widget: "src/widget/index.ts",
    oasis: "src/oasis/index.ts",
    "oasis-proxy": "src/oasis-proxy/index.ts",
    lib: "src/lib/index.ts",
    evalex: "src/evalex/index.ts",
  },
  format: ["esm"],
  target: "es2022",
  // .d.ts 는 tsup 이 만들지 않는다. scripts/lib-dev.mjs 가 tsup 뒤에 `tsc -p tsconfig.build.json` 으로 dist/types/ 에
  // 파일별로 만든다(package.json exports 의 types). tsup 의 dts(rollup-plugin-dts)는 진입점마다 타입을 묶느라
  // RSS 3GB 넘게 쓰고 4GB 힙에서 OOM 이 났다(2026-10-02). TSUP_DTS=0 은 이제 lib-dev 의 tsc 단계를 끈다.
  dts: false,
  sourcemap: true,
  // scripts/lib-dev.mjs 가 dev 중에 tsup 을 한 번씩 돌릴 때는 TSUP_NO_CLEAN=1 — 포털(next dev)이 dist 를 보고 있어 비우면 안 된다.
  clean: !options.watch && process.env.TSUP_NO_CLEAN !== "1",
  splitting: false,
  external: [
    "react",
    "react-dom",
    "next",
    "next/navigation",
    "next/server",
    "next-auth",
    "next-auth/jwt",
    "next-auth/react",
    "next-auth/providers/credentials",
    "ag-grid-react",
    "ag-grid-community",
    "@mantine/core",
    "@mantine/hooks",
    "@mantine/dates",
    "@mantine/notifications",
    "@mantine/modals",
    "dayjs",
    "@tabler/icons-react",
    "clsx",
    "xlsx",
  ],
  loader: {
    ".svg": "dataurl",
  },
}));
