// auto-answer 거부 정규식의 가지별 사례(걸리는 것 pos·안 걸리는 것 neg). 옛 대조 명세 js-parity/specs/auto-answer.mjs 에서 옮겼다.
// ---------- 거부 정규식 가지별 사례(걸리는 것 pos·안 걸리는 것 neg) ----------
export const DENY_CASES = [
  ['rm', ['rm -rf build', 'ls && rm x', 'ls\trm\t-f x', 'RM -rf x', 'cd x; rm'], ['echo perform x', 'cat a-rm b', 'cat a_rm b']],
  ['rmdir·unlink·shred·truncate', ['rmdir x', 'unlink y', 'shred -u z', 'truncate -s 0 f'], ['echo shredder', 'ls rmdirs']],
  ['-delete', ['find . -delete', 'find x -name a -delete'], ['find . -deleted', 'echo -deletex']],
  ['-exec·-execdir', ['find . -exec ls {} ;', 'find . -execdir ls {} +'], ['find . -executable', 'echo -execx']],
  ['xargs', ['ls | xargs echo', 'xargs -n1 ls', 'echo a|xargs\tls'], ['echo xargsx foo', 'echo myxargs a']],
  ['git push 외', ['git push origin x', 'git reset --hard', 'git clean -fd', 'git checkout -- x', 'git restore x', 'git stash drop', 'git stash pop', 'git stash clear', 'git rebase main',
    'git branch -D x', 'git branch -d x', 'git filter-branch x', 'git update-ref -d x', 'GIT PUSH x', 'git   push', 'git restoreall', 'git\tpush'], ['git stash list', 'git checkout main', 'git branch -a', 'git status']],
  ['worktree remove', ['git worktree remove x', 'git worktree   remove y', 'worktree\tremove'], ['git worktree list', 'git worktree add x']],
  ['--force', ['foo --force', 'x --force-with-lease', 'echo --FORCE'], ['foo --forc', 'foo -force', 'echo force']],
  ['DROP·TRUNCATE', ["sqlite3 x 'DROP TABLE a'", 'psql -c "truncate t"', 'echo x;DROP x', 'x drop\ty'], ['echo backdrop x', 'echo dropdown', 'echo DROPS']],
  ['DELETE FROM', ['psql -c "DELETE FROM x"', 'delete   from y', 'DELETE\tFROM z'], ['echo DELETE x', 'echo delete_from']],
  ['UPDATE .. SET', ['psql -c "UPDATE t SET a=1"', 'update x set y', 'UPDATE\tt\tSET\ta'], ['echo UPDATE', 'echo UPDATE only', 'echo update_set']],
  ['kill 류', ['kill 123', 'foo; pkill x', 'killall node', 'launchctl list', 'shutdown now', 'reboot now', 'KILL 9'], ['echo skill x', 'echo killer x', 'echo kills']],
  ['taskkill·Stop-Process', ['taskkill /F /PID 1', 'Stop-Process -Id 1', 'echo x&taskkill'], ['echo taskkills x', 'echo Stop-Processes']],
  ['del·rd·Remove-Item', ['cmd /c del x', 'a & del x', 'x;rd y', 'Remove-Item x', '(del x)', 'echo a|del b', 'ls||RD z'], ['echo del x', 'echo model x', 'ls rd1']],
  ['chmod', ['chmod +x a', 'echo xchmod', 'CHMOD 700 a'], ['echo chmo', 'echo chm od']],
  ['chown', ['chown a b', 'echo xchown'], ['echo chow', 'echo chon']],
  ['sudo', ['sudo ls', 'echo sudoers', 'x SUDO'], ['echo sud', 'echo su do']],
  ['settings.json', ['cat .claude/settings.json', 'ls settings.local.json', 'cat settings.jsonx'], ['cat setting.json', 'cat settings.jso', 'cat settingsXjson']],
  ['.coord.json', ['cat .coord.json', 'cat .coord.local.json', 'cat x.coord.jsonx'], ['cat .coord.js', 'cat .coord.local.jsn', 'cat coordXjson']],
  ['ANTHROPIC|API|AUTH + KEY|TOKEN', ['echo APIKEY', 'echo auth_token', 'echo $ANTHROPIC_API_KEY', 'echo x_AuthKey'], ['echo API_VERSION', 'echo AUTH_URL', 'echo KEY']],
  ['security find-generic-password', ['security find-generic-password -s x', 'security\tfind-generic-password'], ['security list-keychains', 'security find-identity']],
  ['curl -X', ['curl http://x -X POST', 'curl -s x -XPUT', 'curl\t-sX DELETE x', 'curl x -X  PATCH', 'CURL x -x post'], ['curl -s http://x', 'curl x -X GET', 'curl x --request POST']],
  ['bootRun', ['./gradlew bootRun', 'x bootrun', 'gradle BOOTRUN'], ['gradle boot run', 'gradle bootRu']],
  ['local-run.sh', ['bash local-run.sh', 'x local-run.sh y', './LOCAL-RUN.SH'], ['cat local-run.txt', 'cat localXrun.sh', 'cat local_run.sh']],
  ['npm remove 류', ['npm remove x', 'pnpm dlx y', 'yarn exec z', 'npm rm x', 'pnpm uninstall x', 'yarn   remove x', 'NPM\tRM x'], ['npm install', 'npm test', 'pnpm run build', 'npm removed']],
  ['npx -y', ['npx -y foo', 'npx   -y x', 'npx -yes foo', 'NPX -Y a'], ['npx vitest', 'npx vitest run -y', 'npx y']],
  ['쓰기 리다이렉션 >', ['echo a > f', 'cat x>>y', 'echo a >f', 'ls 3> x', "awk '$1 > 3' a", 'echo "a>b"'], ['ls > /dev/null', 'ls 2>&1', 'ls 2>/dev/null', 'echo x >&2', 'ls >>/dev/null', 'ls 2> /dev/null', 'ls &>/dev/null', 'ls 1>/dev/null 2>&1']],
];
