-- mcm-core V3__audit_log.sql — 감사·이력·세션·키 인프라
-- Phase 7 — 갭 #12 (세션) #13 (키) #14 (로그인) #15 (페이지) #16 (트랜잭션) #17 (사용자) #18 (롤)

-- 통합 감사 로그 (롤 변경 / 트랜잭션 / 사용자 변경 모두 한 테이블)
CREATE TABLE IF NOT EXISTS TB_SEC_AUDIT_LOG (
    AUDIT_ID      TEXT PRIMARY KEY,
    ACTION        TEXT NOT NULL,        -- e.g. ROLE_PERM_SAVE, USER_RESET_PW, ROLE_GROUP_ASSIGN_USERS
    TARGET_TYPE   TEXT,                 -- e.g. SecRolePerm, SecUser
    TARGET_ID     TEXT,
    ACTOR_USER_ID TEXT,
    BEFORE_JSON   TEXT,
    AFTER_JSON    TEXT,
    CLIENT_IP     TEXT,
    OCCURRED_AT   TEXT NOT NULL
);

-- 로그인 이력 (#14)
CREATE TABLE IF NOT EXISTS TB_SEC_LOGIN_LOG (
    LOG_ID        TEXT PRIMARY KEY,
    USER_ID       TEXT,
    EVENT_TYPE    TEXT NOT NULL,        -- LOGIN_SUCCESS / LOGIN_FAIL / LOGOUT
    CLIENT_IP     TEXT,
    USER_AGENT    TEXT,
    OCCURRED_AT   TEXT NOT NULL
);

-- JWT 회수 토큰 블랙리스트 (#12)
CREATE TABLE IF NOT EXISTS TB_SEC_REVOKED_TOKEN (
    JTI           TEXT PRIMARY KEY,     -- JWT ID claim
    USER_ID       TEXT,
    REVOKED_AT    TEXT NOT NULL,
    EXPIRES_AT    TEXT                  -- 토큰 본래 만료 시각 (이후엔 GC)
);

-- JWT 키 저장소 (#13)
CREATE TABLE IF NOT EXISTS TB_SEC_KEY_STORE (
    KID           TEXT PRIMARY KEY,     -- key id (kid claim)
    ALG           TEXT,                 -- HS256 / RS256
    PUBLIC_KEY    TEXT,
    PRIVATE_KEY   TEXT,
    SECRET        TEXT,                 -- HMAC secret (HS* 알고리즘용)
    ACTIVE        TEXT DEFAULT 'Y',
    CREATED_AT    TEXT,
    EXPIRES_AT    TEXT
);

CREATE INDEX IF NOT EXISTS IDX_SEC_AUDIT_ACTOR    ON TB_SEC_AUDIT_LOG(ACTOR_USER_ID);
CREATE INDEX IF NOT EXISTS IDX_SEC_AUDIT_TARGET   ON TB_SEC_AUDIT_LOG(TARGET_TYPE, TARGET_ID);
CREATE INDEX IF NOT EXISTS IDX_SEC_AUDIT_TIME     ON TB_SEC_AUDIT_LOG(OCCURRED_AT);
CREATE INDEX IF NOT EXISTS IDX_SEC_LOGIN_USER     ON TB_SEC_LOGIN_LOG(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_SEC_LOGIN_TIME     ON TB_SEC_LOGIN_LOG(OCCURRED_AT);
CREATE INDEX IF NOT EXISTS IDX_SEC_REVOKED_USER   ON TB_SEC_REVOKED_TOKEN(USER_ID);
