-- IFUSER 샘플 인터페이스 표 (초안, 2026-10-07 oracle-1007 ora-platform p1).
-- caravan-hub 는 IF_* 표를 만들지 않는다. 운영자·배포가 정의하고, hub 는 TB_CARAVAN_HUB_CONFIG 의
-- DB_SCHEMA·DB_TABLE_NAME 으로 찾아 `${DB_SCHEMA}.${DB_TABLE_NAME}` 로 읽고 쓴다(InterfaceMapper.xml).
-- 이 파일은 개발·시험용 고정 예시(docs/test 와 hub 단위 시험이 쓰는 IFUSER.IF_MMPPMMCMTT01)이고 운영에는 적용하지 않는다.
-- 컬럼은 InterfaceMapper.xml 이 쓰는 것만 둔다: IF_SEQ(자동 채번), IF_FLAG(N/Y/E), IF_DATE·IF_TIME(처리 일시), KEY_DATA1~3, audit 9컬럼.
-- ⚠ 읽는 쪽(DbInboundHandler)은 `U_AT = #{U_AT}` 를 키로 갱신하므로 U_AT 는 밀리초까지 같은 값이 와야 한다 → TIMESTAMP(6).
CREATE TABLE IF_MMPPMMCMTT01 (
    IF_SEQ           NUMBER(19)           GENERATED BY DEFAULT AS IDENTITY,
    TRANSACTION_CODE VARCHAR2(50 CHAR),
    INTERFACE_ID     VARCHAR2(100 CHAR),
    INTERFACE_MSG    CLOB,
    KEY_DATA1        VARCHAR2(100 CHAR),
    KEY_DATA2        VARCHAR2(100 CHAR),
    KEY_DATA3        VARCHAR2(100 CHAR),
    IF_FLAG          VARCHAR2(1 CHAR)     DEFAULT 'N',
    IF_DATE          VARCHAR2(8 CHAR),
    IF_TIME          VARCHAR2(6 CHAR),
    C_USR_ID         VARCHAR2(100 CHAR),
    C_AT             TIMESTAMP(6),
    C_SVC_ID         VARCHAR2(100 CHAR),
    C_PGM_ID         VARCHAR2(100 CHAR),
    U_USR_ID         VARCHAR2(100 CHAR),
    U_AT             TIMESTAMP(6),
    U_SVC_ID         VARCHAR2(100 CHAR),
    U_PGM_ID         VARCHAR2(100 CHAR),
    VER              NUMBER(19),
    CONSTRAINT PK_IF_MMPPMMCMTT01 PRIMARY KEY (IF_SEQ)
);

-- 폴링이 IF_FLAG 가 N/E/NULL 인 행을 C_AT 순으로 훑는다.
CREATE INDEX IX_IF_MMPPMMCMTT01_FLAG ON IF_MMPPMMCMTT01 (IF_FLAG, C_AT);
