package com.dongkuk.oasis.factories;

import com.dongkuk.oasis.ClassNameResolver;
import com.dongkuk.oasis.NonModifyClassNameResolver;
import com.dongkuk.oasis.process.ProcessStarterFactory;
import com.dongkuk.oasis.provider.ServiceProvider;
import com.dongkuk.oasis.provider.SimpleServiceProvider;
import com.dongkuk.oasis.service.CoreServiceStarter;
import com.dongkuk.oasis.service.ServiceStarter;
import com.dongkuk.oasis.service.ServiceStarterFactory;
import com.dongkuk.oasis.service.StopWatchServiceStarter;
import com.dongkuk.oasis.transaction.NonTransactionHandler;
import com.dongkuk.oasis.transaction.TransactionHandler;

/**
 * 트랜잭션 핸들러와 클래스이름결정기를 입력값으로 {@link ServiceStarter}를 반환한다.
 * <p>
 * 기본값 목록
 * <pre>
 * +----------------------------+-----------+
 * | Item                       | Value     |
 * +----------------------------+-----------+
 * | Service directory          | /services |
 * +----------------------------+-----------+
 * | File Description Delimiter | ^^        |
 * +----------------------------+-----------+
 * | Class Name Resolver        | null      |
 * +----------------------------+-----------+
 * </pre>
 * generated by <a href='https://www.tablesgenerator.com/text_tables'>tables generator</a>
 * <p>
 *
 * @author Jeongjin Kim
 * @since 2021-06-02
 */
final public class DefaultServiceStarterFactory implements ServiceStarterFactory {
    private final ProcessStarterFactory processStarterFactory;
    private final TransactionHandler transactionHandler;
    private String serviceDocumentDirectory = "/services";
    private String fileDescriptionDelimiter = "^^";
    private String fileExtension = "bpmn";

    /**
     * {@link NonTransactionHandler}, {@link NonModifyClassNameResolver}를 사용하는 서비스 실행기를 반환한다.
     */
    public DefaultServiceStarterFactory() {
        this(new NonTransactionHandler(), new NonModifyClassNameResolver());
    }

    /**
     * @param transactionHandler 트랜잭션 핸들러
     */
    public DefaultServiceStarterFactory(TransactionHandler transactionHandler) {
        this(transactionHandler, new NonModifyClassNameResolver());
    }

    /**
     * @param transactionHandler 트랜잭션 핸들러
     * @param classNameResolver  클래스 이름 결정자
     */
    public DefaultServiceStarterFactory(TransactionHandler transactionHandler,
                                        ClassNameResolver classNameResolver) {

        this(transactionHandler, classNameResolver, 10, 50);
    }

    /**
     * @param transactionHandler 트랜잭션 핸들러
     * @param classNameResolver  클래스 이름 결정자
     * @param maxThreads         병렬 수행시 최대 스레드수
     * @param timeoutSeconds     스레드 타임아웃(초)
     */
    public DefaultServiceStarterFactory(TransactionHandler transactionHandler,
                                        ClassNameResolver classNameResolver,
                                        int maxThreads,
                                        int timeoutSeconds) {
        this(transactionHandler,
                new ProcessStaterAndElementExecutorFactory(classNameResolver, maxThreads, timeoutSeconds));
    }

    /**
     * @param transactionHandler    트랜잭션 핸들러
     * @param processStarterFactory 프로세스 스타터 팩토리
     */
    public DefaultServiceStarterFactory(TransactionHandler transactionHandler,
                                        ProcessStarterFactory processStarterFactory) {
        this.transactionHandler = transactionHandler;
        this.processStarterFactory = processStarterFactory;
    }

    /**
     * 서비스 파일의 확장자를 설정한다.
     *
     * @param fileExtension 확장자
     */
    public void setFileExtension(String fileExtension) {
        this.fileExtension = fileExtension;
    }

    /**
     * @param serviceDocumentDirectory 서비스 파일 위치
     */
    public void setServiceDocumentDirectory(String serviceDocumentDirectory) {
        this.serviceDocumentDirectory = serviceDocumentDirectory;
    }

    /**
     * @param fileDescriptionDelimiter 서비스 id와 설명 구분자
     */
    public void setFileDescriptionDelimiter(String fileDescriptionDelimiter) {
        this.fileDescriptionDelimiter = fileDescriptionDelimiter;
    }

    @Override
    public ServiceStarter generateServiceStarter() {
        ServiceProvider serviceProvider =
                new SimpleServiceProvider(
                        serviceDocumentDirectory,
                        fileExtension,
                        fileDescriptionDelimiter);

        return new StopWatchServiceStarter(
                new CoreServiceStarter(
                        serviceProvider,
                        processStarterFactory.generateProcessStarter(),
                        transactionHandler
                )
        );
    }
}
