package com.dongkuk.oasis.factories;

import com.dongkuk.oasis.ClassNameResolver;
import com.dongkuk.oasis.NonModifyClassNameResolver;
import com.dongkuk.oasis.cache.SizeBaseCacheService;
import com.dongkuk.oasis.process.ProcessStarterFactory;
import com.dongkuk.oasis.provider.CachingServiceProvider;
import com.dongkuk.oasis.provider.ServiceProvider;
import com.dongkuk.oasis.provider.SimpleServiceProvider;
import com.dongkuk.oasis.service.CoreServiceStarter;
import com.dongkuk.oasis.service.ServiceStarter;
import com.dongkuk.oasis.service.ServiceStarterFactory;
import com.dongkuk.oasis.service.StopWatchServiceStarter;
import com.dongkuk.oasis.transaction.NonTransactionHandler;

/**
 * 트랜잭션관리를 하지 않는 {@link ServiceStarter}를 반환한다.
 * <ul>
 *     <li>기본값 목록</li>
 * </ul>
 *
 * <pre>
 * +----------------------------+------------------------------------+
 * | Item                       | Value                              |
 * +----------------------------+------------------------------------+
 * | Service directory          | /services                          |
 * +----------------------------+------------------------------------+
 * | File Description Delimiter | ^^                                 |
 * +----------------------------+------------------------------------+
 * | Class Name Resolver        | {@link NonModifyClassNameResolver}         |
 * +----------------------------+------------------------------------+
 * </pre>
 * generated by <a href='https://www.tablesgenerator.com/text_tables'>tables generator</a>
 *
 * @author Jeongjin Kim
 * @since 2021-06-02
 */
final public class NonTransactionalServiceStarterFactory implements ServiceStarterFactory {
    private final ProcessStarterFactory processStarterFactory;
    private String serviceDocumentDirectory = "/services";
    private String fileDescriptionDelimiter = "^^";

    /**
     * 트랜잭션 관리 기능이 없는 서비스 실행기 팩토리 생성.
     */
    public NonTransactionalServiceStarterFactory() {
        this(new NonModifyClassNameResolver());
    }

    /**
     * @param classNameResolver 클래스 이름 결정자
     */
    public NonTransactionalServiceStarterFactory(ClassNameResolver classNameResolver) {
        this(classNameResolver, 10, 50);
    }

    /**
     * @param classNameResolver 클래스 이름 결정자
     * @param maxThreads        병렬 수행시 최대 스레드수
     * @param timeoutSeconds    스레드 타임아웃(초)
     */
    public NonTransactionalServiceStarterFactory(ClassNameResolver classNameResolver,
                                                 int maxThreads,
                                                 int timeoutSeconds) {
        this.processStarterFactory =
                new ProcessStaterAndElementExecutorFactory(classNameResolver, maxThreads, timeoutSeconds);
    }

    /**
     * @param serviceDocumentDirectory 서비스 파일 위치
     */
    public void setServiceDocumentDirectory(String serviceDocumentDirectory) {
        this.serviceDocumentDirectory = serviceDocumentDirectory;
    }

    /**
     * @param fileDescriptionDelimiter 서비스 id와 설명 구분자
     */
    public void setFileDescriptionDelimiter(String fileDescriptionDelimiter) {
        this.fileDescriptionDelimiter = fileDescriptionDelimiter;
    }

    @Override
    public ServiceStarter generateServiceStarter() {
        ServiceProvider serviceProvider =
                new CachingServiceProvider(
                        new SimpleServiceProvider(
                                serviceDocumentDirectory,
                                "bpmn",
                                fileDescriptionDelimiter),
                        new SizeBaseCacheService<>()
                );

        return new StopWatchServiceStarter(
                new CoreServiceStarter(
                        serviceProvider,
                        processStarterFactory.generateProcessStarter(),
                        new NonTransactionHandler()));
    }
}
