package com.dongkuk.oasis.factories;

import com.dongkuk.oasis.ClassNameResolver;
import com.dongkuk.oasis.NonModifyClassNameResolver;
import com.dongkuk.oasis.cache.SizeBaseCacheService;
import com.dongkuk.oasis.context.SpringApplicationContext;
import com.dongkuk.oasis.process.ProcessStarterFactory;
import com.dongkuk.oasis.provider.CachingServiceProvider;
import com.dongkuk.oasis.provider.ServiceProvider;
import com.dongkuk.oasis.provider.SimpleServiceProvider;
import com.dongkuk.oasis.service.*;
import com.dongkuk.oasis.transaction.SpringTransactionHandler;
import org.springframework.context.ApplicationContext;

/**
 * 스프링 컨텍스트와 트랜잭션 매니저 이름 목록을 제외한 모든 필요한 값을 내부에서 결정하여 {@link ServiceStarter}를 반환한다.
 * <p>
 * 기본값 목록
 * <pre>
 * +----------------------------+-----------+
 * | Item                       | Value     |
 * +----------------------------+-----------+
 * | Service directory          | /services |
 * +----------------------------+-----------+
 * | File Description Delimiter | ^^        |
 * +----------------------------+-----------+
 * | Class Name Resolver        | null      |
 * +----------------------------+-----------+
 * </pre>
 * generated by <a href='https://www.tablesgenerator.com/text_tables'>tables generator</a>
 * <p>
 * {@code transactionManagerNames}는 서비스가 수행할 때 시작할 트랜잭션 목록이다. 여기에서 지정하지 않으면 프로세스 정의서에 {@code tx} 속성을
 * 추가하여 명시적으로 시작할 트랜잭션을 지정해야한다.
 *
 * @author Jeongjin Kim
 * @since 2021-06-02
 */
final public class SpringServiceStarterFactory implements ServiceStarterFactory {
    private final ApplicationContext applicationContext;
    private final String[] transactionManagerNames;
    private final ProcessStarterFactory processStarterFactory;
    private String serviceDocumentDirectory = "/services";
    private String fileDescriptionDelimiter = "^^";
    private ServiceProvider serviceProvider;

    /**
     * @param springApplicationContext 스프링 애플리케이션 컨텍스트
     * @param transactionManagerNames  트랜잭션 매니저 이름, null 가능
     */
    public SpringServiceStarterFactory(ApplicationContext springApplicationContext,
                                       String[] transactionManagerNames) {
        this(springApplicationContext, transactionManagerNames, new NonModifyClassNameResolver());
    }

    /**
     * @param springApplicationContext 스프링 애플리케이션 컨텍스트
     * @param transactionManagerNames  트랜잭션 매니저 이름, null 가능
     * @param classNameResolver        클래스 이름 결정자
     */
    public SpringServiceStarterFactory(ApplicationContext springApplicationContext,
                                       String[] transactionManagerNames,
                                       ClassNameResolver classNameResolver) {

        this(springApplicationContext, transactionManagerNames, classNameResolver, 10, 50);
    }

    /**
     * @param springApplicationContext 스프링 애플리케이션 컨텍스트
     * @param transactionManagerNames  트랜잭션 매니저 이름, null 가능
     * @param classNameResolver        클래스 이름 결정자
     * @param maxThreads               병렬 수행시 최대 스레드수
     * @param timeoutSeconds           스레드 타임아웃(초)
     */
    public SpringServiceStarterFactory(ApplicationContext springApplicationContext,
                                       String[] transactionManagerNames,
                                       ClassNameResolver classNameResolver,
                                       int maxThreads,
                                       int timeoutSeconds) {
        if (springApplicationContext == null)
            throw new IllegalArgumentException("org.springframework.context.ApplicationContext is null.");

        this.applicationContext = springApplicationContext;
        this.transactionManagerNames = transactionManagerNames == null ? new String[]{} : transactionManagerNames;
        this.processStarterFactory =
                new ProcessStaterAndElementExecutorFactory(classNameResolver, maxThreads, timeoutSeconds);
    }

    /**
     * @param serviceDocumentDirectory 서비스 파일 위치
     */
    public void setServiceDocumentDirectory(String serviceDocumentDirectory) {
        this.serviceDocumentDirectory = serviceDocumentDirectory;
    }

    /**
     * @param fileDescriptionDelimiter 서비스 id와 설명 구분자
     */
    public void setFileDescriptionDelimiter(String fileDescriptionDelimiter) {
        this.fileDescriptionDelimiter = fileDescriptionDelimiter;
    }

    @Override
    public ServiceStarter generateServiceStarter() {
        ServiceProvider serviceProvider = this.serviceProvider == null ?
                new CachingServiceProvider(
                        new SimpleServiceProvider(
                                serviceDocumentDirectory,
                                "bpmn",
                                fileDescriptionDelimiter),
                        new SizeBaseCacheService<>()
                ) : this.serviceProvider;

        return new StopWatchServiceStarter(
                new SpringServiceStarter(
                        new CoreServiceStarter(
                                serviceProvider,
                                processStarterFactory.generateProcessStarter(),
                                new SpringTransactionHandler(
                                        new SpringApplicationContext(applicationContext), transactionManagerNames)),
                        applicationContext));

    }

    /**
     * @param serviceProvider 서비스 프로바이더
     */
    public void setServiceProvider(ServiceProvider serviceProvider) {
        this.serviceProvider = serviceProvider;
    }
}
