-- 샘플 도메인 초기 스키마 (템플릿 플레이스홀더).
-- 식별자 자동 증가 구문은 방언마다 다르므로(MSSQL: IDENTITY(1,1), PostgreSQL: GENERATED BY DEFAULT AS IDENTITY,
-- SQLite: INTEGER PRIMARY KEY AUTOINCREMENT) 실제 프로젝트에서 사용하는 방언에 맞춰 조정한다.
-- 후속 마이그레이션 채번은 `/flyway-migration-add` 스킬을 사용한다.

CREATE TABLE sample_item
(
    id         BIGINT       NOT NULL PRIMARY KEY,
    code       VARCHAR(50)  NOT NULL,
    name       VARCHAR(200) NOT NULL,
    status     VARCHAR(20)  NOT NULL,
    created_at TIMESTAMP    NOT NULL
);

CREATE UNIQUE INDEX ux_sample_item_code ON sample_item (code);
