-- mpn Oracle 기준선 (초안, 2026-10-07 oracle-1007 ora-platform p3). 소유 사용자 MPNAPUSER, 스키마 접두 없음.
-- due_date 는 엔티티가 LocalDate 이므로 DATE, status 는 enum 문자열(length 20)이다.
CREATE TABLE sample_work_order (
    id          NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no    VARCHAR2(50 CHAR)  NOT NULL,
    item_code   VARCHAR2(50 CHAR)  NOT NULL,
    planned_qty NUMBER(19,4)       NOT NULL,
    due_date    DATE               NOT NULL,
    status      VARCHAR2(20 CHAR)  NOT NULL
);
