-- mpp Oracle 기준선 (초안, 2026-10-07 oracle-1007 ora-platform p3). 소유 사용자 MPPAPUSER, 스키마 접두 없음.
-- recorded_at 은 SQLite TEXT 였고 엔티티는 LocalDateTime 이므로 TIMESTAMP(6) 로 둔다.
CREATE TABLE sample_production_record (
    id            NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_no VARCHAR2(50 CHAR)  NOT NULL,
    produced_qty  NUMBER(19,4)       NOT NULL,
    defect_qty    NUMBER(19,4)       NOT NULL,
    recorded_at   TIMESTAMP(6)       NOT NULL
);
