-- mls Oracle 기준선 (초안, 2026-10-07 oracle-1007 ora-platform p3).
-- 접속 사용자 = 스키마 주인 = MLSAPUSER 이므로 스키마 접두를 붙이지 않는다.
-- SQLite 평평한 폴더 V1~V4 중 V1(sample_inventory_item)만 옮긴다.
-- V2~V4(TB_MLS_NOTICE·TB_MLS_NOTICE_TARGET)는 옮기지 않는다: 공지는 b8c4ccd7a 에서 mcm 으로 옮겨져
-- Notice·NoticeTarget 엔티티가 MCMAPUSER.TB_MCM_NOTICE·TB_MCM_NOTICE_TARGET 을 매핑하고, mls 코드에서
-- TB_MLS_NOTICE 를 쓰는 곳이 없다. 새 Oracle 스키마에는 남겨야 할 Flyway 이력도 없다.
-- 전환 시 V1~V4 SQLite 파일은 archive/ 로 git mv 한다(삭제 금지).
-- 방언 변환 규칙: VARCHAR2(n CHAR), NUMBER(19,4), 자동 증가는 IDENTITY.

CREATE TABLE sample_inventory_item (
    id        NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code VARCHAR2(50 CHAR)  NOT NULL,
    item_name VARCHAR2(200 CHAR) NOT NULL,
    qty       NUMBER(19,4)       NOT NULL,
    location  VARCHAR2(50 CHAR)
);
