-- mls Oracle 기준선 (초안, 2026-10-07 oracle-1007 ora-platform p3).
-- 접속 사용자 = 스키마 주인 = MLSAPUSER 이므로 스키마 접두를 붙이지 않는다.
-- SQLite 평평한 폴더의 V1~V4 를 하나로 합친 결과다. 합친 근거:
--   V1 sample_inventory_item / V2 TB_MLS_NOTICE(+시드 3건) / V3 CONTENT_FORMAT·NOTICE_CATEGORY·PIN_YN(+시드 1건 마크다운화)
--   / V4 TARGET_SCOPE·TB_MLS_NOTICE_TARGET.
-- 방언 변환 규칙: VARCHAR2(n CHAR), TIMESTAMP(6), NUMBER(19,4), 자동 증가는 IDENTITY.
-- CONTENT 는 V3 주석이 예고한 대로 CLOB 이다(엔티티는 LONG32VARCHAR 로 매핑한다).

CREATE TABLE sample_inventory_item (
    id        NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code VARCHAR2(50 CHAR)  NOT NULL,
    item_name VARCHAR2(200 CHAR) NOT NULL,
    qty       NUMBER(19,4)       NOT NULL,
    location  VARCHAR2(50 CHAR)
);

CREATE TABLE TB_MLS_NOTICE (
    NOTICE_ID       VARCHAR2(30 CHAR)  NOT NULL,
    TITLE           VARCHAR2(200 CHAR) NOT NULL,
    CONTENT         CLOB,
    NOTICE_STATUS   VARCHAR2(10 CHAR)  NOT NULL,
    POST_START_DT   DATE,
    POST_END_DT     DATE,
    CONTENT_FORMAT  VARCHAR2(10 CHAR)  DEFAULT 'TEXT'   NOT NULL,
    NOTICE_CATEGORY VARCHAR2(10 CHAR)  DEFAULT 'NORMAL' NOT NULL,
    PIN_YN          CHAR(1 CHAR)       DEFAULT 'N'      NOT NULL,
    TARGET_SCOPE    VARCHAR2(10 CHAR)  DEFAULT 'ALL'    NOT NULL,
    C_USR_ID        VARCHAR2(100 CHAR),
    C_AT            TIMESTAMP(6),
    C_SVC_ID        VARCHAR2(100 CHAR),
    C_PGM_ID        VARCHAR2(100 CHAR),
    U_USR_ID        VARCHAR2(100 CHAR),
    U_AT            TIMESTAMP(6),
    U_SVC_ID        VARCHAR2(100 CHAR),
    U_PGM_ID        VARCHAR2(100 CHAR),
    VER             NUMBER(19),
    CONSTRAINT PK_TB_MLS_NOTICE PRIMARY KEY (NOTICE_ID)
);

CREATE INDEX IX_TB_MLS_NOTICE_STATUS ON TB_MLS_NOTICE (NOTICE_STATUS);

CREATE TABLE TB_MLS_NOTICE_TARGET (
    NOTICE_ID VARCHAR2(30 CHAR)  NOT NULL,
    ROLE_ID   VARCHAR2(100 CHAR) NOT NULL,
    C_USR_ID  VARCHAR2(100 CHAR),
    C_AT      TIMESTAMP(6),
    C_SVC_ID  VARCHAR2(100 CHAR),
    C_PGM_ID  VARCHAR2(100 CHAR),
    U_USR_ID  VARCHAR2(100 CHAR),
    U_AT      TIMESTAMP(6),
    U_SVC_ID  VARCHAR2(100 CHAR),
    U_PGM_ID  VARCHAR2(100 CHAR),
    VER       NUMBER(19),
    CONSTRAINT PK_TB_MLS_NOTICE_TARGET PRIMARY KEY (NOTICE_ID, ROLE_ID)
);

CREATE INDEX IX_TB_MLS_NOTICE_TARGET_ROLE ON TB_MLS_NOTICE_TARGET (ROLE_ID);

-- 초기 확인용 시드 3건. 첫 건은 V3 가 바꾼 결과(마크다운·점검·상단 고정)로 바로 넣는다.
-- 줄바꿈은 CHR(10) 으로 잇는다(SQLite char(10) 대응). NOTICE_ID 3건 모두 세 게시상태를 덮는다.
INSERT INTO TB_MLS_NOTICE
    (NOTICE_ID, TITLE, CONTENT, NOTICE_STATUS, POST_START_DT, POST_END_DT,
     CONTENT_FORMAT, NOTICE_CATEGORY, PIN_YN,
     C_USR_ID, C_SVC_ID, C_PGM_ID, U_USR_ID, U_SVC_ID, U_PGM_ID, VER)
VALUES
    ('NT202609030001', '시스템 정기 점검 안내',
     '## 정기 점검 안내' || CHR(10) || CHR(10)
     || '매월 **첫째 주 토요일 02:00~04:00** 에 정기 점검이 진행됩니다.' || CHR(10) || CHR(10)
     || '- 점검 중에는 포털 접속이 끊길 수 있습니다.' || CHR(10)
     || '- 작업 중인 내용은 점검 시작 전에 저장해 주세요.',
     'POSTED', DATE '2026-09-01', DATE '2026-12-31',
     'MD', 'MAINT', 'Y',
     'admin', 'flyway', 'V1__baseline', 'admin', 'flyway', 'V1__baseline', 0);

INSERT INTO TB_MLS_NOTICE
    (NOTICE_ID, TITLE, CONTENT, NOTICE_STATUS, POST_START_DT, POST_END_DT,
     C_USR_ID, C_SVC_ID, C_PGM_ID, U_USR_ID, U_SVC_ID, U_PGM_ID, VER)
VALUES
    ('NT202609030002', '물류 창고 이전 공지',
     '3공장 자재 창고가 A동에서 B동으로 이전됩니다.',
     'STOPPED', DATE '2026-08-01', DATE '2026-08-31',
     'admin', 'flyway', 'V1__baseline', 'admin', 'flyway', 'V1__baseline', 0);

INSERT INTO TB_MLS_NOTICE
    (NOTICE_ID, TITLE, CONTENT, NOTICE_STATUS, POST_START_DT, POST_END_DT,
     C_USR_ID, C_SVC_ID, C_PGM_ID, U_USR_ID, U_SVC_ID, U_PGM_ID, VER)
VALUES
    ('NT202609030003', '(작성중) 연말 재고실사 일정',
     '일정 확정 후 게시 예정.',
     'DRAFT', NULL, NULL,
     'admin', 'flyway', 'V1__baseline', 'admin', 'flyway', 'V1__baseline', 0);
