-- ============================================================
-- V2: 테이블·칼럼 주석 채우기
-- ============================================================
--
-- 대상 스키마: MCM_SOURCE   위치: oracle/mcm_source
-- 이 파일은 그 스키마 주인으로 접속해 실행된다(앱 Flyway 또는 pdb.mjs template-schema, 운영은 DBA).
--
-- 배경 (사용자 요청, 2026-10-09):
--   DB 뷰어 칼럼명은 MDM 컬럼 사전 이름, 없으면 Oracle 칼럼 주석이다. 주석이 없던 칼럼 60개와 테이블 3개에 주석을 넣는다.
--   이름 근거는 docs/db/column-comments-2026-10-09.md 에 있다. 주석만 바꾸며 데이터·구조는 건드리지 않는다.
-- ============================================================

COMMENT ON TABLE TB_MCM_CODE_CATEGORY IS '코드 카테고리';
COMMENT ON TABLE TB_MCM_CODE_DETAIL IS '코드 상세';
COMMENT ON TABLE TB_MCM_CODE_MASTER IS '코드 마스터';

COMMENT ON COLUMN TB_MCM_CODE_CATEGORY.CATEGORY_ID IS '카테고리 아이디';
COMMENT ON COLUMN TB_MCM_CODE_CATEGORY.CATEGORY_NM IS '카테고리 이름';
COMMENT ON COLUMN TB_MCM_CODE_CATEGORY.C_AT IS '생성일시';
COMMENT ON COLUMN TB_MCM_CODE_CATEGORY.C_PGM_ID IS '생성 프로그램 아이디';
COMMENT ON COLUMN TB_MCM_CODE_CATEGORY.C_SVC_ID IS '생성 서비스 아이디';
COMMENT ON COLUMN TB_MCM_CODE_CATEGORY.C_USR_ID IS '생성자 아이디';
COMMENT ON COLUMN TB_MCM_CODE_CATEGORY.MASTER_CODE IS '마스터 코드';
COMMENT ON COLUMN TB_MCM_CODE_CATEGORY.SORT_SEQ IS '정렬 순번';
COMMENT ON COLUMN TB_MCM_CODE_CATEGORY.U_AT IS '수정일시';
COMMENT ON COLUMN TB_MCM_CODE_CATEGORY.U_PGM_ID IS '수정 프로그램 아이디';
COMMENT ON COLUMN TB_MCM_CODE_CATEGORY.U_SVC_ID IS '수정 서비스 아이디';
COMMENT ON COLUMN TB_MCM_CODE_CATEGORY.U_USR_ID IS '수정자 아이디';
COMMENT ON COLUMN TB_MCM_CODE_CATEGORY.VER IS '버전';

COMMENT ON COLUMN TB_MCM_CODE_DETAIL.CATEGORY_ID IS '카테고리 아이디';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.CODE_VAL_DESC IS '코드 값 설명';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.CODE_VAL_MEAN IS '코드 값 의미';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.CODE_VAL_REF1 IS '코드 값 참조1';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.CODE_VAL_REF2 IS '코드 값 참조2';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.CODE_VAL_REF3 IS '코드 값 참조3';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.CODE_VAL_REF4 IS '코드 값 참조4';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.CODE_VAL_REF5 IS '코드 값 참조5';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.CODE_VAL_REMARK IS '코드 값 비고';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.CODE_VAL IS '코드 값';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.CODE_VER IS '코드 버전';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.C_AT IS '생성일시';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.C_PGM_ID IS '생성 프로그램 아이디';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.C_SVC_ID IS '생성 서비스 아이디';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.C_USR_ID IS '생성자 아이디';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.MASTER_CODE IS '마스터 코드';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.SORT_SEQ IS '정렬 순번';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.U_AT IS '수정일시';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.U_PGM_ID IS '수정 프로그램 아이디';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.U_SVC_ID IS '수정 서비스 아이디';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.U_USR_ID IS '수정자 아이디';
COMMENT ON COLUMN TB_MCM_CODE_DETAIL.VER IS '버전';

COMMENT ON COLUMN TB_MCM_CODE_MASTER.CODE_CHARACTER IS '코드 특성';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.CODE_DESC IS '코드 설명';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.CODE_ID IS '코드 아이디';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.CODE_NM IS '코드 이름';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.CODE_OWNER_DEPT_NM IS '코드 담당 부서명';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.CODE_OWNER_EMP_NO IS '코드 담당 사원번호';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.CODE_VER IS '코드 버전';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.C_AT IS '생성일시';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.C_PGM_ID IS '생성 프로그램 아이디';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.C_SVC_ID IS '생성 서비스 아이디';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.C_USR_ID IS '생성자 아이디';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.END_ACTIVE_DATE IS '유효 종료일';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.MASTER_CODE_REF1 IS '마스터 코드 참조1';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.MASTER_CODE_REF2 IS '마스터 코드 참조2';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.MASTER_CODE_REF3 IS '마스터 코드 참조3';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.MASTER_CODE_REF4 IS '마스터 코드 참조4';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.MASTER_CODE_REF5 IS '마스터 코드 참조5';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.MASTER_CODE IS '마스터 코드';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.START_ACTIVE_DATE IS '유효 시작일';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.USE_TP IS '사용 구분';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.U_AT IS '수정일시';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.U_PGM_ID IS '수정 프로그램 아이디';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.U_SVC_ID IS '수정 서비스 아이디';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.U_USR_ID IS '수정자 아이디';
COMMENT ON COLUMN TB_MCM_CODE_MASTER.VER IS '버전';
