-- TSK-05-03 design.md §6.5·D2 — 레이아웃 스냅샷 버전 이력(SQLite). 저장해 스냅샷이 바뀔 때마다 한 행이다.
-- 상태·승인·소유자는 두지 않는다(03:72). 배포는 보류(PRD §2 규칙 7) — 배포 Task 가 SNAPSHOT_JSON 을 싣는다.
-- 예약어 칼럼을 새로 만들지 않는다(naming-dialect-rules §1 — VERSION 대신 LAYOUT_VERSION). JSON 은 TEXT + json_valid(§3 #3),
-- 애플리케이션이 정규화(키 정렬·공백 없음)해 저장한다(§3 #6). 저장 일시·저장자는 감사 C_AT·C_USR_ID 를 쓴다. CASCADE 없음.
CREATE TABLE TB_MDM_LAYOUT_VER (
    LAYOUT_ID INTEGER NOT NULL,
    LAYOUT_VERSION BIGINT NOT NULL,
    TOTAL_LENGTH INTEGER NOT NULL,
    SWITCH_MODE VARCHAR(20),
    CHANGE_KINDS VARCHAR(200),
    CHANGE_SUMMARY TEXT,
    SNAPSHOT_JSON TEXT NOT NULL CONSTRAINT CK_TB_MDM_LAYOUT_VER_SNAPSHOT_JSON CHECK (json_valid(SNAPSHOT_JSON)),
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_LAYOUT_VER PRIMARY KEY (LAYOUT_ID, LAYOUT_VERSION),
    CONSTRAINT FK_TB_MDM_LAYOUT_VER_LAYOUT FOREIGN KEY (LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID),
    CONSTRAINT CK_TB_MDM_LAYOUT_VER_SWITCH CHECK (SWITCH_MODE IS NULL OR SWITCH_MODE IN ('SEQUENTIAL','SIMULTANEOUS'))
);
