-- 2026-10-02 — 룰 버전 칼럼을 NUMERIC(7,3) 으로 넓히고 버전 종류(VER_KIND)를 추가한다(D-144, 룰 major/minor).
--
-- 왜: 룰 버전을 마스터코드(V9)와 같은 소수 버전(1.000 = major, 1.001 = minor)으로 통일한다.
-- 기존 정수 버전은 모두 MAJOR 의 N.000 이 된다.
--
-- SQLite 는 칼럼 타입과 PK 를 바꿀 수 없어 표를 다시 만든다. 이번에는 V13 의 "새 표 → 복사 → 지움 → 이름 바꿈"
-- 패턴을 쓰지 않는다. ALTER TABLE RENAME 이 자식 FK 의 표 이름을 함께 고치는지는 legacy_alter_table 설정에
-- 달려 있다(앱 드라이버 sqlite-jdbc 기본값에서는 고쳐지고, macOS /usr/bin/sqlite3 CLI 기본값
-- legacy_alter_table=ON·foreign_keys=OFF 에서는 자식 FK 가 TB_MDM_RULE_VER_NEW 로 남아 이후 INSERT·DELETE 가
-- "no such table" 로 깨진다). 실행 환경마다 결과가 달라질 수 있으므로 설정과 무관하게 안전한 순서를 쓴다.
-- 부모·자식 표는 이름 바꿈 없이 다음 순서로 다시 만든다.
-- 순서: ① 옛 부모·자식 데이터를 제약 없는 임시 표(_BAK)에 복사 ② 옛 자식 → 옛 부모 순으로 DROP
--       ③ 최종 이름으로 새 표 생성(부모 → 자식) ④ _BAK 에서 CAST 하여 복사(부모 → 자식) ⑤ _BAK 삭제 ⑥ 인덱스.
-- DROP 시점에 옛 부모를 가리키는 표가 없으므로 CASCADE 삭제·FK 위반이 생기지 않는다.
-- 복사는 컬럼명을 모두 적는다(컬럼 순서에 의존하지 않는다). 칼럼 순서는 V8 그대로이고 VER_KIND 만 VER 바로 뒤에 둔다.
-- VER_KIND 에 DEFAULT 'MAJOR' 를 둔 이유: 칼럼을 모르는 기존 INSERT 경로(샘플 SQL, 시험 보조)가 깨지지 않게 한다.
-- 서비스는 항상 명시한다.
-- 수신 로그(TB_MDM_RULE_RECV)는 자식 FK 가 없어 V13 과 같은 새 표 → 복사 → 지움 → 이름 바꿈으로 처리한다.
-- PRAGMA foreign_keys 를 쓰지 않는 이유는 V13 주석과 같다(Flyway 가 transactional/non-transactional 혼합을 거부).
-- 되돌리려면: 새 마이그레이션에서 같은 패턴으로 VER·BASE_VER 를 INTEGER 로 되돌리고 VER_KIND 를 뺀다
-- (minor 버전 행은 먼저 지워야 한다).

-- ① 임시 복사(제약 없음)
CREATE TABLE TB_MDM_RULE_VER_BAK AS SELECT * FROM TB_MDM_RULE_VER;
CREATE TABLE TB_MDM_RULE_VAR_BAK AS SELECT * FROM TB_MDM_RULE_VAR;
CREATE TABLE TB_MDM_RULE_ROW_BAK AS SELECT * FROM TB_MDM_RULE_ROW;

-- ② 옛 자식 → 옛 부모 순으로 지운다
DROP TABLE TB_MDM_RULE_VAR;
DROP TABLE TB_MDM_RULE_ROW;
DROP TABLE TB_MDM_RULE_VER;

-- ③ 최종 이름으로 새 표 생성
CREATE TABLE TB_MDM_RULE_VER (
    MARU_RULE_ID VARCHAR(50) NOT NULL,
    VER NUMERIC(7,3) NOT NULL,
    VER_KIND VARCHAR(20) NOT NULL DEFAULT 'MAJOR',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    BASE_VER NUMERIC(7,3),
    OWNER_ID VARCHAR(50),
    HIT_POLICY VARCHAR(20),
    APPLY_FROM TEXT,
    APPLY_TO TEXT,
    DESCRIPTION TEXT,
    REQUESTED_BY VARCHAR(50),
    REQUESTED_AT TEXT,
    EMERGENCY_YN VARCHAR(1) NOT NULL DEFAULT 'N',
    EMERGENCY_REASON TEXT,
    APPROVED_BY VARCHAR(50),
    APPROVED_AT TEXT,
    REJECT_REASON TEXT,
    RELEASED_AT TEXT,
    CANCELLED_AT TEXT,
    CANCEL_REASON TEXT,
    ROW_VERSION BIGINT NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    AUD_VER BIGINT,
    CONSTRAINT PK_TB_MDM_RULE_VER PRIMARY KEY (MARU_RULE_ID, VER),
    CONSTRAINT FK_TB_MDM_RULE_VER_RULE FOREIGN KEY (MARU_RULE_ID) REFERENCES TB_MDM_RULE (MARU_RULE_ID),
    CONSTRAINT CK_TB_MDM_RULE_VER_STATUS CHECK (STATUS IN ('DRAFT','REQUESTED','APPROVED','RELEASED','CANCELLED')),
    CONSTRAINT CK_TB_MDM_RULE_VER_KIND CHECK (VER_KIND IN ('MAJOR','MINOR')),
    CONSTRAINT CK_TB_MDM_RULE_VER_HIT CHECK (HIT_POLICY IS NULL OR HIT_POLICY IN ('FIRST','UNIQUE','PRIORITY','COLLECT','ANY')),
    CONSTRAINT CK_TB_MDM_RULE_VER_APPLY CHECK (STATUS = 'DRAFT' OR (APPLY_FROM IS NOT NULL AND APPLY_TO IS NOT NULL)),
    CONSTRAINT CK_TB_MDM_RULE_VER_EMERGENCY_YN CHECK (EMERGENCY_YN IN ('Y','N'))
);

CREATE TABLE TB_MDM_RULE_VAR (
    MARU_RULE_ID VARCHAR(50) NOT NULL,
    VER NUMERIC(7,3) NOT NULL,
    VAR_ID INTEGER NOT NULL,
    VAR_KIND VARCHAR(20) NOT NULL,
    DISP_TYPE VARCHAR(20),
    VAR_NAME TEXT,
    VAR_AST TEXT CONSTRAINT CK_TB_MDM_RULE_VAR_VAR_AST_JSON CHECK (VAR_AST IS NULL OR json_valid(VAR_AST)),
    DOMAIN_ID INTEGER,
    DATA_TYPE VARCHAR(20),
    COLLECT_AGG VARCHAR(20) DEFAULT 'LIST',
    PRIO_LIST TEXT CONSTRAINT CK_TB_MDM_RULE_VAR_PRIO_LIST_JSON CHECK (PRIO_LIST IS NULL OR json_valid(PRIO_LIST)),
    RES_GRP VARCHAR(50),
    GRP_COND TEXT,
    GRP_COND_AST TEXT CONSTRAINT CK_TB_MDM_RULE_VAR_GRP_COND_AST_JSON CHECK (GRP_COND_AST IS NULL OR json_valid(GRP_COND_AST)),
    SEQ INTEGER NOT NULL,
    LABEL TEXT,
    DESCRIPTION TEXT,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    AUD_VER BIGINT,
    CONSTRAINT PK_TB_MDM_RULE_VAR PRIMARY KEY (MARU_RULE_ID, VER, VAR_ID),
    CONSTRAINT FK_TB_MDM_RULE_VAR_VER FOREIGN KEY (MARU_RULE_ID, VER) REFERENCES TB_MDM_RULE_VER (MARU_RULE_ID, VER) ON DELETE CASCADE,
    CONSTRAINT FK_TB_MDM_RULE_VAR_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES TB_MDM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_TB_MDM_RULE_VAR_KIND CHECK (VAR_KIND IN ('COND','RESULT')),
    CONSTRAINT CK_TB_MDM_RULE_VAR_DISP CHECK (DISP_TYPE IS NULL OR DISP_TYPE IN ('Equal','1','2','Expression','Value')),
    CONSTRAINT CK_TB_MDM_RULE_VAR_DTYPE CHECK (DATA_TYPE IS NULL OR DATA_TYPE IN ('BOOLEAN','NUMBER','STRING','DATE')),
    CONSTRAINT CK_TB_MDM_RULE_VAR_AGG CHECK (COLLECT_AGG IS NULL OR COLLECT_AGG IN ('LIST','SUM','MIN','MAX','COUNT')),
    CONSTRAINT CK_TB_MDM_RULE_VAR_RESULT_NAME CHECK (VAR_KIND <> 'RESULT' OR VAR_NAME IS NOT NULL)
);

CREATE TABLE TB_MDM_RULE_ROW (
    MARU_RULE_ID VARCHAR(50) NOT NULL,
    VER NUMERIC(7,3) NOT NULL,
    ROW_ID INTEGER NOT NULL,
    SEQ INTEGER NOT NULL DEFAULT 0,
    ROW_KIND VARCHAR(20) NOT NULL,
    CELLS TEXT NOT NULL CONSTRAINT CK_TB_MDM_RULE_ROW_CELLS_JSON CHECK (json_valid(CELLS)),
    NOTE TEXT,
    TAG VARCHAR(50),
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    AUD_VER BIGINT,
    CONSTRAINT PK_TB_MDM_RULE_ROW PRIMARY KEY (MARU_RULE_ID, VER, ROW_ID),
    CONSTRAINT FK_TB_MDM_RULE_ROW_VER FOREIGN KEY (MARU_RULE_ID, VER) REFERENCES TB_MDM_RULE_VER (MARU_RULE_ID, VER) ON DELETE CASCADE,
    CONSTRAINT CK_TB_MDM_RULE_ROW_KIND CHECK (ROW_KIND IN ('NORMAL','DEFAULT'))
);

-- ④ 복사(VER 는 N.000 MAJOR)
INSERT INTO TB_MDM_RULE_VER (
    MARU_RULE_ID, VER, VER_KIND, STATUS, BASE_VER, OWNER_ID, HIT_POLICY, APPLY_FROM, APPLY_TO, DESCRIPTION, REQUESTED_BY, REQUESTED_AT, EMERGENCY_YN, EMERGENCY_REASON, APPROVED_BY, APPROVED_AT, REJECT_REASON, RELEASED_AT, CANCELLED_AT, CANCEL_REASON, ROW_VERSION, C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, AUD_VER
)
SELECT
    MARU_RULE_ID, CAST(VER AS NUMERIC), 'MAJOR', STATUS, CAST(BASE_VER AS NUMERIC), OWNER_ID, HIT_POLICY, APPLY_FROM, APPLY_TO, DESCRIPTION, REQUESTED_BY, REQUESTED_AT, EMERGENCY_YN, EMERGENCY_REASON, APPROVED_BY, APPROVED_AT, REJECT_REASON, RELEASED_AT, CANCELLED_AT, CANCEL_REASON, ROW_VERSION, C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, AUD_VER
FROM TB_MDM_RULE_VER_BAK;

INSERT INTO TB_MDM_RULE_VAR (
    MARU_RULE_ID, VER, VAR_ID, VAR_KIND, DISP_TYPE, VAR_NAME, VAR_AST, DOMAIN_ID, DATA_TYPE, COLLECT_AGG, PRIO_LIST, RES_GRP, GRP_COND, GRP_COND_AST, SEQ, LABEL, DESCRIPTION, C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, AUD_VER
)
SELECT
    MARU_RULE_ID, CAST(VER AS NUMERIC), VAR_ID, VAR_KIND, DISP_TYPE, VAR_NAME, VAR_AST, DOMAIN_ID, DATA_TYPE, COLLECT_AGG, PRIO_LIST, RES_GRP, GRP_COND, GRP_COND_AST, SEQ, LABEL, DESCRIPTION, C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, AUD_VER
FROM TB_MDM_RULE_VAR_BAK;

INSERT INTO TB_MDM_RULE_ROW (
    MARU_RULE_ID, VER, ROW_ID, SEQ, ROW_KIND, CELLS, NOTE, TAG, C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, AUD_VER
)
SELECT
    MARU_RULE_ID, CAST(VER AS NUMERIC), ROW_ID, SEQ, ROW_KIND, CELLS, NOTE, TAG, C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, AUD_VER
FROM TB_MDM_RULE_ROW_BAK;

-- ⑤ 임시 표 삭제
DROP TABLE TB_MDM_RULE_VER_BAK;
DROP TABLE TB_MDM_RULE_VAR_BAK;
DROP TABLE TB_MDM_RULE_ROW_BAK;

-- ⑥ 인덱스 재생성
CREATE UNIQUE INDEX UX_TB_MDM_RULE_VAR_SEQ ON TB_MDM_RULE_VAR (MARU_RULE_ID, VER, VAR_KIND, SEQ);
CREATE UNIQUE INDEX UX_TB_MDM_RULE_VAR_NAME ON TB_MDM_RULE_VAR (MARU_RULE_ID, VER, VAR_NAME) WHERE VAR_KIND = 'RESULT';
CREATE UNIQUE INDEX UX_TB_MDM_RULE_ROW_SEQ ON TB_MDM_RULE_ROW (MARU_RULE_ID, VER, SEQ) WHERE ROW_KIND = 'NORMAL';

-- 수신 로그
CREATE TABLE TB_MDM_RULE_RECV_NEW (
    RECV_ID INTEGER CONSTRAINT PK_TB_MDM_RULE_RECV PRIMARY KEY AUTOINCREMENT,
    MARU_RULE_ID VARCHAR(50),
    SOURCE_SYSTEM VARCHAR(20) NOT NULL,
    SOURCE_REF VARCHAR(50),
    REQ_KIND VARCHAR(20) NOT NULL,
    RECEIVED_AT TEXT NOT NULL,
    BODY TEXT NOT NULL,
    "RESULT" VARCHAR(20),
    RESULT_DETAIL TEXT,
    VER NUMERIC(7,3),
    PROCESSED_AT TEXT,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    AUD_VER BIGINT,
    CONSTRAINT FK_TB_MDM_RULE_RECV_RULE FOREIGN KEY (MARU_RULE_ID) REFERENCES TB_MDM_RULE (MARU_RULE_ID),
    CONSTRAINT FK_TB_MDM_RULE_RECV_SYSTEM FOREIGN KEY (SOURCE_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_RULE_RECV_REQ CHECK (REQ_KIND IN ('VERSION','CANCEL','DEPRECATE')),
    CONSTRAINT CK_TB_MDM_RULE_RECV_RESULT CHECK ("RESULT" IS NULL OR "RESULT" IN ('OK','REJECTED','FAILED'))
);

INSERT INTO TB_MDM_RULE_RECV_NEW (
    RECV_ID, MARU_RULE_ID, SOURCE_SYSTEM, SOURCE_REF, REQ_KIND, RECEIVED_AT, BODY, "RESULT", RESULT_DETAIL, VER, PROCESSED_AT, C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, AUD_VER
)
SELECT
    RECV_ID, MARU_RULE_ID, SOURCE_SYSTEM, SOURCE_REF, REQ_KIND, RECEIVED_AT, BODY, "RESULT", RESULT_DETAIL, CAST(VER AS NUMERIC), PROCESSED_AT, C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, AUD_VER
FROM TB_MDM_RULE_RECV;

DROP TABLE TB_MDM_RULE_RECV;
ALTER TABLE TB_MDM_RULE_RECV_NEW RENAME TO TB_MDM_RULE_RECV;
