-- 2026-10-02 — 룰 세트를 버전 단위로 바꾼다(D-144 2단계, ADR-0006). 흐름(FLOW_JSON·RULE_IDS)과 ROW_VERSION 을 버전 표로 옮긴다.
--
-- 왜: 룰 세트도 룰처럼 DRAFT 에 저장하고 확정해야 운영에 반영한다(스펙 §6). 부모 TB_MDM_RULE_SET 은 ID·이름·설명·상태만 남기고
-- 상태에 CREATED 를 더한다(첫 확정 때 공통 엔진이 INUSE 로 올린다, markParentInUse).
-- 이행: 기존 세트마다 1.000 MAJOR RELEASED 한 행. APPLY_FROM = 일괄 2000-01-01 00:00:00, APPLY_TO = 9999-12-31 00:00:00,
--   RELEASED_AT·REQUESTED_AT = U_AT(없으면 C_AT, 그것도 없으면 2000-01-01 00:00:00), REQUESTED_BY = U_USR_ID,
--   OWNER_ID 는 비운다(확정한 사람이 없다). 폐기 세트는 부모 DEPRECATED 를 유지한다.
-- APPLY_FROM 을 C_AT 로 두지 않는 이유(Ruling P2-11): 엔진은 판정 시각으로 세트 버전을 고른다. C_AT 로 두면 그보다 이른 판정 시각
--   (과거 데이터 재판정, 세트 테스트 케이스의 EVAL_TS 등)에서 SET_NOT_FOUND 가 난다. 이행 버전은 언제 판정해도 찾혀야 하므로
--   충분히 이른 고정 시각으로 연다(스펙 §6 이행 한계 "이행 이전 시각에는 이행 시점의 흐름이 쓰인다" 와 같은 뜻).
-- 일시 정규화(RELEASED_AT·REQUESTED_AT): 감사 칼럼 C_AT·U_AT 는 쓴 경로에 따라 모양이 다르다. 네이티브 쓰기(MdmTemporalBinder)는
--   'yyyy-MM-dd HH:mm:ss'(KST) 문자열이지만 엔티티(Hibernate) 경로는 C_AT·U_AT 가 Instant 라 정수면 UTC epoch 밀리초다(sqlite-jdbc 기본값,
--   2026-10-02 로컬 DB 실측: 세트 10건 중 C_AT 정수 5건). 정수를 그대로 substr 하면 '1790746498041' 같은 값이 되어 읽기(fromDb)가
--   깨진다. 그래서 정수·실수는 KST 벽시계(datetime(x/1000,'unixepoch','+9 hours'), 서버 시각대와 무관하게 고정), 문자열은
--   'T' 를 공백으로 바꾼 앞 19자로 맞춘다. 버전 행의 업무 일시만 정규화하고, 감사 칼럼(C_AT·U_AT)은 부모·버전 모두 원본 그대로 옮긴다.
-- 한계: 지금까지 세트는 덮어쓰기 저장이라 이전 흐름이 남아 있지 않다. 과거 판정 재현(스펙 목적 3)은 이행 시점 이후부터 보장된다.
--   이행 이전 시각(C_AT 보다 이른 시각 포함)에는 이행 시점의 흐름이 쓰인다.
--
-- 순서(V17 교훈): ALTER TABLE ... RENAME 의 자식 FK 갱신은 legacy_alter_table 설정에 따라 달라진다. 이름 바꿈 없이
--   ① 옛 부모·자식(TB_MDM_RULE_SET_TEST_CASE — V15 가 만든 이 세트의 첫 FK)을 제약 없는 _BAK 으로 복사 ② 옛 자식 → 옛 부모 DROP
--   ③ 최종 이름으로 새 표 생성(부모 → 버전 → 케이스) ④ _BAK 에서 칼럼명을 모두 적어 복사 ⑤ _BAK DROP.
-- DROP 시점에 옛 부모를 가리키는 표가 없으므로 FK 위반·CASCADE 삭제가 생기지 않는다(두 자식 FK 모두 ON DELETE CASCADE 없음).
-- PRAGMA 를 쓰지 않는다(Flyway 가 transactional/non-transactional 혼합을 거부, V13 주석).
-- 되돌리려면: 새 마이그레이션에서 같은 순서로 부모에 RULE_IDS·FLOW_JSON·ROW_VERSION 을 되살리고 세트마다 지금 적용 중인 RELEASED
--   (없으면 VER 최대) 행의 값을 넣은 뒤 TB_MDM_RULE_SET_VER 를 지운다. 다른 버전의 흐름은 사라진다.

-- ① 임시 복사(제약 없음)
CREATE TABLE TB_MDM_RULE_SET_BAK AS SELECT * FROM TB_MDM_RULE_SET;
CREATE TABLE TB_MDM_RULE_SET_TEST_CASE_BAK AS SELECT * FROM TB_MDM_RULE_SET_TEST_CASE;

-- ② 옛 자식 → 옛 부모
DROP TABLE TB_MDM_RULE_SET_TEST_CASE;
DROP TABLE TB_MDM_RULE_SET;

-- ③ 새 표(부모 → 버전 → 케이스)
CREATE TABLE TB_MDM_RULE_SET (
    MARU_RULE_SET_ID VARCHAR(50) NOT NULL,
    MARU_RULE_SET_NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_RULE_SET PRIMARY KEY (MARU_RULE_SET_ID),
    CONSTRAINT CK_TB_MDM_RULE_SET_STATUS CHECK (STATUS IN ('CREATED','INUSE','DEPRECATED'))
);

CREATE TABLE TB_MDM_RULE_SET_VER (
    MARU_RULE_SET_ID VARCHAR(50) NOT NULL,
    VER NUMERIC(7,3) NOT NULL,
    VER_KIND VARCHAR(20) NOT NULL DEFAULT 'MAJOR',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    BASE_VER NUMERIC(7,3),
    OWNER_ID VARCHAR(50),
    APPLY_FROM TEXT,
    APPLY_TO TEXT,
    RULE_IDS TEXT NOT NULL CONSTRAINT CK_TB_MDM_RULE_SET_VER_RULE_IDS_JSON CHECK (json_valid(RULE_IDS)),
    FLOW_JSON TEXT CONSTRAINT CK_TB_MDM_RULE_SET_VER_FLOW_JSON CHECK (FLOW_JSON IS NULL OR json_valid(FLOW_JSON)),
    REQUESTED_BY VARCHAR(50),
    REQUESTED_AT TEXT,
    RELEASED_AT TEXT,
    ROW_VERSION BIGINT NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    AUD_VER BIGINT,
    CONSTRAINT PK_TB_MDM_RULE_SET_VER PRIMARY KEY (MARU_RULE_SET_ID, VER),
    CONSTRAINT FK_TB_MDM_RULE_SET_VER_SET FOREIGN KEY (MARU_RULE_SET_ID) REFERENCES TB_MDM_RULE_SET (MARU_RULE_SET_ID),
    CONSTRAINT CK_TB_MDM_RULE_SET_VER_STATUS CHECK (STATUS IN ('DRAFT','REQUESTED','APPROVED','RELEASED','CANCELLED')),
    CONSTRAINT CK_TB_MDM_RULE_SET_VER_KIND CHECK (VER_KIND IN ('MAJOR','MINOR')),
    CONSTRAINT CK_TB_MDM_RULE_SET_VER_APPLY CHECK (STATUS = 'DRAFT' OR (APPLY_FROM IS NOT NULL AND APPLY_TO IS NOT NULL))
);

CREATE TABLE TB_MDM_RULE_SET_TEST_CASE (
    MARU_RULE_SET_ID VARCHAR(50) NOT NULL,
    CASE_ID INTEGER NOT NULL,
    CASE_NAME TEXT,
    INPUT_JSON TEXT NOT NULL CONSTRAINT CK_TB_MDM_RULE_SET_TEST_CASE_INPUT_JSON CHECK (json_valid(INPUT_JSON)),
    EVAL_TS VARCHAR(19),
    EXPECTED_JSON TEXT CONSTRAINT CK_TB_MDM_RULE_SET_TEST_CASE_EXPECTED_JSON CHECK (EXPECTED_JSON IS NULL OR json_valid(EXPECTED_JSON)),
    DESCRIPTION TEXT,
    ROW_VERSION BIGINT NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_RULE_SET_TEST_CASE PRIMARY KEY (MARU_RULE_SET_ID, CASE_ID),
    CONSTRAINT FK_TB_MDM_RULE_SET_TEST_CASE_SET FOREIGN KEY (MARU_RULE_SET_ID) REFERENCES TB_MDM_RULE_SET (MARU_RULE_SET_ID)
);

-- ④ 복사(부모 → 버전 → 케이스)
INSERT INTO TB_MDM_RULE_SET (
    MARU_RULE_SET_ID, MARU_RULE_SET_NAME, DESCRIPTION, STATUS,
    C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, VER
)
SELECT
    MARU_RULE_SET_ID, MARU_RULE_SET_NAME, DESCRIPTION, STATUS,
    C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, VER
FROM TB_MDM_RULE_SET_BAK;

INSERT INTO TB_MDM_RULE_SET_VER (
    MARU_RULE_SET_ID, VER, VER_KIND, STATUS, BASE_VER, OWNER_ID, APPLY_FROM, APPLY_TO, RULE_IDS, FLOW_JSON,
    REQUESTED_BY, REQUESTED_AT, RELEASED_AT, ROW_VERSION,
    C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, AUD_VER
)
SELECT
    MARU_RULE_SET_ID, CAST(1 AS NUMERIC), 'MAJOR', 'RELEASED', NULL, NULL,
    '2000-01-01 00:00:00',
    '9999-12-31 00:00:00',
    RULE_IDS, FLOW_JSON,
    U_USR_ID,
    COALESCE(U_AT_TEXT, C_AT_TEXT, '2000-01-01 00:00:00'),
    COALESCE(U_AT_TEXT, C_AT_TEXT, '2000-01-01 00:00:00'),
    ROW_VERSION,
    C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, 0
FROM (
    SELECT
        b.*,
        CASE WHEN typeof(b.C_AT) IN ('integer', 'real') THEN datetime(b.C_AT / 1000, 'unixepoch', '+9 hours')
             ELSE substr(replace(b.C_AT, 'T', ' '), 1, 19) END AS C_AT_TEXT,
        CASE WHEN typeof(b.U_AT) IN ('integer', 'real') THEN datetime(b.U_AT / 1000, 'unixepoch', '+9 hours')
             ELSE substr(replace(b.U_AT, 'T', ' '), 1, 19) END AS U_AT_TEXT
    FROM TB_MDM_RULE_SET_BAK b
);

INSERT INTO TB_MDM_RULE_SET_TEST_CASE (
    MARU_RULE_SET_ID, CASE_ID, CASE_NAME, INPUT_JSON, EVAL_TS, EXPECTED_JSON, DESCRIPTION, ROW_VERSION,
    C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, VER
)
SELECT
    MARU_RULE_SET_ID, CASE_ID, CASE_NAME, INPUT_JSON, EVAL_TS, EXPECTED_JSON, DESCRIPTION, ROW_VERSION,
    C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, VER
FROM TB_MDM_RULE_SET_TEST_CASE_BAK;

-- ⑤ 임시 표 삭제
DROP TABLE TB_MDM_RULE_SET_TEST_CASE_BAK;
DROP TABLE TB_MDM_RULE_SET_BAK;
