-- 2026-10-02 — 인터페이스 레이아웃을 버전 단위로 바꾼다(D-144 3단계, 스펙 §7, ADR-0006). 레이아웃 5표를 다시 만들고 저장 이력을 옮긴다.
-- 번호: 당초 V19 로 만들었으나 메타 캐시 V20(TB_MDM_META_REV)이 dev 에 먼저 들어가 V21 로 옮겼다 — mdm Flyway 는 outOfOrder=false 라
--   V20 이 적용된 DB 에 뒤늦은 V19 가 오면 기동 검증이 실패한다. 3단계 브랜치에서 V19 로 만든 로컬·E2E mdm.db 는 이름 변경 뒤
--   Flyway 검증(적용 이력의 V19 를 찾을 수 없음)에서 실패하므로, 그런 DB 는 지우고 다시 기동해 V21 로 새로 만든다.
--
-- 왜: 레이아웃(헤더·전문)도 룰·룰 세트처럼 DRAFT 에 저장하고 확정해야 운영에 반영한다. 항목·헤더 구성·상수 재정의가 버전 키
--   (LAYOUT_ID, VER) 아래로 들어가고, 부모 TB_MDM_LAYOUT 은 ID·종류·이름·송수신 시스템·상태만 남긴다. 형식 속성(EAI_CODE)과
--   자기 길이(OWN_LENGTH)는 버전 행으로 옮긴다 — EAI_CODE 가 부모를 떠나면서 부모 ↔ EAI 순환 FK 가 없어진다.
--   TOTAL_LENGTH 는 저장하지 않는다(전문 총 길이 = 판정 시각 T 의 헤더 OWN_LENGTH 합 + 본문 OWN_LENGTH). 업무 `VERSION` 도 없앤다.
-- 감사 카운터 개명(D-034): 버전 표 4개(VER·ITEM·HEADER·CONST)의 감사 카운터 VER 를 AUD_VER 로 바꾼다. 업무 버전 VER NUMERIC(7,3) 가
--   키 칼럼이 되므로 같은 이름을 둘 수 없다. 부모 TB_MDM_LAYOUT·TB_MDM_EAI 의 감사 VER 는 그대로다.
-- 저장 오프셋: 헤더 항목은 헤더 안 상대값(그대로), 전문 본문 항목은 본문 시작 기준 상대값으로 바꾼다(옛 값 - 쌓인 헤더 TOTAL_LENGTH 합).
-- 상수 재정의: 대상이 (헤더, HEADER_SEQ) 에서 헤더 항목 물리명(HEADER_COLUMN_PHYS)으로 바뀐다 — 헤더 버전이 바뀌어 SEQ 가 움직여도
--   짝이 유지된다. 물리명이 없는 대상(L03 로 생길 수 없다)은 옮기지 않는다.
--
-- 이행 규칙:
--   · 저장 이력(옛 TB_MDM_LAYOUT_VER)이 있는 레이아웃 — 이력 행마다 MAJOR RELEASED 한 행(VER = 옛 LAYOUT_VERSION). 구간은
--     [그 이력 행 C_AT, 다음 이력 행 C_AT). 최신 이력 행만 항목 행을 가지고(LEGACY_SNAPSHOT_YN 'N', SNAPSHOT_JSON NULL),
--     이전 행은 항목 행 없이 옛 스냅샷만 둔다(LEGACY_SNAPSHOT_YN 'Y' — 헤더를 값으로 담은 MdmLayoutSnapshot JSON).
--     이전 행의 OWN_LENGTH = 스냅샷 총 길이 - 스냅샷 헤더 길이 합, EAI_CODE = 스냅샷 eaiCode(지금 EAI 표에 있을 때만, 없으면 NULL).
--   · 저장 이력이 없는 레이아웃(헤더 전부 + 이력 없는 전문) — 현재 행이 1.000 MAJOR RELEASED, 구간 끝 9999-12-31 00:00:00.
--     헤더 버전 행의 EAI_CODE = 그 헤더를 표준 헤더로 가리키던 EAI(여럿이면 코드 순 첫째) — EAI 표준 헤더를 시각 T 에 해석하는 근거다(확정은 TB_MDM_EAI.HEADER_LAYOUT_ID 를 옮기지 않는다).
--   · 부모 STATUS 는 모두 INUSE(이미 적용된 RELEASED 가 있다).
--   · 첫 버전의 APPLY_FROM 은 이행 하한 '2000-01-01 00:00:00' 이다(Ruling P2-11, V18 과 같은 판단). 엔진은 판정 시각으로 버전을
--     고르므로 C_AT 로 열면 그보다 이른 판정 시각(과거 데이터 재생성·시험 시각)에서 적용 버전이 없다는 오류가 난다. 이행한 첫 버전은
--     언제 판정해도 찾혀야 한다. 브리프 원안(첫 이력 행 C_AT·헤더 C_AT 부터)과 다르다. 실제 저장 시각은 RELEASED_AT·REQUESTED_AT 에 남는다.
--   · 같은 초에 저장된 이력 두 행은 길이 0 구간이 되어 판정에 쓰이지 않는다. 이력 C_AT 이 버전 순서와 거꾸로면(형식이 섞인 DB)
--     구간 시작을 앞 버전들의 시작 중 최댓값으로 올려 구간이 겹치지 않게 한다(그 버전은 길이 0 구간).
-- 일시 정규화(APPLY_FROM·APPLY_TO·REQUESTED_AT·RELEASED_AT): 감사 C_AT 은 쓴 경로에 따라 모양이 다르다. 네이티브 쓰기·샘플은
--   'yyyy-MM-dd HH:mm:ss'(KST) 문자열이고, 엔티티(Hibernate) 경로는 Instant 라 UTC epoch 밀리초 정수다(2026-10-02 로컬 DB 실측:
--   레이아웃 5건 중 C_AT 정수 2건, 이력 4건 중 1건). 정수·실수는 datetime(x/1000,'unixepoch','+9 hours')(KST 벽시계, 서버 시각대와
--   무관), 문자열은 'T' 를 공백으로 바꾼 앞 19자, 없으면 이행 하한 '2000-01-01 00:00:00'. 감사 칼럼(C_AT·U_AT)은 원본 그대로 옮긴다.
-- 이행 한계(스펙 §7): 이전 전문 버전은 헤더를 값으로 담은 스냅샷만 있다(항목 행 없음). 헤더 버전에 따른 전문 합성(시각 T 의 헤더
--   버전 해석)은 이행 이후 버전부터 보장된다. 헤더는 저장 이력이 없었으므로 이행 시점 내용이 1.000 하나로 남는다.
--
-- 순서(V17 교훈): ALTER TABLE ... RENAME 의 다른 표 FK 갱신은 legacy_alter_table 설정에 따라 달라지므로 RENAME 을 쓰지 않는다.
--   ① 5표 + 옛 이력 표를 제약 없는 _BAK 으로 복사, AUTOINCREMENT 상한(sqlite_sequence) 보관
--   ② 이행 기준표(레이아웃별 최신 버전·길이, 이력 구간) 계산
--   ③ 옛 자식 → 옛 부모 순 DROP. 레이아웃 ↔ EAI 순환 FK 는 `UPDATE TB_MDM_LAYOUT SET EAI_CODE = NULL` 로 레이아웃 쪽을 끊은 뒤
--      EAI → 레이아웃 순으로 지운다(값은 _BAK 에 있다). DROP 시점에 옛 표를 가리키는 행이 없으므로 FK 위반·CASCADE 삭제가 없다.
--   ④ 최종 이름으로 새 표 생성(부모 → EAI → 버전 → 항목·헤더 구성 → 상수) ⑤ 칼럼명을 모두 적어 복사 ⑥ 임시 표 DROP.
-- AUTOINCREMENT: TB_MDM_LAYOUT 을 DROP 하면 sqlite_sequence 의 그 행이 사라져 이행 INSERT 의 최대 ID 로 다시 잡힌다. 그러면 지운 끝
--   번호(로컬 DB: 상한 360, 최대 ID 305)가 재사용되므로 V16 과 같이 옛 상한을 되살린다(브리프 원안은 재사용을 허용했다).
-- PRAGMA 를 쓰지 않는다(Flyway 가 transactional/non-transactional 혼합을 거부, V13 주석). CASCADE 없음(V4 불변 규칙 11).
-- 되돌리려면: 새 마이그레이션에서 같은 _BAK 패턴으로 V4·V12 모양 표를 다시 만들고, 레이아웃마다 지금 적용 중인 RELEASED(없으면 최신)
--   버전의 항목·헤더 구성·상수만 옮긴다(EAI_CODE·TOTAL_LENGTH 는 버전 행에서 계산해 부모로, 본문 오프셋은 헤더 길이를 더해 절대값으로,
--   상수는 물리명 → 그 헤더의 SEQ). 다른 버전의 항목은 사라지고 이력은 SNAPSHOT_JSON 이 있는 행만 남는다.

-- ① 임시 복사(제약 없음)
CREATE TABLE TB_MDM_LAYOUT_BAK AS SELECT * FROM TB_MDM_LAYOUT;
CREATE TABLE TB_MDM_EAI_BAK AS SELECT * FROM TB_MDM_EAI;
CREATE TABLE TB_MDM_LAYOUT_VER_BAK AS SELECT * FROM TB_MDM_LAYOUT_VER;
CREATE TABLE TB_MDM_LAYOUT_ITEM_BAK AS SELECT * FROM TB_MDM_LAYOUT_ITEM;
CREATE TABLE TB_MDM_LAYOUT_HEADER_BAK AS SELECT * FROM TB_MDM_LAYOUT_HEADER;
CREATE TABLE TB_MDM_LAYOUT_CONST_BAK AS SELECT * FROM TB_MDM_LAYOUT_CONST;
CREATE TABLE TB_MDM_LAYOUT_V21_SEQ AS
SELECT seq FROM sqlite_sequence WHERE name = 'TB_MDM_LAYOUT';

-- ② 이행 기준표
-- 레이아웃마다 최신 버전 번호(이력 최대, 없으면 1)·생성 시각(KST)·자기 항목 길이·쌓인 헤더 길이·헤더를 가리키는 EAI
CREATE TABLE TB_MDM_LAYOUT_V21_KEY AS
SELECT l.LAYOUT_ID AS LAYOUT_ID,
       COALESCE((SELECT MAX(v.LAYOUT_VERSION) FROM TB_MDM_LAYOUT_VER_BAK v WHERE v.LAYOUT_ID = l.LAYOUT_ID), 1) AS LATEST,
       CASE WHEN typeof(l.C_AT) IN ('integer', 'real') THEN datetime(CAST(l.C_AT AS INTEGER) / 1000, 'unixepoch', '+9 hours')
            WHEN typeof(l.C_AT) = 'text' THEN substr(replace(l.C_AT, 'T', ' '), 1, 19)
            ELSE '2000-01-01 00:00:00' END AS CREATED_KST,
       COALESCE((SELECT SUM(i.`LENGTH`) FROM TB_MDM_LAYOUT_ITEM_BAK i WHERE i.LAYOUT_ID = l.LAYOUT_ID), 0) AS OWN_LENGTH,
       COALESCE((SELECT SUM(h.TOTAL_LENGTH) FROM TB_MDM_LAYOUT_HEADER_BAK s JOIN TB_MDM_LAYOUT_BAK h ON h.LAYOUT_ID = s.HEADER_LAYOUT_ID
                 WHERE s.LAYOUT_ID = l.LAYOUT_ID), 0) AS HEADER_LENGTH,
       CASE WHEN l.LAYOUT_KIND = 'MESSAGE' THEN (SELECT e.EAI_CODE FROM TB_MDM_EAI_BAK e WHERE e.EAI_CODE = l.EAI_CODE)
            ELSE (SELECT e.EAI_CODE FROM TB_MDM_EAI_BAK e WHERE e.HEADER_LAYOUT_ID = l.LAYOUT_ID ORDER BY e.EAI_CODE LIMIT 1) END AS EAI_CODE
FROM TB_MDM_LAYOUT_BAK l;

-- 이력 행마다 저장 시각(KST)
CREATE TABLE TB_MDM_LAYOUT_V21_HIST AS
SELECT v.LAYOUT_ID AS LAYOUT_ID, v.LAYOUT_VERSION AS LAYOUT_VERSION,
       CASE WHEN typeof(v.C_AT) IN ('integer', 'real') THEN datetime(CAST(v.C_AT AS INTEGER) / 1000, 'unixepoch', '+9 hours')
            WHEN typeof(v.C_AT) = 'text' THEN substr(replace(v.C_AT, 'T', ' '), 1, 19)
            ELSE '2000-01-01 00:00:00' END AS SAVED_KST
FROM TB_MDM_LAYOUT_VER_BAK v;

-- 이력 행마다 구간 시작 — 첫 버전은 이행 하한(Ruling P2-11), 나머지는 자기까지의 저장 시각 최댓값(구간이 겹치지 않게)
CREATE TABLE TB_MDM_LAYOUT_V21_SPAN AS
SELECT h.LAYOUT_ID AS LAYOUT_ID, h.LAYOUT_VERSION AS LAYOUT_VERSION, h.SAVED_KST AS SAVED_KST,
       CASE WHEN h.LAYOUT_VERSION = (SELECT MIN(f.LAYOUT_VERSION) FROM TB_MDM_LAYOUT_V21_HIST f WHERE f.LAYOUT_ID = h.LAYOUT_ID)
            THEN '2000-01-01 00:00:00'
            ELSE (SELECT MAX(p.SAVED_KST) FROM TB_MDM_LAYOUT_V21_HIST p
                   WHERE p.LAYOUT_ID = h.LAYOUT_ID AND p.LAYOUT_VERSION <= h.LAYOUT_VERSION) END AS APPLY_FROM
FROM TB_MDM_LAYOUT_V21_HIST h;

-- ③ 옛 자식 → 옛 부모 순으로 지운다. 레이아웃 ↔ EAI 순환 FK 는 레이아웃 쪽 칸을 비워 끊는다(값은 _BAK 에 있다)
DROP TABLE TB_MDM_LAYOUT_CONST;
DROP TABLE TB_MDM_LAYOUT_HEADER;
DROP TABLE TB_MDM_LAYOUT_ITEM;
DROP TABLE TB_MDM_LAYOUT_VER;
UPDATE TB_MDM_LAYOUT SET EAI_CODE = NULL;
DROP TABLE TB_MDM_EAI;
DROP TABLE TB_MDM_LAYOUT;

-- ④ 새 표(부모 → 자식). EAI_CODE 는 버전 행으로 옮겨 부모와 EAI 의 순환이 없어진다
CREATE TABLE TB_MDM_LAYOUT (
    LAYOUT_ID INTEGER CONSTRAINT PK_TB_MDM_LAYOUT PRIMARY KEY AUTOINCREMENT,
    LAYOUT_KIND VARCHAR(20) NOT NULL,
    LAYOUT_NAME TEXT NOT NULL,
    SND_SYSTEM VARCHAR(20),
    RCV_SYSTEM VARCHAR(20),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT FK_TB_MDM_LAYOUT_SYSTEM_SND FOREIGN KEY (SND_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT FK_TB_MDM_LAYOUT_SYSTEM_RCV FOREIGN KEY (RCV_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_LAYOUT_KIND CHECK (LAYOUT_KIND IN ('HEADER','MESSAGE')),
    CONSTRAINT CK_TB_MDM_LAYOUT_STATUS CHECK (STATUS IN ('CREATED','INUSE','DEPRECATED'))
);

CREATE TABLE TB_MDM_EAI (
    EAI_CODE VARCHAR(20) NOT NULL,
    EAI_NAME TEXT NOT NULL,
    ENCODING VARCHAR(20) NOT NULL,
    PAD_RULE TEXT,
    HEADER_LAYOUT_ID INTEGER,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_EAI PRIMARY KEY (EAI_CODE),
    CONSTRAINT FK_TB_MDM_EAI_LAYOUT FOREIGN KEY (HEADER_LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID)
);

CREATE TABLE TB_MDM_LAYOUT_VER (
    LAYOUT_ID INTEGER NOT NULL,
    VER NUMERIC(7,3) NOT NULL,
    VER_KIND VARCHAR(20) NOT NULL DEFAULT 'MAJOR',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    BASE_VER NUMERIC(7,3),
    OWNER_ID VARCHAR(50),
    APPLY_FROM TEXT,
    APPLY_TO TEXT,
    REQUESTED_BY VARCHAR(50),
    REQUESTED_AT TEXT,
    RELEASED_AT TEXT,
    ROW_VERSION BIGINT NOT NULL DEFAULT 0,
    EAI_CODE VARCHAR(20),
    OWN_LENGTH INTEGER NOT NULL DEFAULT 0,
    SWITCH_MODE VARCHAR(20),
    CHANGE_KINDS VARCHAR(200),
    CHANGE_SUMMARY TEXT,
    SNAPSHOT_JSON TEXT CONSTRAINT CK_TB_MDM_LAYOUT_VER_SNAPSHOT_JSON CHECK (SNAPSHOT_JSON IS NULL OR json_valid(SNAPSHOT_JSON)),
    LEGACY_SNAPSHOT_YN VARCHAR(1) NOT NULL DEFAULT 'N',
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    AUD_VER BIGINT,
    CONSTRAINT PK_TB_MDM_LAYOUT_VER PRIMARY KEY (LAYOUT_ID, VER),
    CONSTRAINT FK_TB_MDM_LAYOUT_VER_LAYOUT FOREIGN KEY (LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID),
    CONSTRAINT FK_TB_MDM_LAYOUT_VER_EAI FOREIGN KEY (EAI_CODE) REFERENCES TB_MDM_EAI (EAI_CODE),
    CONSTRAINT CK_TB_MDM_LAYOUT_VER_STATUS CHECK (STATUS IN ('DRAFT','REQUESTED','APPROVED','RELEASED','CANCELLED')),
    CONSTRAINT CK_TB_MDM_LAYOUT_VER_KIND CHECK (VER_KIND IN ('MAJOR','MINOR')),
    CONSTRAINT CK_TB_MDM_LAYOUT_VER_APPLY CHECK (STATUS = 'DRAFT' OR (APPLY_FROM IS NOT NULL AND APPLY_TO IS NOT NULL)),
    CONSTRAINT CK_TB_MDM_LAYOUT_VER_SWITCH CHECK (SWITCH_MODE IS NULL OR SWITCH_MODE IN ('SEQUENTIAL','SIMULTANEOUS')),
    CONSTRAINT CK_TB_MDM_LAYOUT_VER_LEGACY CHECK (LEGACY_SNAPSHOT_YN IN ('Y','N') AND (LEGACY_SNAPSHOT_YN = 'N' OR SNAPSHOT_JSON IS NOT NULL))
);

CREATE TABLE TB_MDM_LAYOUT_ITEM (
    LAYOUT_ID INTEGER NOT NULL,
    VER NUMERIC(7,3) NOT NULL,
    SEQ INTEGER NOT NULL,
    FILL_KIND VARCHAR(20) NOT NULL,
    COLUMN_PHYS VARCHAR(50),
    TRANS_UNIT VARCHAR(20),
    UNIT_ITEM VARCHAR(50),
    NUM_FORMAT VARCHAR(50),
    DEFAULT_VALUE VARCHAR(50),
    FILLER_LENGTH INTEGER,
    `OFFSET` INTEGER NOT NULL DEFAULT 0,
    `LENGTH` INTEGER NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    AUD_VER BIGINT,
    CONSTRAINT PK_TB_MDM_LAYOUT_ITEM PRIMARY KEY (LAYOUT_ID, VER, SEQ),
    CONSTRAINT FK_TB_MDM_LAYOUT_ITEM_VER FOREIGN KEY (LAYOUT_ID, VER) REFERENCES TB_MDM_LAYOUT_VER (LAYOUT_ID, VER),
    CONSTRAINT FK_TB_MDM_LAYOUT_ITEM_COLUMN FOREIGN KEY (COLUMN_PHYS) REFERENCES TB_MDM_COLUMN (PHYS_NAME),
    CONSTRAINT FK_TB_MDM_LAYOUT_ITEM_UNIT FOREIGN KEY (TRANS_UNIT) REFERENCES TB_MDM_UNIT (UNIT_CODE),
    CONSTRAINT CK_TB_MDM_LAYOUT_ITEM_FILL_KIND CHECK (FILL_KIND IN ('DATA','CONST','AUTO','FILLER')),
    CONSTRAINT CK_TB_MDM_LAYOUT_ITEM_UNIT CHECK (TRANS_UNIT IS NULL OR UNIT_ITEM IS NULL)
);

CREATE TABLE TB_MDM_LAYOUT_HEADER (
    LAYOUT_ID INTEGER NOT NULL,
    VER NUMERIC(7,3) NOT NULL,
    SEQ INTEGER NOT NULL,
    HEADER_LAYOUT_ID INTEGER NOT NULL,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    AUD_VER BIGINT,
    CONSTRAINT PK_TB_MDM_LAYOUT_HEADER PRIMARY KEY (LAYOUT_ID, VER, SEQ),
    CONSTRAINT FK_TB_MDM_LAYOUT_HEADER_VER FOREIGN KEY (LAYOUT_ID, VER) REFERENCES TB_MDM_LAYOUT_VER (LAYOUT_ID, VER),
    CONSTRAINT FK_TB_MDM_LAYOUT_HEADER_HEADER FOREIGN KEY (HEADER_LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID)
);
-- 상수 표의 FK 대상 — CONST 를 넣기 전에 있어야 한다(SQLite 는 부모 키에 유일 인덱스를 요구한다)
CREATE UNIQUE INDEX UX_TB_MDM_LAYOUT_HEADER_HDR ON TB_MDM_LAYOUT_HEADER (LAYOUT_ID, VER, HEADER_LAYOUT_ID);

-- 재정의 대상은 헤더 항목 물리명이다 — 헤더 버전이 바뀌어 SEQ 가 움직여도 짝이 유지된다(D-144 3단계). 헤더 항목 FK 는 둘 수 없다
-- (어느 헤더 버전인지는 판정 시각에 정해진다, K1)
CREATE TABLE TB_MDM_LAYOUT_CONST (
    LAYOUT_ID INTEGER NOT NULL,
    VER NUMERIC(7,3) NOT NULL,
    HEADER_LAYOUT_ID INTEGER NOT NULL,
    HEADER_COLUMN_PHYS VARCHAR(50) NOT NULL,
    CONST_VALUE VARCHAR(50) NOT NULL,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    AUD_VER BIGINT,
    CONSTRAINT PK_TB_MDM_LAYOUT_CONST PRIMARY KEY (LAYOUT_ID, VER, HEADER_LAYOUT_ID, HEADER_COLUMN_PHYS),
    CONSTRAINT FK_TB_MDM_LAYOUT_CONST_HEADER FOREIGN KEY (LAYOUT_ID, VER, HEADER_LAYOUT_ID)
        REFERENCES TB_MDM_LAYOUT_HEADER (LAYOUT_ID, VER, HEADER_LAYOUT_ID)
);

-- ⑤ 복사(부모 → 자식). 이행한 레이아웃은 모두 이미 적용된 RELEASED 를 가지므로 INUSE 다
INSERT INTO TB_MDM_LAYOUT (LAYOUT_ID, LAYOUT_KIND, LAYOUT_NAME, SND_SYSTEM, RCV_SYSTEM, STATUS,
    C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, VER)
SELECT LAYOUT_ID, LAYOUT_KIND, LAYOUT_NAME, SND_SYSTEM, RCV_SYSTEM, 'INUSE',
    C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, VER
FROM TB_MDM_LAYOUT_BAK;

-- AUTOINCREMENT 상한 복원 — 지운 끝 번호를 다시 쓰지 않는다(V16 과 같은 방식)
INSERT INTO sqlite_sequence (name, seq)
SELECT 'TB_MDM_LAYOUT', seq FROM TB_MDM_LAYOUT_V21_SEQ
WHERE NOT EXISTS (SELECT 1 FROM sqlite_sequence WHERE name = 'TB_MDM_LAYOUT');
UPDATE sqlite_sequence
SET seq = (SELECT seq FROM TB_MDM_LAYOUT_V21_SEQ)
WHERE name = 'TB_MDM_LAYOUT'
  AND seq < (SELECT seq FROM TB_MDM_LAYOUT_V21_SEQ);

INSERT INTO TB_MDM_EAI (EAI_CODE, EAI_NAME, ENCODING, PAD_RULE, HEADER_LAYOUT_ID,
    C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, VER)
SELECT EAI_CODE, EAI_NAME, ENCODING, PAD_RULE, HEADER_LAYOUT_ID,
    C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, VER
FROM TB_MDM_EAI_BAK;

-- ⑤-1 저장 이력이 있는 레이아웃 — 이력 행마다 RELEASED. 다음 이력의 시작에서 닫고, 최신만 항목 행을 가진다(LEGACY 'N')
INSERT INTO TB_MDM_LAYOUT_VER (LAYOUT_ID, VER, VER_KIND, STATUS, BASE_VER, OWNER_ID, APPLY_FROM, APPLY_TO,
    REQUESTED_BY, REQUESTED_AT, RELEASED_AT, ROW_VERSION, EAI_CODE, OWN_LENGTH,
    SWITCH_MODE, CHANGE_KINDS, CHANGE_SUMMARY, SNAPSHOT_JSON, LEGACY_SNAPSHOT_YN,
    C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, AUD_VER)
SELECT v.LAYOUT_ID, CAST(v.LAYOUT_VERSION AS NUMERIC), 'MAJOR', 'RELEASED',
    (SELECT CAST(MAX(p.LAYOUT_VERSION) AS NUMERIC) FROM TB_MDM_LAYOUT_VER_BAK p
      WHERE p.LAYOUT_ID = v.LAYOUT_ID AND p.LAYOUT_VERSION < v.LAYOUT_VERSION),
    NULL, sp.APPLY_FROM,
    COALESCE((SELECT n.APPLY_FROM FROM TB_MDM_LAYOUT_V21_SPAN n
               WHERE n.LAYOUT_ID = v.LAYOUT_ID AND n.LAYOUT_VERSION > v.LAYOUT_VERSION
               ORDER BY n.LAYOUT_VERSION LIMIT 1), '9999-12-31 00:00:00'),
    v.C_USR_ID, sp.SAVED_KST, sp.SAVED_KST, 0,
    CASE WHEN v.LAYOUT_VERSION = k.LATEST THEN k.EAI_CODE
         ELSE (SELECT e.EAI_CODE FROM TB_MDM_EAI_BAK e WHERE e.EAI_CODE = json_extract(v.SNAPSHOT_JSON, '$.eaiCode')) END,
    CASE WHEN v.LAYOUT_VERSION = k.LATEST THEN k.OWN_LENGTH
         ELSE v.TOTAL_LENGTH - COALESCE((SELECT SUM(json_extract(j.value, '$.totalLength'))
                                           FROM json_each(v.SNAPSHOT_JSON, '$.headers') j), 0) END,
    v.SWITCH_MODE, v.CHANGE_KINDS, v.CHANGE_SUMMARY,
    CASE WHEN v.LAYOUT_VERSION = k.LATEST THEN NULL ELSE v.SNAPSHOT_JSON END,
    CASE WHEN v.LAYOUT_VERSION = k.LATEST THEN 'N' ELSE 'Y' END,
    v.C_USR_ID, v.C_AT, v.C_SVC_ID, v.C_PGM_ID, v.U_USR_ID, v.U_AT, v.U_SVC_ID, v.U_PGM_ID, v.VER
FROM TB_MDM_LAYOUT_VER_BAK v
JOIN TB_MDM_LAYOUT_V21_SPAN sp ON sp.LAYOUT_ID = v.LAYOUT_ID AND sp.LAYOUT_VERSION = v.LAYOUT_VERSION
JOIN TB_MDM_LAYOUT_V21_KEY k ON k.LAYOUT_ID = v.LAYOUT_ID;

-- ⑤-2 이력이 없는 레이아웃(헤더 전부 + 저장 이력 없는 전문) — 현재 행이 1.000 RELEASED, 이행 하한부터(Ruling P2-11)
INSERT INTO TB_MDM_LAYOUT_VER (LAYOUT_ID, VER, VER_KIND, STATUS, BASE_VER, OWNER_ID, APPLY_FROM, APPLY_TO,
    REQUESTED_BY, REQUESTED_AT, RELEASED_AT, ROW_VERSION, EAI_CODE, OWN_LENGTH,
    SWITCH_MODE, CHANGE_KINDS, CHANGE_SUMMARY, SNAPSHOT_JSON, LEGACY_SNAPSHOT_YN,
    C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, AUD_VER)
SELECT l.LAYOUT_ID, 1, 'MAJOR', 'RELEASED', NULL, NULL, '2000-01-01 00:00:00', '9999-12-31 00:00:00',
    l.C_USR_ID, k.CREATED_KST, k.CREATED_KST, 0,
    k.EAI_CODE, k.OWN_LENGTH,
    NULL, 'INITIAL', '이행(V21) — 저장 이력 없음', NULL, 'N',
    l.C_USR_ID, l.C_AT, l.C_SVC_ID, l.C_PGM_ID, l.U_USR_ID, l.U_AT, l.U_SVC_ID, l.U_PGM_ID, 0
FROM TB_MDM_LAYOUT_BAK l
JOIN TB_MDM_LAYOUT_V21_KEY k ON k.LAYOUT_ID = l.LAYOUT_ID
WHERE NOT EXISTS (SELECT 1 FROM TB_MDM_LAYOUT_VER_BAK v WHERE v.LAYOUT_ID = l.LAYOUT_ID);

-- ⑤-3 항목 — 최신 버전에만. 전문 본문 오프셋은 쌓인 헤더 길이를 빼 본문 기준 상대값으로 바꾼다
INSERT INTO TB_MDM_LAYOUT_ITEM (LAYOUT_ID, VER, SEQ, FILL_KIND, COLUMN_PHYS, TRANS_UNIT, UNIT_ITEM, NUM_FORMAT,
    DEFAULT_VALUE, FILLER_LENGTH, `OFFSET`, `LENGTH`,
    C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, AUD_VER)
SELECT i.LAYOUT_ID, CAST(k.LATEST AS NUMERIC), i.SEQ, i.FILL_KIND, i.COLUMN_PHYS, i.TRANS_UNIT, i.UNIT_ITEM, i.NUM_FORMAT,
    i.DEFAULT_VALUE, i.FILLER_LENGTH,
    CASE WHEN l.LAYOUT_KIND = 'MESSAGE' THEN i.`OFFSET` - k.HEADER_LENGTH ELSE i.`OFFSET` END, i.`LENGTH`,
    i.C_USR_ID, i.C_AT, i.C_SVC_ID, i.C_PGM_ID, i.U_USR_ID, i.U_AT, i.U_SVC_ID, i.U_PGM_ID, i.VER
FROM TB_MDM_LAYOUT_ITEM_BAK i
JOIN TB_MDM_LAYOUT_V21_KEY k ON k.LAYOUT_ID = i.LAYOUT_ID
JOIN TB_MDM_LAYOUT_BAK l ON l.LAYOUT_ID = i.LAYOUT_ID;

INSERT INTO TB_MDM_LAYOUT_HEADER (LAYOUT_ID, VER, SEQ, HEADER_LAYOUT_ID,
    C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, AUD_VER)
SELECT s.LAYOUT_ID, CAST(k.LATEST AS NUMERIC), s.SEQ, s.HEADER_LAYOUT_ID,
    s.C_USR_ID, s.C_AT, s.C_SVC_ID, s.C_PGM_ID, s.U_USR_ID, s.U_AT, s.U_SVC_ID, s.U_PGM_ID, s.VER
FROM TB_MDM_LAYOUT_HEADER_BAK s
JOIN TB_MDM_LAYOUT_V21_KEY k ON k.LAYOUT_ID = s.LAYOUT_ID;

-- 재정의 — 옛 (헤더, SEQ) 를 그 헤더 항목의 물리명으로 바꾼다. 물리명 없는 대상(L03 로 생길 수 없다)은 옮기지 않는다
INSERT INTO TB_MDM_LAYOUT_CONST (LAYOUT_ID, VER, HEADER_LAYOUT_ID, HEADER_COLUMN_PHYS, CONST_VALUE,
    C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, AUD_VER)
SELECT c.LAYOUT_ID, CAST(k.LATEST AS NUMERIC), c.HEADER_LAYOUT_ID, hi.COLUMN_PHYS, c.CONST_VALUE,
    c.C_USR_ID, c.C_AT, c.C_SVC_ID, c.C_PGM_ID, c.U_USR_ID, c.U_AT, c.U_SVC_ID, c.U_PGM_ID, c.VER
FROM TB_MDM_LAYOUT_CONST_BAK c
JOIN TB_MDM_LAYOUT_V21_KEY k ON k.LAYOUT_ID = c.LAYOUT_ID
JOIN TB_MDM_LAYOUT_ITEM_BAK hi ON hi.LAYOUT_ID = c.HEADER_LAYOUT_ID AND hi.SEQ = c.HEADER_SEQ
WHERE hi.COLUMN_PHYS IS NOT NULL;

-- ⑥ 임시 표 삭제
DROP TABLE TB_MDM_LAYOUT_V21_SPAN;
DROP TABLE TB_MDM_LAYOUT_V21_HIST;
DROP TABLE TB_MDM_LAYOUT_V21_KEY;
DROP TABLE TB_MDM_LAYOUT_V21_SEQ;
DROP TABLE TB_MDM_LAYOUT_CONST_BAK;
DROP TABLE TB_MDM_LAYOUT_HEADER_BAK;
DROP TABLE TB_MDM_LAYOUT_ITEM_BAK;
DROP TABLE TB_MDM_LAYOUT_VER_BAK;
DROP TABLE TB_MDM_EAI_BAK;
DROP TABLE TB_MDM_LAYOUT_BAK;
