-- TSK-07-01 design.md §1·§2·§6.0 — 05 영역(마스터데이터) 원장 7테이블(SQLite).
-- 1차 텍스트는 docs/mdm/erd/05-master-data.sqlite.sql(TSK-02-03) 이되, 이 Task 가 갈라지는 두 지점만
-- 명시적으로 다르게 쓴다(불변 규칙 §5):
--   ① 감사 VER 은 SQLite 도 BIGINT 로 쓴다(F15, V2~V4 실제 관례 — ERD 초안의 INTEGER 는 드리프트).
--   ② TB_MDM_DATA_CATE 에 CK_TB_MDM_DATA_CATE_TARGET 을 추가한다(F18, CategoryOwner.MASTER_DATA
--      .allowedDefTargets() 와 값 집합을 정확히 맞춘다).
-- 그 외 칼럼·타입·NULL 여부·제약·FK 배치는 ERD 원문을 그대로 옮긴다(불변 규칙 1·2·10).
-- 순환 FK 가 없으므로(§1) 단순 순서로 인라인 FK 를 건다: DATA → DATA_SYSTEM → DATA_ITEM → DATA_CATE →
-- DATA_CATE_ITEM → DATA_RECV → DATA_RECV_ITEM. CASCADE 는 쓰지 않는다.
-- 보류 테이블(TB_MDM_DATA_SYSTEM·TB_MDM_DATA_RECV·TB_MDM_DATA_RECV_ITEM)도 DDL 은 만든다(F3·PRD §2 규칙 7).

CREATE TABLE TB_MDM_DATA (
    MARU_DATA_ID VARCHAR(50) NOT NULL,
    MARU_DATA_NAME TEXT NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'INUSE',
    SOURCE_KIND VARCHAR(20) NOT NULL,
    SOURCE_SYSTEM VARCHAR(20),
    CODE_PATTERN TEXT NOT NULL DEFAULT '^[0-9A-Z]{1,20}$',
    DESCRIPTION TEXT,
    ATTR01_NAME TEXT, ATTR02_NAME TEXT, ATTR03_NAME TEXT, ATTR04_NAME TEXT, ATTR05_NAME TEXT,
    ATTR06_NAME TEXT, ATTR07_NAME TEXT, ATTR08_NAME TEXT, ATTR09_NAME TEXT, ATTR10_NAME TEXT,
    LVL_CNT INTEGER NOT NULL DEFAULT 0,
    CLOSED_AT TEXT,
    LAST_CHG_SEQ INTEGER NOT NULL DEFAULT 0,
    CHG_SEQ INTEGER NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_DATA PRIMARY KEY (MARU_DATA_ID),
    CONSTRAINT FK_TB_MDM_DATA_SYSTEM_SRC FOREIGN KEY (SOURCE_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_DATA_STATUS CHECK (STATUS IN ('INUSE','DEPRECATED')),
    CONSTRAINT CK_TB_MDM_DATA_SRC_KIND CHECK (SOURCE_KIND IN ('MDM','EXTERNAL')),
    CONSTRAINT CK_TB_MDM_DATA_SRC_SYS CHECK ((SOURCE_KIND = 'EXTERNAL' AND SOURCE_SYSTEM IS NOT NULL) OR (SOURCE_KIND = 'MDM' AND SOURCE_SYSTEM IS NULL)),
    CONSTRAINT CK_TB_MDM_DATA_LVL_CNT CHECK (LVL_CNT BETWEEN 0 AND 5)
);

-- 보류 테이블(배포 대상, PRD §2 규칙 7·F3·F4 — DDL·엔티티는 만들되 서비스·화면은 없음).
CREATE TABLE TB_MDM_DATA_SYSTEM (
    MARU_DATA_ID VARCHAR(50) NOT NULL,
    SYSTEM_CODE VARCHAR(20) NOT NULL,
    DESCRIPTION TEXT,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_DATA_SYSTEM PRIMARY KEY (MARU_DATA_ID, SYSTEM_CODE),
    CONSTRAINT FK_TB_MDM_DATA_SYSTEM_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID),
    CONSTRAINT FK_TB_MDM_DATA_SYSTEM_SYSTEM FOREIGN KEY (SYSTEM_CODE) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE)
);

CREATE TABLE TB_MDM_DATA_ITEM (
    MARU_DATA_ID VARCHAR(50) NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    VALID_FROM TEXT NOT NULL,
    NAME TEXT NOT NULL,
    ALTER_NAME TEXT,
    SEQ INTEGER,
    DESCRIPTION TEXT,
    VALID_TO TEXT NOT NULL DEFAULT '9999-12-31 00:00:00',
    ROW_VERSION INTEGER NOT NULL DEFAULT 0,
    CHG_SEQ INTEGER NOT NULL DEFAULT 0,
    LVL1 VARCHAR(50), LVL2 VARCHAR(50), LVL3 VARCHAR(50), LVL4 VARCHAR(50), LVL5 VARCHAR(50),
    ATTR01 TEXT, ATTR02 TEXT, ATTR03 TEXT, ATTR04 TEXT, ATTR05 TEXT,
    ATTR06 TEXT, ATTR07 TEXT, ATTR08 TEXT, ATTR09 TEXT, ATTR10 TEXT,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_DATA_ITEM PRIMARY KEY (MARU_DATA_ID, CODE, VALID_FROM),
    CONSTRAINT FK_TB_MDM_DATA_ITEM_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID)
);
CREATE INDEX IX_TB_MDM_DATA_ITEM_NAME ON TB_MDM_DATA_ITEM (MARU_DATA_ID, NAME);

-- CK_TB_MDM_DATA_CATE_TARGET(F18 신설) — DEF_TARGET 허용값을 CategoryOwner.MASTER_DATA.allowedDefTargets()
-- (KEY, LVL1-5, ATTR01-10 — CODE 는 포함하지 않는다)와 정확히 맞춘다. DDL 수준에서 "계약 재사용"을 증명한다.
CREATE TABLE TB_MDM_DATA_CATE (
    MARU_DATA_ID VARCHAR(50) NOT NULL,
    CATE_ID VARCHAR(50) NOT NULL,
    VALID_FROM TEXT NOT NULL,
    CATE_NAME TEXT,
    DEF_KIND VARCHAR(20) NOT NULL,
    DEF_EXPR TEXT,
    DEF_TARGET VARCHAR(20),
    DESCRIPTION TEXT,
    VALID_TO TEXT NOT NULL DEFAULT '9999-12-31 00:00:00',
    CHG_SEQ INTEGER NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_DATA_CATE PRIMARY KEY (MARU_DATA_ID, CATE_ID, VALID_FROM),
    CONSTRAINT FK_TB_MDM_DATA_CATE_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID),
    CONSTRAINT CK_TB_MDM_DATA_CATE_KIND CHECK (DEF_KIND IN ('REGEX','TABLE')),
    CONSTRAINT CK_TB_MDM_DATA_CATE_DEF CHECK ((DEF_KIND = 'REGEX' AND DEF_EXPR IS NOT NULL AND DEF_TARGET IS NOT NULL) OR (DEF_KIND = 'TABLE' AND DEF_EXPR IS NULL AND DEF_TARGET IS NULL)),
    CONSTRAINT CK_TB_MDM_DATA_CATE_TARGET CHECK (DEF_TARGET IS NULL OR DEF_TARGET IN ('KEY','LVL1','LVL2','LVL3','LVL4','LVL5','ATTR01','ATTR02','ATTR03','ATTR04','ATTR05','ATTR06','ATTR07','ATTR08','ATTR09','ATTR10'))
);

-- CATE_ID·CODE 는 FK 없음(F13, 선분 때문에 앱이 검사한다). MARU_DATA_ID → TB_MDM_DATA FK 만 건다.
CREATE TABLE TB_MDM_DATA_CATE_ITEM (
    MARU_DATA_ID VARCHAR(50) NOT NULL,
    CATE_ID VARCHAR(50) NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    VALID_FROM TEXT NOT NULL,
    VALID_TO TEXT NOT NULL DEFAULT '9999-12-31 00:00:00',
    CHG_SEQ INTEGER NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_DATA_CATE_ITEM PRIMARY KEY (MARU_DATA_ID, CATE_ID, CODE, VALID_FROM),
    CONSTRAINT FK_TB_MDM_DATA_CATE_ITEM_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID)
);

-- 보류 테이블(배포 안 함, F3·F4). RECV_ID 는 AUTOINCREMENT 라 PK 를 칼럼 정의 안에 인라인으로 건다(V4 선례).
CREATE TABLE TB_MDM_DATA_RECV (
    RECV_ID INTEGER CONSTRAINT PK_TB_MDM_DATA_RECV PRIMARY KEY AUTOINCREMENT,
    MARU_DATA_ID VARCHAR(50),
    SOURCE_SYSTEM VARCHAR(20) NOT NULL,
    SOURCE_REF VARCHAR(50),
    RECEIVED_AT TEXT NOT NULL,
    BODY TEXT NOT NULL,
    ROW_COUNT INTEGER NOT NULL DEFAULT 0,
    "RESULT" VARCHAR(20),
    RESULT_DETAIL TEXT,
    CHG_SEQ INTEGER,
    PROCESSED_AT TEXT,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT FK_TB_MDM_DATA_RECV_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID),
    CONSTRAINT FK_TB_MDM_DATA_RECV_SYSTEM FOREIGN KEY (SOURCE_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_DATA_RECV_RESULT CHECK ("RESULT" IS NULL OR "RESULT" IN ('OK','REJECTED','FAILED'))
);

CREATE TABLE TB_MDM_DATA_RECV_ITEM (
    RECV_ID INTEGER NOT NULL,
    SEQ INTEGER NOT NULL,
    CODE VARCHAR(50),
    "ACTION" VARCHAR(20),
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_DATA_RECV_ITEM PRIMARY KEY (RECV_ID, SEQ),
    CONSTRAINT FK_TB_MDM_DATA_RECV_ITEM_RECV FOREIGN KEY (RECV_ID) REFERENCES TB_MDM_DATA_RECV (RECV_ID),
    CONSTRAINT CK_TB_MDM_DATA_RECV_ITEM_ACTION CHECK ("ACTION" IS NULL OR "ACTION" IN ('INSERT','UPDATE','CLOSE','REOPEN','NONE'))
);
