-- TSK-08-01 design.md §1·§2·§6.0 — 06 영역(업무기준) 8테이블(SQLite). 팀장 배정 버전 V8(V5~V7 은 비워 둔다).
-- 1차 텍스트는 docs/mdm/erd/06-business-rule.sqlite.sql(TSK-02-03) 이되, 이 Task 가 확인한 지점에서 갈라진다(§6.1):
--   ① 감사 카운터(VER·AUD_VER)는 SQLite 도 BIGINT 로 쓴다 — naming-dialect-rules §2, V2~V4 선례.
--   ② 모든 ROW_VERSION 은 BIGINT 로 쓴다 — D2, TSK-01-03 인계 ②.
--   ③ 결과 열 VAR_NAME 필수 CHECK(CK_TB_MDM_RULE_VAR_RESULT_NAME)를 더한다 — D3, 06:1011.
--   ④ DISP_TYPE 은 06 표기(Equal·1·2·Expression·Value)만 받는다(CK_TB_MDM_RULE_VAR_DISP) — D4, 06:1009.
--   ⑤ JSON CHECK 는 V3 관례대로 칼럼 정의 안의 인라인 제약으로 통일한다 — F3·F4.
-- TB_MDM_RULE_VER·RULE_VAR·RULE_ROW·RULE_RECV 는 업무 칼럼 VER 와 겹치지 않게 감사 카운터를 AUD_VER 로 둔다(D-034).
-- CASCADE 는 06 이 정한 두 FK(RULE_VAR→RULE_VER, RULE_ROW→RULE_VER)에만 둔다.

CREATE TABLE TB_MDM_RULE (
    MARU_RULE_ID VARCHAR(50) NOT NULL,
    MARU_RULE_NAME TEXT NOT NULL,
    RULE_KIND VARCHAR(20) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    SOURCE_KIND VARCHAR(20) NOT NULL,
    SOURCE_SYSTEM VARCHAR(20),
    DESCRIPTION TEXT,
    USAGE_NOTE TEXT,
    LAST_VAR_ID INTEGER NOT NULL DEFAULT 0,
    LAST_ROW_ID INTEGER NOT NULL DEFAULT 0,
    LAST_CASE_ID INTEGER NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_RULE PRIMARY KEY (MARU_RULE_ID),
    CONSTRAINT FK_TB_MDM_RULE_SYSTEM_SRC FOREIGN KEY (SOURCE_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_RULE_KIND CHECK (RULE_KIND IN ('DECISION','DERIVE')),
    CONSTRAINT CK_TB_MDM_RULE_STATUS CHECK (STATUS IN ('CREATED','INUSE','DEPRECATED')),
    CONSTRAINT CK_TB_MDM_RULE_SRC_KIND CHECK (SOURCE_KIND IN ('MDM','EXTERNAL')),
    CONSTRAINT CK_TB_MDM_RULE_SRC_SYS CHECK ((SOURCE_KIND = 'EXTERNAL' AND SOURCE_SYSTEM IS NOT NULL) OR (SOURCE_KIND = 'MDM' AND SOURCE_SYSTEM IS NULL))
);

-- 보류 테이블(배포 대상, D1·D-019). 엔티티·리포지토리를 붙이지 않는다.
CREATE TABLE TB_MDM_RULE_SYSTEM (
    MARU_RULE_ID VARCHAR(50) NOT NULL,
    SYSTEM_CODE VARCHAR(20) NOT NULL,
    DEPLOY_KIND VARCHAR(20) NOT NULL DEFAULT 'DEF',
    DESCRIPTION TEXT,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_RULE_SYSTEM PRIMARY KEY (MARU_RULE_ID, SYSTEM_CODE),
    CONSTRAINT FK_TB_MDM_RULE_SYSTEM_RULE FOREIGN KEY (MARU_RULE_ID) REFERENCES TB_MDM_RULE (MARU_RULE_ID),
    CONSTRAINT FK_TB_MDM_RULE_SYSTEM_SYSTEM FOREIGN KEY (SYSTEM_CODE) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_RULE_SYSTEM_KIND CHECK (DEPLOY_KIND IN ('DEF','RESULT'))
);

-- 업무 일시(APPLY_*·*_AT)는 KST 'YYYY-MM-DD HH:MM:SS' 문자열이다(규칙표 #16).
CREATE TABLE TB_MDM_RULE_VER (
    MARU_RULE_ID VARCHAR(50) NOT NULL,
    VER INTEGER NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    BASE_VER INTEGER,
    OWNER_ID VARCHAR(50),
    HIT_POLICY VARCHAR(20),
    APPLY_FROM TEXT,
    APPLY_TO TEXT,
    DESCRIPTION TEXT,
    REQUESTED_BY VARCHAR(50),
    REQUESTED_AT TEXT,
    EMERGENCY_YN VARCHAR(1) NOT NULL DEFAULT 'N',
    EMERGENCY_REASON TEXT,
    APPROVED_BY VARCHAR(50),
    APPROVED_AT TEXT,
    REJECT_REASON TEXT,
    RELEASED_AT TEXT,
    CANCELLED_AT TEXT,
    CANCEL_REASON TEXT,
    ROW_VERSION BIGINT NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    AUD_VER BIGINT,
    CONSTRAINT PK_TB_MDM_RULE_VER PRIMARY KEY (MARU_RULE_ID, VER),
    CONSTRAINT FK_TB_MDM_RULE_VER_RULE FOREIGN KEY (MARU_RULE_ID) REFERENCES TB_MDM_RULE (MARU_RULE_ID),
    CONSTRAINT CK_TB_MDM_RULE_VER_STATUS CHECK (STATUS IN ('DRAFT','REQUESTED','APPROVED','RELEASED','CANCELLED')),
    CONSTRAINT CK_TB_MDM_RULE_VER_HIT CHECK (HIT_POLICY IS NULL OR HIT_POLICY IN ('FIRST','UNIQUE','PRIORITY','COLLECT','ANY')),
    CONSTRAINT CK_TB_MDM_RULE_VER_APPLY CHECK (STATUS = 'DRAFT' OR (APPLY_FROM IS NOT NULL AND APPLY_TO IS NOT NULL)),
    CONSTRAINT CK_TB_MDM_RULE_VER_EMERGENCY_YN CHECK (EMERGENCY_YN IN ('Y','N'))
);

CREATE TABLE TB_MDM_RULE_VAR (
    MARU_RULE_ID VARCHAR(50) NOT NULL,
    VER INTEGER NOT NULL,
    VAR_ID INTEGER NOT NULL,
    VAR_KIND VARCHAR(20) NOT NULL,
    DISP_TYPE VARCHAR(20),
    AXIS VARCHAR(20),
    VAR_NAME TEXT,
    VAR_AST TEXT CONSTRAINT CK_TB_MDM_RULE_VAR_VAR_AST_JSON CHECK (VAR_AST IS NULL OR json_valid(VAR_AST)),
    DOMAIN_ID INTEGER,
    DATA_TYPE VARCHAR(20),
    COLLECT_AGG VARCHAR(20) DEFAULT 'LIST',
    PRIO_LIST TEXT CONSTRAINT CK_TB_MDM_RULE_VAR_PRIO_LIST_JSON CHECK (PRIO_LIST IS NULL OR json_valid(PRIO_LIST)),
    RES_GRP VARCHAR(50),
    GRP_COND TEXT,
    GRP_COND_AST TEXT CONSTRAINT CK_TB_MDM_RULE_VAR_GRP_COND_AST_JSON CHECK (GRP_COND_AST IS NULL OR json_valid(GRP_COND_AST)),
    SEQ INTEGER NOT NULL,
    LABEL TEXT,
    DESCRIPTION TEXT,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    AUD_VER BIGINT,
    CONSTRAINT PK_TB_MDM_RULE_VAR PRIMARY KEY (MARU_RULE_ID, VER, VAR_ID),
    CONSTRAINT FK_TB_MDM_RULE_VAR_VER FOREIGN KEY (MARU_RULE_ID, VER) REFERENCES TB_MDM_RULE_VER (MARU_RULE_ID, VER) ON DELETE CASCADE,
    CONSTRAINT FK_TB_MDM_RULE_VAR_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES TB_MDM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_TB_MDM_RULE_VAR_KIND CHECK (VAR_KIND IN ('COND','RESULT')),
    CONSTRAINT CK_TB_MDM_RULE_VAR_DISP CHECK (DISP_TYPE IS NULL OR DISP_TYPE IN ('Equal','1','2','Expression','Value')),
    CONSTRAINT CK_TB_MDM_RULE_VAR_AXIS CHECK (AXIS IS NULL OR AXIS IN ('ROW','COL','NONE')),
    CONSTRAINT CK_TB_MDM_RULE_VAR_DTYPE CHECK (DATA_TYPE IS NULL OR DATA_TYPE IN ('BOOLEAN','NUMBER','STRING','DATE')),
    CONSTRAINT CK_TB_MDM_RULE_VAR_AGG CHECK (COLLECT_AGG IS NULL OR COLLECT_AGG IN ('LIST','SUM','MIN','MAX','COUNT')),
    CONSTRAINT CK_TB_MDM_RULE_VAR_RESULT_NAME CHECK (VAR_KIND <> 'RESULT' OR VAR_NAME IS NOT NULL)
);
CREATE UNIQUE INDEX UX_TB_MDM_RULE_VAR_SEQ ON TB_MDM_RULE_VAR (MARU_RULE_ID, VER, VAR_KIND, SEQ);
CREATE UNIQUE INDEX UX_TB_MDM_RULE_VAR_NAME ON TB_MDM_RULE_VAR (MARU_RULE_ID, VER, VAR_NAME) WHERE VAR_KIND = 'RESULT';

CREATE TABLE TB_MDM_RULE_ROW (
    MARU_RULE_ID VARCHAR(50) NOT NULL,
    VER INTEGER NOT NULL,
    ROW_ID INTEGER NOT NULL,
    SEQ INTEGER NOT NULL DEFAULT 0,
    ROW_KIND VARCHAR(20) NOT NULL,
    CELLS TEXT NOT NULL CONSTRAINT CK_TB_MDM_RULE_ROW_CELLS_JSON CHECK (json_valid(CELLS)),
    NOTE TEXT,
    TAG VARCHAR(50),
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    AUD_VER BIGINT,
    CONSTRAINT PK_TB_MDM_RULE_ROW PRIMARY KEY (MARU_RULE_ID, VER, ROW_ID),
    CONSTRAINT FK_TB_MDM_RULE_ROW_VER FOREIGN KEY (MARU_RULE_ID, VER) REFERENCES TB_MDM_RULE_VER (MARU_RULE_ID, VER) ON DELETE CASCADE,
    CONSTRAINT CK_TB_MDM_RULE_ROW_KIND CHECK (ROW_KIND IN ('NORMAL','DEFAULT'))
);
CREATE UNIQUE INDEX UX_TB_MDM_RULE_ROW_SEQ ON TB_MDM_RULE_ROW (MARU_RULE_ID, VER, SEQ) WHERE ROW_KIND = 'NORMAL';

CREATE TABLE TB_MDM_RULE_TEST_CASE (
    MARU_RULE_ID VARCHAR(50) NOT NULL,
    CASE_ID INTEGER NOT NULL,
    CASE_NAME TEXT,
    INPUT_JSON TEXT NOT NULL CONSTRAINT CK_TB_MDM_RULE_TEST_CASE_INPUT_JSON CHECK (json_valid(INPUT_JSON)),
    EXPECTED_JSON TEXT CONSTRAINT CK_TB_MDM_RULE_TEST_CASE_EXPECTED_JSON CHECK (EXPECTED_JSON IS NULL OR json_valid(EXPECTED_JSON)),
    DESCRIPTION TEXT,
    ROW_VERSION BIGINT NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_RULE_TEST_CASE PRIMARY KEY (MARU_RULE_ID, CASE_ID),
    CONSTRAINT FK_TB_MDM_RULE_TEST_CASE_RULE FOREIGN KEY (MARU_RULE_ID) REFERENCES TB_MDM_RULE (MARU_RULE_ID)
);

-- 버전 없음(저장 즉시 배포). RULE_IDS 는 FK 가 아니다.
CREATE TABLE TB_MDM_RULE_SET (
    MARU_RULE_SET_ID VARCHAR(50) NOT NULL,
    MARU_RULE_SET_NAME TEXT NOT NULL,
    RULE_IDS TEXT NOT NULL CONSTRAINT CK_TB_MDM_RULE_SET_RULE_IDS_JSON CHECK (json_valid(RULE_IDS)),
    DESCRIPTION TEXT,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'INUSE',
    ROW_VERSION BIGINT NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_RULE_SET PRIMARY KEY (MARU_RULE_SET_ID),
    CONSTRAINT CK_TB_MDM_RULE_SET_STATUS CHECK (STATUS IN ('INUSE','DEPRECATED'))
);

-- 보류 테이블(수신 로그, D1·D-019). 엔티티·리포지토리를 붙이지 않는다. BODY 는 요청 원문이라 JSON CHECK 를 두지 않는다(F5).
CREATE TABLE TB_MDM_RULE_RECV (
    RECV_ID INTEGER CONSTRAINT PK_TB_MDM_RULE_RECV PRIMARY KEY AUTOINCREMENT,
    MARU_RULE_ID VARCHAR(50),
    SOURCE_SYSTEM VARCHAR(20) NOT NULL,
    SOURCE_REF VARCHAR(50),
    REQ_KIND VARCHAR(20) NOT NULL,
    RECEIVED_AT TEXT NOT NULL,
    BODY TEXT NOT NULL,
    "RESULT" VARCHAR(20),
    RESULT_DETAIL TEXT,
    VER INTEGER,
    PROCESSED_AT TEXT,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    AUD_VER BIGINT,
    CONSTRAINT FK_TB_MDM_RULE_RECV_RULE FOREIGN KEY (MARU_RULE_ID) REFERENCES TB_MDM_RULE (MARU_RULE_ID),
    CONSTRAINT FK_TB_MDM_RULE_RECV_SYSTEM FOREIGN KEY (SOURCE_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_RULE_RECV_REQ CHECK (REQ_KIND IN ('VERSION','CANCEL','DEPRECATE')),
    CONSTRAINT CK_TB_MDM_RULE_RECV_RESULT CHECK ("RESULT" IS NULL OR "RESULT" IN ('OK','REJECTED','FAILED'))
);
