-- TSK-06-01 design.md §1·§2·§6.0 — 04 영역(마스터코드) 7테이블(SQLite) + FK_TB_MDM_DOMAIN_CODE 후행 추가.
-- 버전 번호는 V9 다(D1 — origin/dev 머지 뒤 mdm 두 방언 폴더의 최대 버전 V8 + 1). 당초 팀장 배정 V6 이었고
-- 2026-09-24 팀장 정정(배정표 폐기, done 직전 머지 뒤 최대 버전+1)으로 V9 로 재채번했다. DDL 본문은 그대로다.
-- 1차 텍스트는 docs/mdm/erd/04-master-code.sqlite.sql(TSK-02-03) 이되, 이 Task 가 실측·원천 대조로 갈라진
-- 지점만 바꾼다(§6.0 G1~G5):
--   G1 감사 VER(5표)·AUD_VER(VER·RECV) 는 INTEGER 가 아니라 BIGINT — F5(naming-dialect-rules §2, V2~V4 선례).
--   G2 TB_MDM_CODE_VER.ROW_VERSION 은 BIGINT — D5(TSK-01-03 §7 ② 인계, VersionConventions long).
--   G3 CK_TB_MDM_CODE_VER_APPLY 는 REQUESTED 행(apply_from 만 있고 apply_to NULL)을 받는다 — D4(원천 04:999-1000).
--   G4 (MSSQL 전용 — DEF_EXPR NVARCHAR(MAX), D6) SQLite 는 TEXT 그대로다.
--   G5 파일 끝에서 TB_MDM_DOMAIN 을 재생성해 FK_TB_MDM_DOMAIN_CODE 를 건다 — D3(TSK-04-01 D1 인계).
-- 업무 칼럼 LAST_CHG_SEQ·CHG_SEQ(BIGI 토큰)는 V3 선례대로 SQLite INTEGER 를 유지한다(F5).
-- CASCADE 는 어디에도 쓰지 않는다(불변 규칙 8).

CREATE TABLE TB_MDM_CODE (
    MARU_CODE_ID VARCHAR(50) NOT NULL,
    MARU_CODE_NAME TEXT NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    SOURCE_KIND VARCHAR(20) NOT NULL,
    SOURCE_SYSTEM VARCHAR(20),
    DESCRIPTION TEXT,
    ATTR01_NAME TEXT, ATTR02_NAME TEXT, ATTR03_NAME TEXT, ATTR04_NAME TEXT, ATTR05_NAME TEXT,
    ATTR06_NAME TEXT, ATTR07_NAME TEXT, ATTR08_NAME TEXT, ATTR09_NAME TEXT, ATTR10_NAME TEXT,
    LVL_CNT INTEGER NOT NULL DEFAULT 0,
    LAST_CHG_SEQ INTEGER NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_CODE PRIMARY KEY (MARU_CODE_ID),
    CONSTRAINT FK_TB_MDM_CODE_SYSTEM_SRC FOREIGN KEY (SOURCE_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_CODE_STATUS CHECK (STATUS IN ('CREATED','INUSE','DEPRECATED')),
    CONSTRAINT CK_TB_MDM_CODE_SRC_KIND CHECK (SOURCE_KIND IN ('MDM','EXTERNAL')),
    CONSTRAINT CK_TB_MDM_CODE_SRC_SYS CHECK ((SOURCE_KIND = 'EXTERNAL' AND SOURCE_SYSTEM IS NOT NULL) OR (SOURCE_KIND = 'MDM' AND SOURCE_SYSTEM IS NULL)),
    CONSTRAINT CK_TB_MDM_CODE_LVL_CNT CHECK (LVL_CNT BETWEEN 0 AND 5)
);

-- 보류 테이블(배포 안 함, D-019·ADR-0002 D7). 엔티티·리포지토리를 붙이지 않는다(D2).
CREATE TABLE TB_MDM_CODE_SYSTEM (
    MARU_CODE_ID VARCHAR(50) NOT NULL,
    SYSTEM_CODE VARCHAR(20) NOT NULL,
    DESCRIPTION TEXT,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_CODE_SYSTEM PRIMARY KEY (MARU_CODE_ID, SYSTEM_CODE),
    CONSTRAINT FK_TB_MDM_CODE_SYSTEM_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID),
    CONSTRAINT FK_TB_MDM_CODE_SYSTEM_SYSTEM FOREIGN KEY (SYSTEM_CODE) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE)
);

-- 업무 칼럼 VER 과 감사 카운터가 이름이 겹쳐 감사 카운터만 AUD_VER 로 둔다(D-034).
CREATE TABLE TB_MDM_CODE_VER (
    MARU_CODE_ID VARCHAR(50) NOT NULL,
    VER NUMERIC(7,3) NOT NULL,
    VER_KIND VARCHAR(20) NOT NULL,
    RESTORED_FROM NUMERIC(7,3),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    OWNER_ID VARCHAR(50),
    APPLY_FROM TEXT,
    APPLY_TO TEXT,
    DESCRIPTION TEXT,
    REQUESTED_BY VARCHAR(50),
    REQUESTED_AT TEXT,
    EMERGENCY_YN VARCHAR(1) NOT NULL DEFAULT 'N',
    EMERGENCY_REASON TEXT,
    APPROVED_BY VARCHAR(50),
    APPROVED_AT TEXT,
    REJECT_REASON TEXT,
    RELEASED_AT TEXT,
    CANCELLED_AT TEXT,
    CANCEL_REASON TEXT,
    ROW_VERSION BIGINT NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    AUD_VER BIGINT,
    CONSTRAINT PK_TB_MDM_CODE_VER PRIMARY KEY (MARU_CODE_ID, VER),
    CONSTRAINT FK_TB_MDM_CODE_VER_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID),
    CONSTRAINT CK_TB_MDM_CODE_VER_KIND CHECK (VER_KIND IN ('MAJOR','MINOR')),
    CONSTRAINT CK_TB_MDM_CODE_VER_STATUS CHECK (STATUS IN ('DRAFT','REQUESTED','APPROVED','RELEASED','CANCELLED')),
    CONSTRAINT CK_TB_MDM_CODE_VER_APPLY CHECK (STATUS = 'DRAFT' OR (APPLY_FROM IS NOT NULL AND (STATUS = 'REQUESTED' OR APPLY_TO IS NOT NULL))),
    CONSTRAINT CK_TB_MDM_CODE_VER_EMERGENCY_YN CHECK (EMERGENCY_YN IN ('Y','N'))
);

CREATE TABLE TB_MDM_CODE_ITEM (
    MARU_CODE_ID VARCHAR(50) NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    FROM_VER NUMERIC(7,3) NOT NULL,
    TO_VER NUMERIC(7,3) NOT NULL DEFAULT 9999,
    NAME TEXT,
    ALTER_NAME TEXT,
    SEQ INTEGER,
    DESCRIPTION TEXT,
    LVL1 VARCHAR(50), LVL2 VARCHAR(50), LVL3 VARCHAR(50), LVL4 VARCHAR(50), LVL5 VARCHAR(50),
    ATTR01 TEXT, ATTR02 TEXT, ATTR03 TEXT, ATTR04 TEXT, ATTR05 TEXT,
    ATTR06 TEXT, ATTR07 TEXT, ATTR08 TEXT, ATTR09 TEXT, ATTR10 TEXT,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_CODE_ITEM PRIMARY KEY (MARU_CODE_ID, CODE, FROM_VER),
    CONSTRAINT FK_TB_MDM_CODE_ITEM_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID),
    CONSTRAINT FK_TB_MDM_CODE_ITEM_VER FOREIGN KEY (MARU_CODE_ID, FROM_VER) REFERENCES TB_MDM_CODE_VER (MARU_CODE_ID, VER),
    CONSTRAINT CK_TB_MDM_CODE_ITEM_CODE CHECK (CODE NOT LIKE '% %' AND CODE NOT LIKE '%,%')
);

CREATE TABLE TB_MDM_CODE_CATE (
    MARU_CODE_ID VARCHAR(50) NOT NULL,
    CATE_ID VARCHAR(50) NOT NULL,
    FROM_VER NUMERIC(7,3) NOT NULL,
    TO_VER NUMERIC(7,3) NOT NULL DEFAULT 9999,
    CATE_NAME TEXT,
    DEF_KIND VARCHAR(20) NOT NULL,
    DEF_EXPR TEXT,
    DEF_TARGET VARCHAR(20),
    DESCRIPTION TEXT,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_CODE_CATE PRIMARY KEY (MARU_CODE_ID, CATE_ID, FROM_VER),
    CONSTRAINT FK_TB_MDM_CODE_CATE_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID),
    CONSTRAINT FK_TB_MDM_CODE_CATE_VER FOREIGN KEY (MARU_CODE_ID, FROM_VER) REFERENCES TB_MDM_CODE_VER (MARU_CODE_ID, VER),
    CONSTRAINT CK_TB_MDM_CODE_CATE_KIND CHECK (DEF_KIND IN ('REGEX','TABLE')),
    CONSTRAINT CK_TB_MDM_CODE_CATE_DEF CHECK ((DEF_KIND = 'REGEX' AND DEF_EXPR IS NOT NULL AND DEF_TARGET IS NOT NULL) OR (DEF_KIND = 'TABLE' AND DEF_EXPR IS NULL AND DEF_TARGET IS NULL))
);

-- CATE_ID·CODE 자체는 FK 없음(불변 규칙 7 — 저장 시·상신 시 앱 검사). TO_VER 도 FK 없음(9999 는 실제 버전이 아니다, 04:958).
CREATE TABLE TB_MDM_CODE_CATE_ITEM (
    MARU_CODE_ID VARCHAR(50) NOT NULL,
    CATE_ID VARCHAR(50) NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    FROM_VER NUMERIC(7,3) NOT NULL,
    TO_VER NUMERIC(7,3) NOT NULL DEFAULT 9999,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_CODE_CATE_ITEM PRIMARY KEY (MARU_CODE_ID, CATE_ID, CODE, FROM_VER),
    CONSTRAINT FK_TB_MDM_CODE_CATE_ITEM_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID),
    CONSTRAINT FK_TB_MDM_CODE_CATE_ITEM_VER FOREIGN KEY (MARU_CODE_ID, FROM_VER) REFERENCES TB_MDM_CODE_VER (MARU_CODE_ID, VER)
);

-- 보류 테이블(수신 로그, D-019·ADR-0002 D7). 엔티티·리포지토리를 붙이지 않는다(D2). RECV_ID 는 서버 채번(규칙표 #2).
CREATE TABLE TB_MDM_CODE_RECV (
    RECV_ID INTEGER CONSTRAINT PK_TB_MDM_CODE_RECV PRIMARY KEY AUTOINCREMENT,
    MARU_CODE_ID VARCHAR(50),
    SOURCE_SYSTEM VARCHAR(20) NOT NULL,
    SOURCE_REF VARCHAR(50),
    REQ_KIND VARCHAR(20) NOT NULL,
    RECEIVED_AT TEXT NOT NULL,
    BODY TEXT NOT NULL,
    "RESULT" VARCHAR(20),
    RESULT_DETAIL TEXT,
    VER NUMERIC(7,3),
    CHG_SEQ INTEGER,
    PROCESSED_AT TEXT,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    AUD_VER BIGINT,
    CONSTRAINT FK_TB_MDM_CODE_RECV_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID),
    CONSTRAINT FK_TB_MDM_CODE_RECV_SYSTEM FOREIGN KEY (SOURCE_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_CODE_RECV_REQ CHECK (REQ_KIND IN ('VERSION','CANCEL','DEPRECATE')),
    CONSTRAINT CK_TB_MDM_CODE_RECV_RESULT CHECK ("RESULT" IS NULL OR "RESULT" IN ('OK','REJECTED','FAILED'))
);

-- ── G5: TB_MDM_DOMAIN 재생성으로 FK_TB_MDM_DOMAIN_CODE 추가(D3, §6.0.8) ──────────────────────────────
-- SQLite 는 ALTER TABLE ADD CONSTRAINT 가 없어 12단계 재생성 패턴을 쓴다. Flyway 기본 동작대로 이 파일 전체가 한
-- 트랜잭션이라 실패하면 V9 전체가 롤백된다(불변 규칙 20). PRAGMA defer_foreign_keys 는 쓰지 않는다 — 도메인을
-- 참조하는 행(TB_MDM_COLUMN·자식 도메인·V8 의 TB_MDM_RULE_VAR)이 있으면 DROP 의 암묵 DELETE 가 곧바로 FK 위반으로
-- 실패한다(F7-②, 원인이 분명하다). 그런 로컬 DB 는 src/backend/data/mdm.db 를 지우고 다시 띄운다(D3 대가 ①).
-- 다른 표의 FK(TB_MDM_COLUMN·V8 FK_TB_MDM_RULE_VAR_DOMAIN)는 표 이름으로 TB_MDM_DOMAIN 을 가리키므로 ⑤ RENAME 뒤
-- 새 표를 그대로 가리킨다(MdmDomainCodeFkRebuildTest A 가 확인한다).
-- ① TB_MDM_DOMAIN 을 마지막으로 정의한 V3 의 정의를 글자 그대로 옮기고(V4·V8 은 이 표를 바꾸지 않는다), V3 의
--    "걸지 않는다" 주석 자리에 FK 한 줄만 넣는다.
--    V9 앞에 TB_MDM_DOMAIN 을 바꾸는 마이그레이션이 들어오면 이 정의를 그 모습으로 맞춘다(MdmDomainCodeFkRebuildTest A 가 잡는다).
CREATE TABLE TB_MDM_DOMAIN_NEW (
    DOMAIN_ID INTEGER CONSTRAINT PK_TB_MDM_DOMAIN PRIMARY KEY AUTOINCREMENT,
    DOMAIN_NAME TEXT NOT NULL,
    STD_NAME VARCHAR(50) NOT NULL,
    PARENT_DOMAIN_ID INTEGER,
    DOMAIN_KIND VARCHAR(20) NOT NULL,
    DATA_TYPE VARCHAR(20) NOT NULL,
    LENGTH INTEGER,
    SCALE INTEGER,
    UNIT_CODE VARCHAR(20),
    MARU_CODE_ID VARCHAR(50),
    CATE_ID VARCHAR(50),
    STD_RULE TEXT,
    STD_AST TEXT CONSTRAINT CK_TB_MDM_DOMAIN_STD_AST_JSON CHECK (STD_AST IS NULL OR json_valid(STD_AST)),
    BIZ_RULE TEXT,
    BIZ_AST TEXT CONSTRAINT CK_TB_MDM_DOMAIN_BIZ_AST_JSON CHECK (BIZ_AST IS NULL OR json_valid(BIZ_AST)),
    DESCRIPTION TEXT,
    EXAMPLES TEXT CONSTRAINT CK_TB_MDM_DOMAIN_EXAMPLES_JSON CHECK (EXAMPLES IS NULL OR json_valid(EXAMPLES)),
    TEST_CASES TEXT CONSTRAINT CK_TB_MDM_DOMAIN_TEST_CASES_JSON CHECK (TEST_CASES IS NULL OR json_valid(TEST_CASES)),
    CHG_SEQ INTEGER NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT FK_TB_MDM_DOMAIN_DOMAIN FOREIGN KEY (PARENT_DOMAIN_ID) REFERENCES TB_MDM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_TB_MDM_DOMAIN_UNIT FOREIGN KEY (UNIT_CODE) REFERENCES TB_MDM_UNIT (UNIT_CODE),
    CONSTRAINT FK_TB_MDM_DOMAIN_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID),
    CONSTRAINT CK_TB_MDM_DOMAIN_CODE CHECK (DOMAIN_KIND <> 'CODE' OR STD_RULE IS NULL),
    CONSTRAINT CK_TB_MDM_DOMAIN_FLAG CHECK (DOMAIN_KIND <> 'FLAG' OR PARENT_DOMAIN_ID IS NOT NULL OR STD_RULE IS NOT NULL)
);

-- ② 행을 칼럼 목록을 명시해 그대로 옮긴다.
INSERT INTO TB_MDM_DOMAIN_NEW (DOMAIN_ID, DOMAIN_NAME, STD_NAME, PARENT_DOMAIN_ID, DOMAIN_KIND, DATA_TYPE, LENGTH, SCALE,
    UNIT_CODE, MARU_CODE_ID, CATE_ID, STD_RULE, STD_AST, BIZ_RULE, BIZ_AST, DESCRIPTION, EXAMPLES, TEST_CASES, CHG_SEQ,
    C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, VER)
SELECT DOMAIN_ID, DOMAIN_NAME, STD_NAME, PARENT_DOMAIN_ID, DOMAIN_KIND, DATA_TYPE, LENGTH, SCALE,
    UNIT_CODE, MARU_CODE_ID, CATE_ID, STD_RULE, STD_AST, BIZ_RULE, BIZ_AST, DESCRIPTION, EXAMPLES, TEST_CASES, CHG_SEQ,
    C_USR_ID, C_AT, C_SVC_ID, C_PGM_ID, U_USR_ID, U_AT, U_SVC_ID, U_PGM_ID, VER
FROM TB_MDM_DOMAIN;

-- ③ AUTOINCREMENT 상한 보존(F7-④). DROP 은 옛 표의 sqlite_sequence 행을 지우므로, 지운 최댓값 ID 를 다시 쓰지 않게
--    옛 seq 를 새 표 이름으로 옮긴다. 새 표 행이 없으면 INSERT, 있으면(복사로 생겼으면) 더 클 때만 UPDATE 한다.
--    옛 표가 행을 가진 적이 없으면 두 문장 모두 아무것도 하지 않는다. RENAME 은 sqlite_sequence 의 이름도 함께 옮긴다.
INSERT INTO sqlite_sequence (name, seq)
SELECT 'TB_MDM_DOMAIN_NEW', seq FROM sqlite_sequence
WHERE name = 'TB_MDM_DOMAIN'
  AND NOT EXISTS (SELECT 1 FROM sqlite_sequence WHERE name = 'TB_MDM_DOMAIN_NEW');
UPDATE sqlite_sequence
SET seq = (SELECT seq FROM sqlite_sequence WHERE name = 'TB_MDM_DOMAIN')
WHERE name = 'TB_MDM_DOMAIN_NEW'
  AND seq < (SELECT seq FROM sqlite_sequence WHERE name = 'TB_MDM_DOMAIN');

-- ④ 옛 표를 지우고 ⑤ 새 표를 개명한 뒤 ⑥ 인덱스를 다시 만든다(DROP 이 인덱스도 함께 지운다).
DROP TABLE TB_MDM_DOMAIN;
ALTER TABLE TB_MDM_DOMAIN_NEW RENAME TO TB_MDM_DOMAIN;
CREATE INDEX IX_TB_MDM_DOMAIN_PARENT ON TB_MDM_DOMAIN (PARENT_DOMAIN_ID);
