-- mdm Oracle 기준선 V1 — 자동 생성 파일. 직접 고치지 말고 생성기·보정 패치를 고친 뒤 다시 만든다.
--   생성기: src/backend/mdm/tools/oracle-baseline/gen_oracle_baseline.py
--   보정 패치: src/backend/mdm/tools/oracle-baseline/overrides.json · 결정표: DECISIONS.md
--   원천: SQLite 마이그레이션 V1__baseline.sql ~ V23__rule_set_ver_call_set_ids.sql (19개)
--   원천 SHA-256: 0804799aa3d456364a6a123c2846a7b8c060d7d0949d1da5d0745c8b524c0029
-- 접속 사용자 = 스키마 주인(MDMAPUSER). SQL 에 스키마 접두를 두지 않는다.
-- 순서: 표(PK·UNIQUE·CHECK) -> 인덱스 -> FK -> 초기 행.

CREATE TABLE TB_MDM_CODE (
    MARU_CODE_ID           VARCHAR2(50 CHAR) NOT NULL,
    MARU_CODE_NAME         VARCHAR2(4000 BYTE) NOT NULL,
    STATUS                 VARCHAR2(20 CHAR) DEFAULT 'CREATED' NOT NULL,
    SOURCE_KIND            VARCHAR2(20 CHAR) NOT NULL,
    SOURCE_SYSTEM          VARCHAR2(20 CHAR),
    DESCRIPTION            VARCHAR2(4000 BYTE),
    ATTR01_NAME            VARCHAR2(4000 BYTE),
    ATTR02_NAME            VARCHAR2(4000 BYTE),
    ATTR03_NAME            VARCHAR2(4000 BYTE),
    ATTR04_NAME            VARCHAR2(4000 BYTE),
    ATTR05_NAME            VARCHAR2(4000 BYTE),
    ATTR06_NAME            VARCHAR2(4000 BYTE),
    ATTR07_NAME            VARCHAR2(4000 BYTE),
    ATTR08_NAME            VARCHAR2(4000 BYTE),
    ATTR09_NAME            VARCHAR2(4000 BYTE),
    ATTR10_NAME            VARCHAR2(4000 BYTE),
    LVL_CNT                NUMBER(10) DEFAULT 0 NOT NULL,
    LAST_CHG_SEQ           NUMBER(10) DEFAULT 0 NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_CODE PRIMARY KEY (MARU_CODE_ID),
    CONSTRAINT CK_TB_MDM_CODE_STATUS CHECK (STATUS IN ('CREATED','INUSE','DEPRECATED')),
    CONSTRAINT CK_TB_MDM_CODE_SRC_KIND CHECK (SOURCE_KIND IN ('MDM','EXTERNAL')),
    CONSTRAINT CK_TB_MDM_CODE_SRC_SYS CHECK ((SOURCE_KIND = 'EXTERNAL' AND SOURCE_SYSTEM IS NOT NULL) OR (SOURCE_KIND = 'MDM' AND SOURCE_SYSTEM IS NULL)),
    CONSTRAINT CK_TB_MDM_CODE_LVL_CNT CHECK (LVL_CNT BETWEEN 0 AND 5)
);

CREATE TABLE TB_MDM_CODE_CATE (
    MARU_CODE_ID           VARCHAR2(50 CHAR) NOT NULL,
    CATE_ID                VARCHAR2(50 CHAR) NOT NULL,
    FROM_VER               NUMBER(7,3) NOT NULL,
    TO_VER                 NUMBER(7,3) DEFAULT 9999 NOT NULL,
    CATE_NAME              VARCHAR2(4000 BYTE),
    DEF_KIND               VARCHAR2(20 CHAR) NOT NULL,
    DEF_EXPR               VARCHAR2(4000 BYTE),
    DEF_TARGET             VARCHAR2(20 CHAR),
    DESCRIPTION            VARCHAR2(4000 BYTE),
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_CODE_CATE PRIMARY KEY (MARU_CODE_ID, CATE_ID, FROM_VER),
    CONSTRAINT CK_TB_MDM_CODE_CATE_KIND CHECK (DEF_KIND IN ('REGEX','TABLE')),
    CONSTRAINT CK_TB_MDM_CODE_CATE_DEF CHECK ((DEF_KIND = 'REGEX' AND DEF_EXPR IS NOT NULL AND DEF_TARGET IS NOT NULL) OR (DEF_KIND = 'TABLE' AND DEF_EXPR IS NULL AND DEF_TARGET IS NULL))
);

CREATE TABLE TB_MDM_CODE_CATE_ITEM (
    MARU_CODE_ID           VARCHAR2(50 CHAR) NOT NULL,
    CATE_ID                VARCHAR2(50 CHAR) NOT NULL,
    CODE                   VARCHAR2(50 CHAR) NOT NULL,
    FROM_VER               NUMBER(7,3) NOT NULL,
    TO_VER                 NUMBER(7,3) DEFAULT 9999 NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_CODE_CATE_ITEM PRIMARY KEY (MARU_CODE_ID, CATE_ID, CODE, FROM_VER)
);

CREATE TABLE TB_MDM_CODE_ITEM (
    MARU_CODE_ID           VARCHAR2(50 CHAR) NOT NULL,
    CODE                   VARCHAR2(50 CHAR) NOT NULL,
    FROM_VER               NUMBER(7,3) NOT NULL,
    TO_VER                 NUMBER(7,3) DEFAULT 9999 NOT NULL,
    NAME                   VARCHAR2(4000 BYTE),
    ALTER_NAME             VARCHAR2(4000 BYTE),
    SEQ                    NUMBER(10),
    DESCRIPTION            VARCHAR2(4000 BYTE),
    LVL1                   VARCHAR2(50 CHAR),
    LVL2                   VARCHAR2(50 CHAR),
    LVL3                   VARCHAR2(50 CHAR),
    LVL4                   VARCHAR2(50 CHAR),
    LVL5                   VARCHAR2(50 CHAR),
    ATTR01                 VARCHAR2(4000 BYTE),
    ATTR02                 VARCHAR2(4000 BYTE),
    ATTR03                 VARCHAR2(4000 BYTE),
    ATTR04                 VARCHAR2(4000 BYTE),
    ATTR05                 VARCHAR2(4000 BYTE),
    ATTR06                 VARCHAR2(4000 BYTE),
    ATTR07                 VARCHAR2(4000 BYTE),
    ATTR08                 VARCHAR2(4000 BYTE),
    ATTR09                 VARCHAR2(4000 BYTE),
    ATTR10                 VARCHAR2(4000 BYTE),
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_CODE_ITEM PRIMARY KEY (MARU_CODE_ID, CODE, FROM_VER),
    CONSTRAINT CK_TB_MDM_CODE_ITEM_CODE CHECK (CODE NOT LIKE '% %' AND CODE NOT LIKE '%,%')
);

CREATE TABLE TB_MDM_CODE_RECV (
    RECV_ID                NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    MARU_CODE_ID           VARCHAR2(50 CHAR),
    SOURCE_SYSTEM          VARCHAR2(20 CHAR) NOT NULL,
    SOURCE_REF             VARCHAR2(50 CHAR),
    REQ_KIND               VARCHAR2(20 CHAR) NOT NULL,
    RECEIVED_AT            TIMESTAMP(6) NOT NULL,
    BODY                   CLOB NOT NULL,
    "RESULT"               VARCHAR2(20 CHAR),
    RESULT_DETAIL          VARCHAR2(4000 BYTE),
    VER                    NUMBER(7,3),
    CHG_SEQ                NUMBER(10),
    PROCESSED_AT           TIMESTAMP(6),
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    AUD_VER                NUMBER(19),
    CONSTRAINT PK_TB_MDM_CODE_RECV PRIMARY KEY (RECV_ID),
    CONSTRAINT CK_TB_MDM_CODE_RECV_REQ CHECK (REQ_KIND IN ('VERSION','CANCEL','DEPRECATE')),
    CONSTRAINT CK_TB_MDM_CODE_RECV_RESULT CHECK ("RESULT" IS NULL OR "RESULT" IN ('OK','REJECTED','FAILED'))
);

CREATE TABLE TB_MDM_CODE_SYSTEM (
    MARU_CODE_ID           VARCHAR2(50 CHAR) NOT NULL,
    SYSTEM_CODE            VARCHAR2(20 CHAR) NOT NULL,
    DESCRIPTION            VARCHAR2(4000 BYTE),
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_CODE_SYSTEM PRIMARY KEY (MARU_CODE_ID, SYSTEM_CODE)
);

CREATE TABLE TB_MDM_CODE_VER (
    MARU_CODE_ID           VARCHAR2(50 CHAR) NOT NULL,
    VER                    NUMBER(7,3) NOT NULL,
    VER_KIND               VARCHAR2(20 CHAR) NOT NULL,
    RESTORED_FROM          NUMBER(7,3),
    STATUS                 VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
    OWNER_ID               VARCHAR2(50 CHAR),
    APPLY_FROM             TIMESTAMP(6),
    APPLY_TO               TIMESTAMP(6),
    DESCRIPTION            VARCHAR2(4000 BYTE),
    REQUESTED_BY           VARCHAR2(50 CHAR),
    REQUESTED_AT           TIMESTAMP(6),
    EMERGENCY_YN           VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
    EMERGENCY_REASON       VARCHAR2(4000 BYTE),
    APPROVED_BY            VARCHAR2(50 CHAR),
    APPROVED_AT            TIMESTAMP(6),
    REJECT_REASON          VARCHAR2(4000 BYTE),
    RELEASED_AT            TIMESTAMP(6),
    CANCELLED_AT           TIMESTAMP(6),
    CANCEL_REASON          VARCHAR2(4000 BYTE),
    ROW_VERSION            NUMBER(19) DEFAULT 0 NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    AUD_VER                NUMBER(19),
    CONSTRAINT PK_TB_MDM_CODE_VER PRIMARY KEY (MARU_CODE_ID, VER),
    CONSTRAINT CK_TB_MDM_CODE_VER_KIND CHECK (VER_KIND IN ('MAJOR','MINOR')),
    CONSTRAINT CK_TB_MDM_CODE_VER_STATUS CHECK (STATUS IN ('DRAFT','REQUESTED','APPROVED','RELEASED','CANCELLED')),
    CONSTRAINT CK_TB_MDM_CODE_VER_APPLY CHECK (STATUS = 'DRAFT' OR (APPLY_FROM IS NOT NULL AND (STATUS = 'REQUESTED' OR APPLY_TO IS NOT NULL))),
    CONSTRAINT CK_TB_MDM_CODE_VER_EMERGENCY_YN CHECK (EMERGENCY_YN IN ('Y','N'))
);

CREATE TABLE TB_MDM_COLUMN (
    COLUMN_ID              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    COLUMN_NAME            VARCHAR2(4000 BYTE) NOT NULL,
    LABEL_LONG             VARCHAR2(4000 BYTE),
    LABEL_MID              VARCHAR2(4000 BYTE),
    LABEL_SHORT            VARCHAR2(4000 BYTE),
    PHYS_NAME              VARCHAR2(50 CHAR) NOT NULL,
    DESCRIPTION            VARCHAR2(4000 BYTE),
    DOMAIN_ID              NUMBER(19),
    REQUIRED               NUMBER(1) DEFAULT 0 NOT NULL,
    DEFAULT_VALUE          VARCHAR2(50 CHAR),
    REF_KIND               VARCHAR2(20 CHAR),
    REF_TARGET             VARCHAR2(50 CHAR),
    REF_CATE_ID            VARCHAR2(50 CHAR),
    TERM_IDS               VARCHAR2(4000 BYTE),
    USAGE_NOTE             VARCHAR2(4000 BYTE),
    CHG_SEQ                NUMBER(10) DEFAULT 0 NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_COLUMN PRIMARY KEY (COLUMN_ID),
    CONSTRAINT UX_TB_MDM_COLUMN_PHYS_NAME UNIQUE (PHYS_NAME),
    CONSTRAINT CK_TB_MDM_COLUMN_TERM_IDS_JSON CHECK (TERM_IDS IS NULL OR TERM_IDS IS JSON STRICT),
    CONSTRAINT CK_TB_MDM_COLUMN_REQUIRED CHECK (REQUIRED IN (0,1))
);

CREATE TABLE TB_MDM_COLUMN_SYSTEM (
    COLUMN_ID              NUMBER(19) NOT NULL,
    SYSTEM_CODE            VARCHAR2(20 CHAR) NOT NULL,
    PHYS_NAME              VARCHAR2(50 CHAR) NOT NULL,
    TRANSFORM              VARCHAR2(50 CHAR),
    NOTE                   VARCHAR2(4000 BYTE),
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_COLUMN_SYSTEM PRIMARY KEY (COLUMN_ID, SYSTEM_CODE, PHYS_NAME)
);

CREATE TABLE TB_MDM_DATA (
    MARU_DATA_ID           VARCHAR2(50 CHAR) NOT NULL,
    MARU_DATA_NAME         VARCHAR2(4000 BYTE) NOT NULL,
    STATUS                 VARCHAR2(20 CHAR) DEFAULT 'INUSE' NOT NULL,
    SOURCE_KIND            VARCHAR2(20 CHAR) NOT NULL,
    SOURCE_SYSTEM          VARCHAR2(20 CHAR),
    CODE_PATTERN           VARCHAR2(4000 BYTE) DEFAULT '^[0-9A-Z]{1,20}$' NOT NULL,
    DESCRIPTION            VARCHAR2(4000 BYTE),
    ATTR01_NAME            VARCHAR2(4000 BYTE),
    ATTR02_NAME            VARCHAR2(4000 BYTE),
    ATTR03_NAME            VARCHAR2(4000 BYTE),
    ATTR04_NAME            VARCHAR2(4000 BYTE),
    ATTR05_NAME            VARCHAR2(4000 BYTE),
    ATTR06_NAME            VARCHAR2(4000 BYTE),
    ATTR07_NAME            VARCHAR2(4000 BYTE),
    ATTR08_NAME            VARCHAR2(4000 BYTE),
    ATTR09_NAME            VARCHAR2(4000 BYTE),
    ATTR10_NAME            VARCHAR2(4000 BYTE),
    LVL_CNT                NUMBER(10) DEFAULT 0 NOT NULL,
    CLOSED_AT              TIMESTAMP(6),
    LAST_CHG_SEQ           NUMBER(10) DEFAULT 0 NOT NULL,
    CHG_SEQ                NUMBER(10) DEFAULT 0 NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_DATA PRIMARY KEY (MARU_DATA_ID),
    CONSTRAINT CK_TB_MDM_DATA_STATUS CHECK (STATUS IN ('INUSE','DEPRECATED')),
    CONSTRAINT CK_TB_MDM_DATA_SRC_KIND CHECK (SOURCE_KIND IN ('MDM','EXTERNAL')),
    CONSTRAINT CK_TB_MDM_DATA_SRC_SYS CHECK ((SOURCE_KIND = 'EXTERNAL' AND SOURCE_SYSTEM IS NOT NULL) OR (SOURCE_KIND = 'MDM' AND SOURCE_SYSTEM IS NULL)),
    CONSTRAINT CK_TB_MDM_DATA_LVL_CNT CHECK (LVL_CNT BETWEEN 0 AND 5)
);

CREATE TABLE TB_MDM_DATA_CATE (
    MARU_DATA_ID           VARCHAR2(50 CHAR) NOT NULL,
    CATE_ID                VARCHAR2(50 CHAR) NOT NULL,
    VALID_FROM             TIMESTAMP(6) NOT NULL,
    CATE_NAME              VARCHAR2(4000 BYTE),
    DEF_KIND               VARCHAR2(20 CHAR) NOT NULL,
    DEF_EXPR               VARCHAR2(4000 BYTE),
    DEF_TARGET             VARCHAR2(20 CHAR),
    DESCRIPTION            VARCHAR2(4000 BYTE),
    VALID_TO               TIMESTAMP(6) DEFAULT TIMESTAMP '9999-12-31 00:00:00' NOT NULL,
    CHG_SEQ                NUMBER(10) DEFAULT 0 NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_DATA_CATE PRIMARY KEY (MARU_DATA_ID, CATE_ID, VALID_FROM),
    CONSTRAINT CK_TB_MDM_DATA_CATE_KIND CHECK (DEF_KIND IN ('REGEX','TABLE')),
    CONSTRAINT CK_TB_MDM_DATA_CATE_DEF CHECK ((DEF_KIND = 'REGEX' AND DEF_EXPR IS NOT NULL AND DEF_TARGET IS NOT NULL) OR (DEF_KIND = 'TABLE' AND DEF_EXPR IS NULL AND DEF_TARGET IS NULL)),
    CONSTRAINT CK_TB_MDM_DATA_CATE_TARGET CHECK (DEF_TARGET IS NULL OR DEF_TARGET IN ('KEY','LVL1','LVL2','LVL3','LVL4','LVL5','ATTR01','ATTR02','ATTR03','ATTR04','ATTR05','ATTR06','ATTR07','ATTR08','ATTR09','ATTR10'))
);

CREATE TABLE TB_MDM_DATA_CATE_ITEM (
    MARU_DATA_ID           VARCHAR2(50 CHAR) NOT NULL,
    CATE_ID                VARCHAR2(50 CHAR) NOT NULL,
    CODE                   VARCHAR2(50 CHAR) NOT NULL,
    VALID_FROM             TIMESTAMP(6) NOT NULL,
    VALID_TO               TIMESTAMP(6) DEFAULT TIMESTAMP '9999-12-31 00:00:00' NOT NULL,
    CHG_SEQ                NUMBER(10) DEFAULT 0 NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_DATA_CATE_ITEM PRIMARY KEY (MARU_DATA_ID, CATE_ID, CODE, VALID_FROM)
);

CREATE TABLE TB_MDM_DATA_ITEM (
    MARU_DATA_ID           VARCHAR2(50 CHAR) NOT NULL,
    CODE                   VARCHAR2(50 CHAR) NOT NULL,
    VALID_FROM             TIMESTAMP(6) NOT NULL,
    NAME                   VARCHAR2(4000 BYTE) NOT NULL,
    ALTER_NAME             VARCHAR2(4000 BYTE),
    SEQ                    NUMBER(10),
    DESCRIPTION            VARCHAR2(4000 BYTE),
    VALID_TO               TIMESTAMP(6) DEFAULT TIMESTAMP '9999-12-31 00:00:00' NOT NULL,
    ROW_VERSION            NUMBER(10) DEFAULT 0 NOT NULL,
    CHG_SEQ                NUMBER(10) DEFAULT 0 NOT NULL,
    LVL1                   VARCHAR2(50 CHAR),
    LVL2                   VARCHAR2(50 CHAR),
    LVL3                   VARCHAR2(50 CHAR),
    LVL4                   VARCHAR2(50 CHAR),
    LVL5                   VARCHAR2(50 CHAR),
    ATTR01                 VARCHAR2(4000 BYTE),
    ATTR02                 VARCHAR2(4000 BYTE),
    ATTR03                 VARCHAR2(4000 BYTE),
    ATTR04                 VARCHAR2(4000 BYTE),
    ATTR05                 VARCHAR2(4000 BYTE),
    ATTR06                 VARCHAR2(4000 BYTE),
    ATTR07                 VARCHAR2(4000 BYTE),
    ATTR08                 VARCHAR2(4000 BYTE),
    ATTR09                 VARCHAR2(4000 BYTE),
    ATTR10                 VARCHAR2(4000 BYTE),
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_DATA_ITEM PRIMARY KEY (MARU_DATA_ID, CODE, VALID_FROM)
);

CREATE TABLE TB_MDM_DATA_RECV (
    RECV_ID                NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    MARU_DATA_ID           VARCHAR2(50 CHAR),
    SOURCE_SYSTEM          VARCHAR2(20 CHAR) NOT NULL,
    SOURCE_REF             VARCHAR2(50 CHAR),
    RECEIVED_AT            TIMESTAMP(6) NOT NULL,
    BODY                   CLOB NOT NULL,
    ROW_COUNT              NUMBER(10) DEFAULT 0 NOT NULL,
    "RESULT"               VARCHAR2(20 CHAR),
    RESULT_DETAIL          VARCHAR2(4000 BYTE),
    CHG_SEQ                NUMBER(10),
    PROCESSED_AT           TIMESTAMP(6),
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_DATA_RECV PRIMARY KEY (RECV_ID),
    CONSTRAINT CK_TB_MDM_DATA_RECV_RESULT CHECK ("RESULT" IS NULL OR "RESULT" IN ('OK','REJECTED','FAILED'))
);

CREATE TABLE TB_MDM_DATA_RECV_ITEM (
    RECV_ID                NUMBER(19) NOT NULL,
    SEQ                    NUMBER(10) NOT NULL,
    CODE                   VARCHAR2(50 CHAR),
    "ACTION"               VARCHAR2(20 CHAR),
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_DATA_RECV_ITEM PRIMARY KEY (RECV_ID, SEQ),
    CONSTRAINT CK_TB_MDM_DATA_RECV_ITEM_ACTION CHECK ("ACTION" IS NULL OR "ACTION" IN ('INSERT','UPDATE','CLOSE','REOPEN','NONE'))
);

CREATE TABLE TB_MDM_DATA_SYSTEM (
    MARU_DATA_ID           VARCHAR2(50 CHAR) NOT NULL,
    SYSTEM_CODE            VARCHAR2(20 CHAR) NOT NULL,
    DESCRIPTION            VARCHAR2(4000 BYTE),
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_DATA_SYSTEM PRIMARY KEY (MARU_DATA_ID, SYSTEM_CODE)
);

CREATE TABLE TB_MDM_DICT_SEQ (
    DICT_CODE              VARCHAR2(20 CHAR) NOT NULL,
    LAST_CHG_SEQ           NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TB_MDM_DICT_SEQ PRIMARY KEY (DICT_CODE),
    CONSTRAINT CK_TB_MDM_DICT_SEQ_CODE CHECK (DICT_CODE = 'DOMAIN')
);

CREATE TABLE TB_MDM_DICT_SYSTEM (
    DICT_CODE              VARCHAR2(20 CHAR) NOT NULL,
    SYSTEM_CODE            VARCHAR2(20 CHAR) NOT NULL,
    NOTE                   VARCHAR2(4000 BYTE),
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_DICT_SYSTEM PRIMARY KEY (DICT_CODE, SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_DICT_SYSTEM_CODE CHECK (DICT_CODE = 'DOMAIN')
);

CREATE TABLE TB_MDM_DOMAIN (
    DOMAIN_ID              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    DOMAIN_NAME            VARCHAR2(4000 BYTE) NOT NULL,
    STD_NAME               VARCHAR2(50 CHAR) NOT NULL,
    PARENT_DOMAIN_ID       NUMBER(19),
    DOMAIN_KIND            VARCHAR2(20 CHAR) NOT NULL,
    DATA_TYPE              VARCHAR2(20 CHAR) NOT NULL,
    LENGTH                 NUMBER(10),
    SCALE                  NUMBER(10),
    UNIT_CODE              VARCHAR2(20 CHAR),
    MARU_CODE_ID           VARCHAR2(50 CHAR),
    CATE_ID                VARCHAR2(50 CHAR),
    STD_RULE               VARCHAR2(4000 BYTE),
    STD_AST                CLOB,
    BIZ_RULE               VARCHAR2(4000 BYTE),
    BIZ_AST                CLOB,
    DESCRIPTION            VARCHAR2(4000 BYTE),
    EXAMPLES               VARCHAR2(4000 BYTE),
    TEST_CASES             CLOB,
    CHG_SEQ                NUMBER(10) DEFAULT 0 NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_DOMAIN PRIMARY KEY (DOMAIN_ID),
    CONSTRAINT CK_TB_MDM_DOMAIN_STD_AST_JSON CHECK (STD_AST IS NULL OR STD_AST IS JSON STRICT),
    CONSTRAINT CK_TB_MDM_DOMAIN_BIZ_AST_JSON CHECK (BIZ_AST IS NULL OR BIZ_AST IS JSON STRICT),
    CONSTRAINT CK_TB_MDM_DOMAIN_EXAMPLES_JSON CHECK (EXAMPLES IS NULL OR EXAMPLES IS JSON STRICT),
    CONSTRAINT CK_TB_MDM_DOMAIN_TEST_CASES_JSON CHECK (TEST_CASES IS NULL OR TEST_CASES IS JSON STRICT),
    CONSTRAINT CK_TB_MDM_DOMAIN_CODE CHECK (DOMAIN_KIND <> 'CODE' OR STD_RULE IS NULL),
    CONSTRAINT CK_TB_MDM_DOMAIN_FLAG CHECK (DOMAIN_KIND <> 'FLAG' OR PARENT_DOMAIN_ID IS NOT NULL OR STD_RULE IS NOT NULL)
);

CREATE TABLE TB_MDM_EAI (
    EAI_CODE               VARCHAR2(20 CHAR) NOT NULL,
    EAI_NAME               VARCHAR2(4000 BYTE) NOT NULL,
    ENCODING               VARCHAR2(20 CHAR) NOT NULL,
    PAD_RULE               VARCHAR2(4000 BYTE),
    HEADER_LAYOUT_ID       NUMBER(19),
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_EAI PRIMARY KEY (EAI_CODE)
);

CREATE TABLE TB_MDM_LAYOUT (
    LAYOUT_ID              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    LAYOUT_KIND            VARCHAR2(20 CHAR) NOT NULL,
    LAYOUT_NAME            VARCHAR2(4000 BYTE) NOT NULL,
    SND_SYSTEM             VARCHAR2(20 CHAR),
    RCV_SYSTEM             VARCHAR2(20 CHAR),
    STATUS                 VARCHAR2(20 CHAR) DEFAULT 'CREATED' NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_LAYOUT PRIMARY KEY (LAYOUT_ID),
    CONSTRAINT CK_TB_MDM_LAYOUT_KIND CHECK (LAYOUT_KIND IN ('HEADER','MESSAGE')),
    CONSTRAINT CK_TB_MDM_LAYOUT_STATUS CHECK (STATUS IN ('CREATED','INUSE','DEPRECATED'))
);

CREATE TABLE TB_MDM_LAYOUT_CONST (
    LAYOUT_ID              NUMBER(19) NOT NULL,
    VER                    NUMBER(7,3) NOT NULL,
    HEADER_LAYOUT_ID       NUMBER(19) NOT NULL,
    HEADER_COLUMN_PHYS     VARCHAR2(50 CHAR) NOT NULL,
    CONST_VALUE            VARCHAR2(50 CHAR) NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    AUD_VER                NUMBER(19),
    CONSTRAINT PK_TB_MDM_LAYOUT_CONST PRIMARY KEY (LAYOUT_ID, VER, HEADER_LAYOUT_ID, HEADER_COLUMN_PHYS)
);

CREATE TABLE TB_MDM_LAYOUT_HEADER (
    LAYOUT_ID              NUMBER(19) NOT NULL,
    VER                    NUMBER(7,3) NOT NULL,
    SEQ                    NUMBER(10) NOT NULL,
    HEADER_LAYOUT_ID       NUMBER(19) NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    AUD_VER                NUMBER(19),
    CONSTRAINT PK_TB_MDM_LAYOUT_HEADER PRIMARY KEY (LAYOUT_ID, VER, SEQ),
    CONSTRAINT UX_TB_MDM_LAYOUT_HEADER_HDR UNIQUE (LAYOUT_ID, VER, HEADER_LAYOUT_ID)
);

CREATE TABLE TB_MDM_LAYOUT_ITEM (
    LAYOUT_ID              NUMBER(19) NOT NULL,
    VER                    NUMBER(7,3) NOT NULL,
    SEQ                    NUMBER(10) NOT NULL,
    FILL_KIND              VARCHAR2(20 CHAR) NOT NULL,
    COLUMN_PHYS            VARCHAR2(50 CHAR),
    TRANS_UNIT             VARCHAR2(20 CHAR),
    UNIT_ITEM              VARCHAR2(50 CHAR),
    NUM_FORMAT             VARCHAR2(50 CHAR),
    DEFAULT_VALUE          VARCHAR2(50 CHAR),
    FILLER_LENGTH          NUMBER(10),
    "OFFSET"               NUMBER(10) DEFAULT 0 NOT NULL,
    "LENGTH"               NUMBER(10) DEFAULT 0 NOT NULL,
    DATA_TYPE              VARCHAR2(20 CHAR),
    UNIT_CODE              VARCHAR2(20 CHAR),
    SCALE                  NUMBER(10),
    PINNED_YN              VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    AUD_VER                NUMBER(19),
    CONSTRAINT PK_TB_MDM_LAYOUT_ITEM PRIMARY KEY (LAYOUT_ID, VER, SEQ),
    CONSTRAINT CK_TB_MDM_LAYOUT_ITEM_FILL_KIND CHECK (FILL_KIND IN ('DATA','CONST','AUTO','FILLER')),
    CONSTRAINT CK_TB_MDM_LAYOUT_ITEM_UNIT CHECK (TRANS_UNIT IS NULL OR UNIT_ITEM IS NULL),
    CONSTRAINT CK_TB_MDM_LAYOUT_ITEM_PINNED CHECK (PINNED_YN IN ('Y','N') AND (PINNED_YN = 'Y' OR (DATA_TYPE IS NULL AND UNIT_CODE IS NULL AND SCALE IS NULL)))
);

CREATE TABLE TB_MDM_LAYOUT_VER (
    LAYOUT_ID              NUMBER(19) NOT NULL,
    VER                    NUMBER(7,3) NOT NULL,
    VER_KIND               VARCHAR2(20 CHAR) DEFAULT 'MAJOR' NOT NULL,
    STATUS                 VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
    BASE_VER               NUMBER(7,3),
    OWNER_ID               VARCHAR2(50 CHAR),
    APPLY_FROM             TIMESTAMP(6),
    APPLY_TO               TIMESTAMP(6),
    REQUESTED_BY           VARCHAR2(50 CHAR),
    REQUESTED_AT           TIMESTAMP(6),
    RELEASED_AT            TIMESTAMP(6),
    ROW_VERSION            NUMBER(19) DEFAULT 0 NOT NULL,
    EAI_CODE               VARCHAR2(20 CHAR),
    OWN_LENGTH             NUMBER(10) DEFAULT 0 NOT NULL,
    SWITCH_MODE            VARCHAR2(20 CHAR),
    CHANGE_KINDS           VARCHAR2(200 CHAR),
    CHANGE_SUMMARY         VARCHAR2(4000 BYTE),
    SNAPSHOT_JSON          CLOB,
    LEGACY_SNAPSHOT_YN     VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    AUD_VER                NUMBER(19),
    CONSTRAINT PK_TB_MDM_LAYOUT_VER PRIMARY KEY (LAYOUT_ID, VER),
    CONSTRAINT CK_TB_MDM_LAYOUT_VER_SNAPSHOT_JSON CHECK (SNAPSHOT_JSON IS NULL OR SNAPSHOT_JSON IS JSON STRICT),
    CONSTRAINT CK_TB_MDM_LAYOUT_VER_STATUS CHECK (STATUS IN ('DRAFT','REQUESTED','APPROVED','RELEASED','CANCELLED')),
    CONSTRAINT CK_TB_MDM_LAYOUT_VER_KIND CHECK (VER_KIND IN ('MAJOR','MINOR')),
    CONSTRAINT CK_TB_MDM_LAYOUT_VER_APPLY CHECK (STATUS = 'DRAFT' OR (APPLY_FROM IS NOT NULL AND APPLY_TO IS NOT NULL)),
    CONSTRAINT CK_TB_MDM_LAYOUT_VER_SWITCH CHECK (SWITCH_MODE IS NULL OR SWITCH_MODE IN ('SEQUENTIAL','SIMULTANEOUS')),
    CONSTRAINT CK_TB_MDM_LAYOUT_VER_LEGACY CHECK (LEGACY_SNAPSHOT_YN IN ('Y','N') AND (LEGACY_SNAPSHOT_YN = 'N' OR SNAPSHOT_JSON IS NOT NULL))
);

CREATE TABLE TB_MDM_META_REV (
    REV_SEQ                NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    TARGET_TYPE            VARCHAR2(20 CHAR) NOT NULL,
    TARGET_KEY             VARCHAR2(100 CHAR) NOT NULL,
    CHANGE_KIND            VARCHAR2(10 CHAR) NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_META_REV PRIMARY KEY (REV_SEQ),
    CONSTRAINT CK_TB_MDM_META_REV_TYPE CHECK (TARGET_TYPE IN ('COLUMN','DOMAIN','RULE','RULE_SET','CODE','LAYOUT')),
    CONSTRAINT CK_TB_MDM_META_REV_KIND CHECK (CHANGE_KIND IN ('SAVE','EVICT','RELOAD'))
);

CREATE TABLE TB_MDM_RULE (
    MARU_RULE_ID           VARCHAR2(50 CHAR) NOT NULL,
    MARU_RULE_NAME         VARCHAR2(4000 BYTE) NOT NULL,
    RULE_KIND              VARCHAR2(20 CHAR) NOT NULL,
    STATUS                 VARCHAR2(20 CHAR) DEFAULT 'CREATED' NOT NULL,
    SOURCE_KIND            VARCHAR2(20 CHAR) NOT NULL,
    SOURCE_SYSTEM          VARCHAR2(20 CHAR),
    DESCRIPTION            VARCHAR2(4000 BYTE),
    USAGE_NOTE             VARCHAR2(4000 BYTE),
    LAST_VAR_ID            NUMBER(10) DEFAULT 0 NOT NULL,
    LAST_ROW_ID            NUMBER(10) DEFAULT 0 NOT NULL,
    LAST_CASE_ID           NUMBER(10) DEFAULT 0 NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_RULE PRIMARY KEY (MARU_RULE_ID),
    CONSTRAINT CK_TB_MDM_RULE_KIND CHECK (RULE_KIND IN ('DECISION','DERIVE')),
    CONSTRAINT CK_TB_MDM_RULE_STATUS CHECK (STATUS IN ('CREATED','INUSE','DEPRECATED')),
    CONSTRAINT CK_TB_MDM_RULE_SRC_KIND CHECK (SOURCE_KIND IN ('MDM','EXTERNAL')),
    CONSTRAINT CK_TB_MDM_RULE_SRC_SYS CHECK ((SOURCE_KIND = 'EXTERNAL' AND SOURCE_SYSTEM IS NOT NULL) OR (SOURCE_KIND = 'MDM' AND SOURCE_SYSTEM IS NULL))
);

CREATE TABLE TB_MDM_RULE_RECV (
    RECV_ID                NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    MARU_RULE_ID           VARCHAR2(50 CHAR),
    SOURCE_SYSTEM          VARCHAR2(20 CHAR) NOT NULL,
    SOURCE_REF             VARCHAR2(50 CHAR),
    REQ_KIND               VARCHAR2(20 CHAR) NOT NULL,
    RECEIVED_AT            TIMESTAMP(6) NOT NULL,
    BODY                   CLOB NOT NULL,
    "RESULT"               VARCHAR2(20 CHAR),
    RESULT_DETAIL          VARCHAR2(4000 BYTE),
    VER                    NUMBER(7,3),
    PROCESSED_AT           TIMESTAMP(6),
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    AUD_VER                NUMBER(19),
    CONSTRAINT PK_TB_MDM_RULE_RECV PRIMARY KEY (RECV_ID),
    CONSTRAINT CK_TB_MDM_RULE_RECV_REQ CHECK (REQ_KIND IN ('VERSION','CANCEL','DEPRECATE')),
    CONSTRAINT CK_TB_MDM_RULE_RECV_RESULT CHECK ("RESULT" IS NULL OR "RESULT" IN ('OK','REJECTED','FAILED'))
);

CREATE TABLE TB_MDM_RULE_ROW (
    MARU_RULE_ID           VARCHAR2(50 CHAR) NOT NULL,
    VER                    NUMBER(7,3) NOT NULL,
    ROW_ID                 NUMBER(10) NOT NULL,
    SEQ                    NUMBER(10) DEFAULT 0 NOT NULL,
    ROW_KIND               VARCHAR2(20 CHAR) NOT NULL,
    CELLS                  CLOB NOT NULL,
    NOTE                   VARCHAR2(4000 BYTE),
    TAG                    VARCHAR2(50 CHAR),
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    AUD_VER                NUMBER(19),
    CONSTRAINT PK_TB_MDM_RULE_ROW PRIMARY KEY (MARU_RULE_ID, VER, ROW_ID),
    CONSTRAINT CK_TB_MDM_RULE_ROW_CELLS_JSON CHECK (CELLS IS JSON STRICT),
    CONSTRAINT CK_TB_MDM_RULE_ROW_KIND CHECK (ROW_KIND IN ('NORMAL','DEFAULT'))
);

CREATE TABLE TB_MDM_RULE_SET (
    MARU_RULE_SET_ID       VARCHAR2(50 CHAR) NOT NULL,
    MARU_RULE_SET_NAME     VARCHAR2(4000 BYTE) NOT NULL,
    DESCRIPTION            VARCHAR2(4000 BYTE),
    STATUS                 VARCHAR2(20 CHAR) DEFAULT 'CREATED' NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_RULE_SET PRIMARY KEY (MARU_RULE_SET_ID),
    CONSTRAINT CK_TB_MDM_RULE_SET_STATUS CHECK (STATUS IN ('CREATED','INUSE','DEPRECATED'))
);

CREATE TABLE TB_MDM_RULE_SET_TEST_CASE (
    MARU_RULE_SET_ID       VARCHAR2(50 CHAR) NOT NULL,
    CASE_ID                NUMBER(10) NOT NULL,
    CASE_NAME              VARCHAR2(4000 BYTE),
    INPUT_JSON             CLOB NOT NULL,
    EVAL_TS                VARCHAR2(19 CHAR),
    EXPECTED_JSON          CLOB,
    DESCRIPTION            VARCHAR2(4000 BYTE),
    ROW_VERSION            NUMBER(19) DEFAULT 0 NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_RULE_SET_TEST_CASE PRIMARY KEY (MARU_RULE_SET_ID, CASE_ID),
    CONSTRAINT CK_TB_MDM_RULE_SET_TEST_CASE_INPUT_JSON CHECK (INPUT_JSON IS JSON STRICT),
    CONSTRAINT CK_TB_MDM_RULE_SET_TEST_CASE_EXPECTED_JSON CHECK (EXPECTED_JSON IS NULL OR EXPECTED_JSON IS JSON STRICT)
);

CREATE TABLE TB_MDM_RULE_SET_VER (
    MARU_RULE_SET_ID       VARCHAR2(50 CHAR) NOT NULL,
    VER                    NUMBER(7,3) NOT NULL,
    VER_KIND               VARCHAR2(20 CHAR) DEFAULT 'MAJOR' NOT NULL,
    STATUS                 VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
    BASE_VER               NUMBER(7,3),
    OWNER_ID               VARCHAR2(50 CHAR),
    APPLY_FROM             TIMESTAMP(6),
    APPLY_TO               TIMESTAMP(6),
    RULE_IDS               VARCHAR2(4000 BYTE) NOT NULL,
    FLOW_JSON              CLOB,
    CALL_SET_IDS           VARCHAR2(4000 BYTE) DEFAULT '[]' NOT NULL,
    REQUESTED_BY           VARCHAR2(50 CHAR),
    REQUESTED_AT           TIMESTAMP(6),
    RELEASED_AT            TIMESTAMP(6),
    ROW_VERSION            NUMBER(19) DEFAULT 0 NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    AUD_VER                NUMBER(19),
    CONSTRAINT PK_TB_MDM_RULE_SET_VER PRIMARY KEY (MARU_RULE_SET_ID, VER),
    CONSTRAINT CK_TB_MDM_RULE_SET_VER_RULE_IDS_JSON CHECK (RULE_IDS IS JSON STRICT),
    CONSTRAINT CK_TB_MDM_RULE_SET_VER_FLOW_JSON CHECK (FLOW_JSON IS NULL OR FLOW_JSON IS JSON STRICT),
    CONSTRAINT CK_TB_MDM_RULE_SET_VER_CALL_SET_IDS_JSON CHECK (CALL_SET_IDS IS JSON STRICT),
    CONSTRAINT CK_TB_MDM_RULE_SET_VER_STATUS CHECK (STATUS IN ('DRAFT','REQUESTED','APPROVED','RELEASED','CANCELLED')),
    CONSTRAINT CK_TB_MDM_RULE_SET_VER_KIND CHECK (VER_KIND IN ('MAJOR','MINOR')),
    CONSTRAINT CK_TB_MDM_RULE_SET_VER_APPLY CHECK (STATUS = 'DRAFT' OR (APPLY_FROM IS NOT NULL AND APPLY_TO IS NOT NULL))
);

CREATE TABLE TB_MDM_RULE_SYSTEM (
    MARU_RULE_ID           VARCHAR2(50 CHAR) NOT NULL,
    SYSTEM_CODE            VARCHAR2(20 CHAR) NOT NULL,
    DEPLOY_KIND            VARCHAR2(20 CHAR) DEFAULT 'DEF' NOT NULL,
    DESCRIPTION            VARCHAR2(4000 BYTE),
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_RULE_SYSTEM PRIMARY KEY (MARU_RULE_ID, SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_RULE_SYSTEM_KIND CHECK (DEPLOY_KIND IN ('DEF','RESULT'))
);

CREATE TABLE TB_MDM_RULE_TEST_CASE (
    MARU_RULE_ID           VARCHAR2(50 CHAR) NOT NULL,
    CASE_ID                NUMBER(10) NOT NULL,
    CASE_NAME              VARCHAR2(4000 BYTE),
    INPUT_JSON             CLOB NOT NULL,
    EXPECTED_JSON          CLOB,
    DESCRIPTION            VARCHAR2(4000 BYTE),
    ROW_VERSION            NUMBER(19) DEFAULT 0 NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_RULE_TEST_CASE PRIMARY KEY (MARU_RULE_ID, CASE_ID),
    CONSTRAINT CK_TB_MDM_RULE_TEST_CASE_INPUT_JSON CHECK (INPUT_JSON IS JSON STRICT),
    CONSTRAINT CK_TB_MDM_RULE_TEST_CASE_EXPECTED_JSON CHECK (EXPECTED_JSON IS NULL OR EXPECTED_JSON IS JSON STRICT)
);

CREATE TABLE TB_MDM_RULE_VAR (
    MARU_RULE_ID           VARCHAR2(50 CHAR) NOT NULL,
    VER                    NUMBER(7,3) NOT NULL,
    VAR_ID                 NUMBER(10) NOT NULL,
    VAR_KIND               VARCHAR2(20 CHAR) NOT NULL,
    DISP_TYPE              VARCHAR2(20 CHAR),
    VAR_NAME               VARCHAR2(4000 BYTE),
    VAR_AST                CLOB,
    DOMAIN_ID              NUMBER(19),
    DATA_TYPE              VARCHAR2(20 CHAR),
    COLLECT_AGG            VARCHAR2(20 CHAR) DEFAULT 'LIST',
    PRIO_LIST              VARCHAR2(4000 BYTE),
    RES_GRP                VARCHAR2(50 CHAR),
    GRP_COND               VARCHAR2(4000 BYTE),
    GRP_COND_AST           CLOB,
    SEQ                    NUMBER(10) NOT NULL,
    LABEL                  VARCHAR2(4000 BYTE),
    DESCRIPTION            VARCHAR2(4000 BYTE),
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    AUD_VER                NUMBER(19),
    CONSTRAINT PK_TB_MDM_RULE_VAR PRIMARY KEY (MARU_RULE_ID, VER, VAR_ID),
    CONSTRAINT CK_TB_MDM_RULE_VAR_VAR_AST_JSON CHECK (VAR_AST IS NULL OR VAR_AST IS JSON STRICT),
    CONSTRAINT CK_TB_MDM_RULE_VAR_PRIO_LIST_JSON CHECK (PRIO_LIST IS NULL OR PRIO_LIST IS JSON STRICT),
    CONSTRAINT CK_TB_MDM_RULE_VAR_GRP_COND_AST_JSON CHECK (GRP_COND_AST IS NULL OR GRP_COND_AST IS JSON STRICT),
    CONSTRAINT CK_TB_MDM_RULE_VAR_KIND CHECK (VAR_KIND IN ('COND','RESULT')),
    CONSTRAINT CK_TB_MDM_RULE_VAR_DISP CHECK (DISP_TYPE IS NULL OR DISP_TYPE IN ('Equal','1','2','Expression','Value')),
    CONSTRAINT CK_TB_MDM_RULE_VAR_DTYPE CHECK (DATA_TYPE IS NULL OR DATA_TYPE IN ('BOOLEAN','NUMBER','STRING','DATE')),
    CONSTRAINT CK_TB_MDM_RULE_VAR_AGG CHECK (COLLECT_AGG IS NULL OR COLLECT_AGG IN ('LIST','SUM','MIN','MAX','COUNT')),
    CONSTRAINT CK_TB_MDM_RULE_VAR_RESULT_NAME CHECK (VAR_KIND <> 'RESULT' OR VAR_NAME IS NOT NULL)
);

CREATE TABLE TB_MDM_RULE_VER (
    MARU_RULE_ID           VARCHAR2(50 CHAR) NOT NULL,
    VER                    NUMBER(7,3) NOT NULL,
    VER_KIND               VARCHAR2(20 CHAR) DEFAULT 'MAJOR' NOT NULL,
    STATUS                 VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
    BASE_VER               NUMBER(7,3),
    OWNER_ID               VARCHAR2(50 CHAR),
    HIT_POLICY             VARCHAR2(20 CHAR),
    APPLY_FROM             TIMESTAMP(6),
    APPLY_TO               TIMESTAMP(6),
    DESCRIPTION            VARCHAR2(4000 BYTE),
    REQUESTED_BY           VARCHAR2(50 CHAR),
    REQUESTED_AT           TIMESTAMP(6),
    EMERGENCY_YN           VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
    EMERGENCY_REASON       VARCHAR2(4000 BYTE),
    APPROVED_BY            VARCHAR2(50 CHAR),
    APPROVED_AT            TIMESTAMP(6),
    REJECT_REASON          VARCHAR2(4000 BYTE),
    RELEASED_AT            TIMESTAMP(6),
    CANCELLED_AT           TIMESTAMP(6),
    CANCEL_REASON          VARCHAR2(4000 BYTE),
    ROW_VERSION            NUMBER(19) DEFAULT 0 NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    AUD_VER                NUMBER(19),
    CONSTRAINT PK_TB_MDM_RULE_VER PRIMARY KEY (MARU_RULE_ID, VER),
    CONSTRAINT CK_TB_MDM_RULE_VER_STATUS CHECK (STATUS IN ('DRAFT','REQUESTED','APPROVED','RELEASED','CANCELLED')),
    CONSTRAINT CK_TB_MDM_RULE_VER_KIND CHECK (VER_KIND IN ('MAJOR','MINOR')),
    CONSTRAINT CK_TB_MDM_RULE_VER_HIT CHECK (HIT_POLICY IS NULL OR HIT_POLICY IN ('FIRST','UNIQUE','PRIORITY','COLLECT','ANY')),
    CONSTRAINT CK_TB_MDM_RULE_VER_APPLY CHECK (STATUS = 'DRAFT' OR (APPLY_FROM IS NOT NULL AND APPLY_TO IS NOT NULL)),
    CONSTRAINT CK_TB_MDM_RULE_VER_EMERGENCY_YN CHECK (EMERGENCY_YN IN ('Y','N'))
);

CREATE TABLE TB_MDM_SYSTEM (
    SYSTEM_CODE            VARCHAR2(20 CHAR) NOT NULL,
    SYSTEM_NAME            VARCHAR2(100 CHAR) NOT NULL,
    SELF_YN                VARCHAR2(1 CHAR) NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_SYSTEM PRIMARY KEY (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_SYSTEM_SELF_YN CHECK (SELF_YN IN ('Y', 'N'))
);

CREATE TABLE TB_MDM_TERM (
    TERM_ID                NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    TERM_NAME              VARCHAR2(4000 BYTE) NOT NULL,
    SENSE_NO               NUMBER(10) NOT NULL,
    DEFINITION             VARCHAR2(4000 BYTE),
    CONTEXT                VARCHAR2(4000 BYTE),
    ENG_NAME               VARCHAR2(4000 BYTE),
    ENG_ABBR               VARCHAR2(50 CHAR),
    SYNONYMS               VARCHAR2(4000 BYTE),
    ALIASES                VARCHAR2(4000 BYTE),
    SYSTEMS                VARCHAR2(4000 BYTE),
    STD_BASIS              VARCHAR2(4000 BYTE),
    OWNER_DEPT             VARCHAR2(4000 BYTE),
    OWNER_ID               VARCHAR2(50 CHAR),
    SRC_ORIGIN             VARCHAR2(4000 BYTE),
    EMBEDDING              BLOB,
    EMBEDDING_MODEL        VARCHAR2(100 CHAR),
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_TERM PRIMARY KEY (TERM_ID),
    CONSTRAINT CK_TB_MDM_TERM_SYNONYMS_JSON CHECK (SYNONYMS IS NULL OR SYNONYMS IS JSON STRICT),
    CONSTRAINT CK_TB_MDM_TERM_ALIASES_JSON CHECK (ALIASES IS NULL OR ALIASES IS JSON STRICT),
    CONSTRAINT CK_TB_MDM_TERM_SYSTEMS_JSON CHECK (SYSTEMS IS NULL OR SYSTEMS IS JSON STRICT)
);

CREATE TABLE TB_MDM_UNIT (
    UNIT_CODE              VARCHAR2(20 CHAR) NOT NULL,
    DIMENSION              VARCHAR2(50 CHAR) NOT NULL,
    BASE_UNIT              VARCHAR2(20 CHAR) NOT NULL,
    FACTOR                 NUMBER(18,9) NOT NULL,
    CHG_SEQ                NUMBER(10) DEFAULT 0 NOT NULL,
    C_USR_ID               VARCHAR2(100 CHAR),
    C_AT                   TIMESTAMP(6),
    C_SVC_ID               VARCHAR2(100 CHAR),
    C_PGM_ID               VARCHAR2(100 CHAR),
    U_USR_ID               VARCHAR2(100 CHAR),
    U_AT                   TIMESTAMP(6),
    U_SVC_ID               VARCHAR2(100 CHAR),
    U_PGM_ID               VARCHAR2(100 CHAR),
    VER                    NUMBER(19),
    CONSTRAINT PK_TB_MDM_UNIT PRIMARY KEY (UNIT_CODE)
);

-- 인덱스. 부분 인덱스(WHERE)는 함수 기반 인덱스로 바꾼다.
CREATE INDEX IX_TB_MDM_COLUMN_SYSTEM_SYS_PHYS ON TB_MDM_COLUMN_SYSTEM (SYSTEM_CODE, PHYS_NAME);
CREATE INDEX IX_TB_MDM_DATA_ITEM_NAME ON TB_MDM_DATA_ITEM (MARU_DATA_ID, NAME);
CREATE INDEX IX_TB_MDM_DOMAIN_PARENT ON TB_MDM_DOMAIN (PARENT_DOMAIN_ID);
-- IX_TB_MDM_TERM_ABBR: 원문 WHERE ENG_ABBR IS NOT NULL. Oracle B-tree 는 키가 모두 NULL 인 행을 넣지 않으므로 일반 인덱스로 같은 의미다.
CREATE INDEX IX_TB_MDM_TERM_ABBR ON TB_MDM_TERM (ENG_ABBR);
CREATE UNIQUE INDEX UX_TB_MDM_COLUMN_NAME ON TB_MDM_COLUMN (COLUMN_NAME);
-- UX_TB_MDM_RULE_ROW_SEQ: 원문 WHERE ROW_KIND = 'NORMAL'. 조건 밖 행은 키가 모두 NULL 이 되어 인덱스에 들어가지 않는다.
CREATE UNIQUE INDEX UX_TB_MDM_RULE_ROW_SEQ ON TB_MDM_RULE_ROW (CASE WHEN ROW_KIND = 'NORMAL' THEN MARU_RULE_ID END, CASE WHEN ROW_KIND = 'NORMAL' THEN VER END, CASE WHEN ROW_KIND = 'NORMAL' THEN SEQ END);
-- UX_TB_MDM_RULE_VAR_NAME: 원문 WHERE VAR_KIND = 'RESULT'. 조건 밖 행은 키가 모두 NULL 이 되어 인덱스에 들어가지 않는다.
CREATE UNIQUE INDEX UX_TB_MDM_RULE_VAR_NAME ON TB_MDM_RULE_VAR (CASE WHEN VAR_KIND = 'RESULT' THEN MARU_RULE_ID END, CASE WHEN VAR_KIND = 'RESULT' THEN VER END, CASE WHEN VAR_KIND = 'RESULT' THEN VAR_NAME END);
CREATE UNIQUE INDEX UX_TB_MDM_RULE_VAR_SEQ ON TB_MDM_RULE_VAR (MARU_RULE_ID, VER, VAR_KIND, SEQ);
-- UX_TB_MDM_SYSTEM_SELF_YN: 원문 WHERE SELF_YN = 'Y'. 조건 밖 행은 키가 모두 NULL 이 되어 인덱스에 들어가지 않는다.
CREATE UNIQUE INDEX UX_TB_MDM_SYSTEM_SELF_YN ON TB_MDM_SYSTEM (CASE WHEN SELF_YN = 'Y' THEN SELF_YN END);
CREATE UNIQUE INDEX UX_TB_MDM_TERM_NAME_SENSE ON TB_MDM_TERM (TERM_NAME, SENSE_NO);

-- FK. 순환 참조(EAI <-> LAYOUT_VER 등)가 있어 표를 모두 만든 뒤 붙인다.
ALTER TABLE TB_MDM_CODE_CATE ADD CONSTRAINT FK_TB_MDM_CODE_CATE_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID);
ALTER TABLE TB_MDM_CODE_CATE_ITEM ADD CONSTRAINT FK_TB_MDM_CODE_CATE_ITEM_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID);
ALTER TABLE TB_MDM_CODE_CATE_ITEM ADD CONSTRAINT FK_TB_MDM_CODE_CATE_ITEM_VER FOREIGN KEY (MARU_CODE_ID, FROM_VER) REFERENCES TB_MDM_CODE_VER (MARU_CODE_ID, VER);
ALTER TABLE TB_MDM_CODE_CATE ADD CONSTRAINT FK_TB_MDM_CODE_CATE_VER FOREIGN KEY (MARU_CODE_ID, FROM_VER) REFERENCES TB_MDM_CODE_VER (MARU_CODE_ID, VER);
ALTER TABLE TB_MDM_CODE_ITEM ADD CONSTRAINT FK_TB_MDM_CODE_ITEM_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID);
ALTER TABLE TB_MDM_CODE_ITEM ADD CONSTRAINT FK_TB_MDM_CODE_ITEM_VER FOREIGN KEY (MARU_CODE_ID, FROM_VER) REFERENCES TB_MDM_CODE_VER (MARU_CODE_ID, VER);
ALTER TABLE TB_MDM_CODE_RECV ADD CONSTRAINT FK_TB_MDM_CODE_RECV_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID);
ALTER TABLE TB_MDM_CODE_RECV ADD CONSTRAINT FK_TB_MDM_CODE_RECV_SYSTEM FOREIGN KEY (SOURCE_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE);
ALTER TABLE TB_MDM_CODE_SYSTEM ADD CONSTRAINT FK_TB_MDM_CODE_SYSTEM_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID);
ALTER TABLE TB_MDM_CODE ADD CONSTRAINT FK_TB_MDM_CODE_SYSTEM_SRC FOREIGN KEY (SOURCE_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE);
ALTER TABLE TB_MDM_CODE_SYSTEM ADD CONSTRAINT FK_TB_MDM_CODE_SYSTEM_SYSTEM FOREIGN KEY (SYSTEM_CODE) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE);
ALTER TABLE TB_MDM_CODE_VER ADD CONSTRAINT FK_TB_MDM_CODE_VER_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID);
ALTER TABLE TB_MDM_COLUMN ADD CONSTRAINT FK_TB_MDM_COLUMN_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES TB_MDM_DOMAIN (DOMAIN_ID);
ALTER TABLE TB_MDM_COLUMN_SYSTEM ADD CONSTRAINT FK_TB_MDM_COLUMN_SYSTEM_COLUMN FOREIGN KEY (COLUMN_ID) REFERENCES TB_MDM_COLUMN (COLUMN_ID);
ALTER TABLE TB_MDM_COLUMN_SYSTEM ADD CONSTRAINT FK_TB_MDM_COLUMN_SYSTEM_SYSTEM FOREIGN KEY (SYSTEM_CODE) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE);
ALTER TABLE TB_MDM_DATA_CATE ADD CONSTRAINT FK_TB_MDM_DATA_CATE_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID);
ALTER TABLE TB_MDM_DATA_CATE_ITEM ADD CONSTRAINT FK_TB_MDM_DATA_CATE_ITEM_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID);
ALTER TABLE TB_MDM_DATA_ITEM ADD CONSTRAINT FK_TB_MDM_DATA_ITEM_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID);
ALTER TABLE TB_MDM_DATA_RECV ADD CONSTRAINT FK_TB_MDM_DATA_RECV_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID);
ALTER TABLE TB_MDM_DATA_RECV_ITEM ADD CONSTRAINT FK_TB_MDM_DATA_RECV_ITEM_RECV FOREIGN KEY (RECV_ID) REFERENCES TB_MDM_DATA_RECV (RECV_ID);
ALTER TABLE TB_MDM_DATA_RECV ADD CONSTRAINT FK_TB_MDM_DATA_RECV_SYSTEM FOREIGN KEY (SOURCE_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE);
ALTER TABLE TB_MDM_DATA_SYSTEM ADD CONSTRAINT FK_TB_MDM_DATA_SYSTEM_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID);
ALTER TABLE TB_MDM_DATA ADD CONSTRAINT FK_TB_MDM_DATA_SYSTEM_SRC FOREIGN KEY (SOURCE_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE);
ALTER TABLE TB_MDM_DATA_SYSTEM ADD CONSTRAINT FK_TB_MDM_DATA_SYSTEM_SYSTEM FOREIGN KEY (SYSTEM_CODE) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE);
ALTER TABLE TB_MDM_DICT_SYSTEM ADD CONSTRAINT FK_TB_MDM_DICT_SYSTEM_DICT_SEQ FOREIGN KEY (DICT_CODE) REFERENCES TB_MDM_DICT_SEQ (DICT_CODE);
ALTER TABLE TB_MDM_DICT_SYSTEM ADD CONSTRAINT FK_TB_MDM_DICT_SYSTEM_SYSTEM FOREIGN KEY (SYSTEM_CODE) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE);
ALTER TABLE TB_MDM_DOMAIN ADD CONSTRAINT FK_TB_MDM_DOMAIN_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID);
ALTER TABLE TB_MDM_DOMAIN ADD CONSTRAINT FK_TB_MDM_DOMAIN_DOMAIN FOREIGN KEY (PARENT_DOMAIN_ID) REFERENCES TB_MDM_DOMAIN (DOMAIN_ID);
ALTER TABLE TB_MDM_DOMAIN ADD CONSTRAINT FK_TB_MDM_DOMAIN_UNIT FOREIGN KEY (UNIT_CODE) REFERENCES TB_MDM_UNIT (UNIT_CODE);
ALTER TABLE TB_MDM_EAI ADD CONSTRAINT FK_TB_MDM_EAI_LAYOUT FOREIGN KEY (HEADER_LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID);
ALTER TABLE TB_MDM_LAYOUT_CONST ADD CONSTRAINT FK_TB_MDM_LAYOUT_CONST_HEADER FOREIGN KEY (LAYOUT_ID, VER, HEADER_LAYOUT_ID) REFERENCES TB_MDM_LAYOUT_HEADER (LAYOUT_ID, VER, HEADER_LAYOUT_ID);
ALTER TABLE TB_MDM_LAYOUT_HEADER ADD CONSTRAINT FK_TB_MDM_LAYOUT_HEADER_HEADER FOREIGN KEY (HEADER_LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID);
ALTER TABLE TB_MDM_LAYOUT_HEADER ADD CONSTRAINT FK_TB_MDM_LAYOUT_HEADER_VER FOREIGN KEY (LAYOUT_ID, VER) REFERENCES TB_MDM_LAYOUT_VER (LAYOUT_ID, VER);
ALTER TABLE TB_MDM_LAYOUT_ITEM ADD CONSTRAINT FK_TB_MDM_LAYOUT_ITEM_COLUMN FOREIGN KEY (COLUMN_PHYS) REFERENCES TB_MDM_COLUMN (PHYS_NAME);
ALTER TABLE TB_MDM_LAYOUT_ITEM ADD CONSTRAINT FK_TB_MDM_LAYOUT_ITEM_UNIT FOREIGN KEY (TRANS_UNIT) REFERENCES TB_MDM_UNIT (UNIT_CODE);
ALTER TABLE TB_MDM_LAYOUT_ITEM ADD CONSTRAINT FK_TB_MDM_LAYOUT_ITEM_UNIT_CODE FOREIGN KEY (UNIT_CODE) REFERENCES TB_MDM_UNIT (UNIT_CODE);
ALTER TABLE TB_MDM_LAYOUT_ITEM ADD CONSTRAINT FK_TB_MDM_LAYOUT_ITEM_VER FOREIGN KEY (LAYOUT_ID, VER) REFERENCES TB_MDM_LAYOUT_VER (LAYOUT_ID, VER);
ALTER TABLE TB_MDM_LAYOUT ADD CONSTRAINT FK_TB_MDM_LAYOUT_SYSTEM_RCV FOREIGN KEY (RCV_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE);
ALTER TABLE TB_MDM_LAYOUT ADD CONSTRAINT FK_TB_MDM_LAYOUT_SYSTEM_SND FOREIGN KEY (SND_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE);
ALTER TABLE TB_MDM_LAYOUT_VER ADD CONSTRAINT FK_TB_MDM_LAYOUT_VER_EAI FOREIGN KEY (EAI_CODE) REFERENCES TB_MDM_EAI (EAI_CODE);
ALTER TABLE TB_MDM_LAYOUT_VER ADD CONSTRAINT FK_TB_MDM_LAYOUT_VER_LAYOUT FOREIGN KEY (LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID);
ALTER TABLE TB_MDM_RULE_RECV ADD CONSTRAINT FK_TB_MDM_RULE_RECV_RULE FOREIGN KEY (MARU_RULE_ID) REFERENCES TB_MDM_RULE (MARU_RULE_ID);
ALTER TABLE TB_MDM_RULE_RECV ADD CONSTRAINT FK_TB_MDM_RULE_RECV_SYSTEM FOREIGN KEY (SOURCE_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE);
ALTER TABLE TB_MDM_RULE_ROW ADD CONSTRAINT FK_TB_MDM_RULE_ROW_VER FOREIGN KEY (MARU_RULE_ID, VER) REFERENCES TB_MDM_RULE_VER (MARU_RULE_ID, VER) ON DELETE CASCADE;
ALTER TABLE TB_MDM_RULE_SET_TEST_CASE ADD CONSTRAINT FK_TB_MDM_RULE_SET_TEST_CASE_SET FOREIGN KEY (MARU_RULE_SET_ID) REFERENCES TB_MDM_RULE_SET (MARU_RULE_SET_ID);
ALTER TABLE TB_MDM_RULE_SET_VER ADD CONSTRAINT FK_TB_MDM_RULE_SET_VER_SET FOREIGN KEY (MARU_RULE_SET_ID) REFERENCES TB_MDM_RULE_SET (MARU_RULE_SET_ID);
ALTER TABLE TB_MDM_RULE_SYSTEM ADD CONSTRAINT FK_TB_MDM_RULE_SYSTEM_RULE FOREIGN KEY (MARU_RULE_ID) REFERENCES TB_MDM_RULE (MARU_RULE_ID);
ALTER TABLE TB_MDM_RULE ADD CONSTRAINT FK_TB_MDM_RULE_SYSTEM_SRC FOREIGN KEY (SOURCE_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE);
ALTER TABLE TB_MDM_RULE_SYSTEM ADD CONSTRAINT FK_TB_MDM_RULE_SYSTEM_SYSTEM FOREIGN KEY (SYSTEM_CODE) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE);
ALTER TABLE TB_MDM_RULE_TEST_CASE ADD CONSTRAINT FK_TB_MDM_RULE_TEST_CASE_RULE FOREIGN KEY (MARU_RULE_ID) REFERENCES TB_MDM_RULE (MARU_RULE_ID);
ALTER TABLE TB_MDM_RULE_VAR ADD CONSTRAINT FK_TB_MDM_RULE_VAR_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES TB_MDM_DOMAIN (DOMAIN_ID);
ALTER TABLE TB_MDM_RULE_VAR ADD CONSTRAINT FK_TB_MDM_RULE_VAR_VER FOREIGN KEY (MARU_RULE_ID, VER) REFERENCES TB_MDM_RULE_VER (MARU_RULE_ID, VER) ON DELETE CASCADE;
ALTER TABLE TB_MDM_RULE_VER ADD CONSTRAINT FK_TB_MDM_RULE_VER_RULE FOREIGN KEY (MARU_RULE_ID) REFERENCES TB_MDM_RULE (MARU_RULE_ID);

-- 초기 행(SQLite 최종 상태 그대로).
INSERT INTO TB_MDM_DICT_SEQ (DICT_CODE, LAST_CHG_SEQ) VALUES ('DOMAIN', 0);
INSERT INTO TB_MDM_SYSTEM (SYSTEM_CODE, SYSTEM_NAME, SELF_YN, C_USR_ID, C_SVC_ID, C_PGM_ID, U_USR_ID, U_SVC_ID, U_PGM_ID, VER) VALUES ('APS', 'APS', 'N', 'SYSTEM', 'flyway', 'V2__create_mdm_system', 'SYSTEM', 'flyway', 'V2__create_mdm_system', 0);
INSERT INTO TB_MDM_SYSTEM (SYSTEM_CODE, SYSTEM_NAME, SELF_YN, C_USR_ID, C_SVC_ID, C_PGM_ID, U_USR_ID, U_SVC_ID, U_PGM_ID, VER) VALUES ('DKMS', 'DKMS', 'N', 'SYSTEM', 'flyway', 'V2__create_mdm_system', 'SYSTEM', 'flyway', 'V2__create_mdm_system', 0);
INSERT INTO TB_MDM_SYSTEM (SYSTEM_CODE, SYSTEM_NAME, SELF_YN, C_USR_ID, C_SVC_ID, C_PGM_ID, U_USR_ID, U_SVC_ID, U_PGM_ID, VER) VALUES ('ERP', 'ERP', 'N', 'SYSTEM', 'flyway', 'V2__create_mdm_system', 'SYSTEM', 'flyway', 'V2__create_mdm_system', 0);
INSERT INTO TB_MDM_SYSTEM (SYSTEM_CODE, SYSTEM_NAME, SELF_YN, C_USR_ID, C_SVC_ID, C_PGM_ID, U_USR_ID, U_SVC_ID, U_PGM_ID, VER) VALUES ('L2', '레벨2', 'N', 'SYSTEM', 'flyway', 'V2__create_mdm_system', 'SYSTEM', 'flyway', 'V2__create_mdm_system', 0);
INSERT INTO TB_MDM_SYSTEM (SYSTEM_CODE, SYSTEM_NAME, SELF_YN, C_USR_ID, C_SVC_ID, C_PGM_ID, U_USR_ID, U_SVC_ID, U_PGM_ID, VER) VALUES ('MDM', '마루 MDM', 'Y', 'SYSTEM', 'flyway', 'V2__create_mdm_system', 'SYSTEM', 'flyway', 'V2__create_mdm_system', 0);
INSERT INTO TB_MDM_SYSTEM (SYSTEM_CODE, SYSTEM_NAME, SELF_YN, C_USR_ID, C_SVC_ID, C_PGM_ID, U_USR_ID, U_SVC_ID, U_PGM_ID, VER) VALUES ('MES', 'MES', 'N', 'SYSTEM', 'flyway', 'V2__create_mdm_system', 'SYSTEM', 'flyway', 'V2__create_mdm_system', 0);
