-- analog 별도 시스템 폴더 + logViewer 화면 RBAC 멱등 등재
-- 최초 적용: 2026-07-14 포항 dev(10.10.80.241, ksm_dmes) — 완료.
-- KP(172.16.2.154,5010) 등 다른 서버 적용 시 본 파일 그대로 sqlcmd -i 실행 (UTF-8 BOM 유지 필수).
-- 체계: 루트폴더 FULL_SEQ — mpn=1M, mcm=2M, mpp=3M / 4~5M 은 mqc·mls 예약 / 도구성 analog=9M.
SET NOCOUNT ON;

IF NOT EXISTS (SELECT 1 FROM TB_MCM_SEC_MENU_FLD WHERE MENU_ID = 'analog')
INSERT INTO TB_MCM_SEC_MENU_FLD (MENU_ID, MENU_NM, PARENT_MENU_ID, BIZ_SYSTEM_CODE, MENU_SEQ, FULL_SEQ, USE_TP, MENU_TP, MENU_VIEW_YN)
VALUES ('analog', N'로그분석', NULL, NULL, '00000009', '9000000', 'Y', NULL, 'Y');

IF NOT EXISTS (SELECT 1 FROM TB_MCM_SEC_MENU_FLD WHERE MENU_ID = 'anl')
INSERT INTO TB_MCM_SEC_MENU_FLD (MENU_ID, MENU_NM, PARENT_MENU_ID, BIZ_SYSTEM_CODE, MENU_SEQ, FULL_SEQ, USE_TP, MENU_TP, MENU_VIEW_YN)
VALUES ('anl', N'로그조회', 'analog', NULL, '00000100', '9010000', 'Y', NULL, 'Y');

-- FORM_URL 은 BE componentPath 파생 규약(PARENT_MENU_ID/OBJECT_ID)과 동일 형태로 유지
IF NOT EXISTS (SELECT 1 FROM TB_MCM_SEC_OBJ WHERE OBJECT_ID = 'logViewer')
INSERT INTO TB_MCM_SEC_OBJ (OBJECT_ID, OBJECT_NM, SYSTEM_CODE, OBJECT_TYPE, FORM_URL, ACCESS_TP, USE_TP, C_AT, C_USR_ID, VER)
VALUES ('logViewer', N'로그 분석(Analog)', 'analog', 'web', 'anl/logViewer', N'내부', 'Y', SYSDATETIMEOFFSET(), 'admin', 0);

IF NOT EXISTS (SELECT 1 FROM TB_MCM_SEC_MENU WHERE MENU_ID = 'logViewer')
INSERT INTO TB_MCM_SEC_MENU (MENU_ID, MENU_NM, PARENT_MENU_ID, MENU_SEQ, FULL_SEQ, MENU_TP, MENU_VIEW_YN, USE_TP, OBJECT_ID, C_AT, C_USR_ID, VER)
VALUES ('logViewer', N'로그 분석', 'anl', '00000001', '9010100', 'WEB', 'Y', 'Y', 'logViewer', SYSDATETIMEOFFSET(), 'admin', 0);

IF NOT EXISTS (SELECT 1 FROM TB_MCM_SEC_ROLE_MAPPING WHERE OBJECT_ID = 'logViewer' AND ROLE_ID = 'SYSADMIN')
INSERT INTO TB_MCM_SEC_ROLE_MAPPING (OBJECT_ID, ROLE_ID, PERMISSION_ID, C_AT, C_USR_ID, VER)
VALUES ('logViewer', 'SYSADMIN', 'PERM_ALL', SYSDATETIMEOFFSET(), 'admin', 0);
IF NOT EXISTS (SELECT 1 FROM TB_MCM_SEC_ROLE_MAPPING WHERE OBJECT_ID = 'logViewer' AND ROLE_ID = 'MCM_VIEWER')
INSERT INTO TB_MCM_SEC_ROLE_MAPPING (OBJECT_ID, ROLE_ID, PERMISSION_ID, C_AT, C_USR_ID, VER)
VALUES ('logViewer', 'MCM_VIEWER', 'PERM_VIEW', SYSDATETIMEOFFSET(), 'admin', 0);

PRINT 'analog RBAC registration done';
