-- TSK-02-03 영역 02 (dma) SQLite DDL — TB_MDM_UNIT · TERM · DOMAIN · COLUMN · COLUMN_SYSTEM · DICT_SEQ · DICT_SYSTEM
-- 근거: docs/mdm/tasks/TSK-02-03/design.md §6.1, 타입 토큰은 §6.0
-- 전제: TB_MDM_SYSTEM(TSK-01-02 소유)이 먼저 존재해야 한다(F2). 검증 fixtures/00-system.sql 참조.
-- 감사 9칼럼(+AUDIT9)은 `TB_MDM_DICT_SEQ` 를 제외한 모든 테이블에 둔다(naming-dialect-rules.md §2).

CREATE TABLE TB_MDM_UNIT (
    UNIT_CODE VARCHAR(20) NOT NULL,
    DIMENSION VARCHAR(50) NOT NULL,
    BASE_UNIT VARCHAR(20) NOT NULL,
    FACTOR NUMERIC(18,9) NOT NULL,
    CHG_SEQ INTEGER NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER INTEGER,
    CONSTRAINT PK_TB_MDM_UNIT PRIMARY KEY (UNIT_CODE)
);

CREATE TABLE TB_MDM_TERM (
    TERM_ID INTEGER CONSTRAINT PK_TB_MDM_TERM PRIMARY KEY AUTOINCREMENT,
    TERM_NAME TEXT NOT NULL,
    SENSE_NO INTEGER NOT NULL,
    DEFINITION TEXT NOT NULL,
    CONTEXT TEXT,
    ENG_NAME TEXT,
    ENG_ABBR VARCHAR(50),
    SYNONYMS TEXT CONSTRAINT CK_TB_MDM_TERM_SYNONYMS_JSON CHECK (SYNONYMS IS NULL OR json_valid(SYNONYMS)),
    ALIASES TEXT CONSTRAINT CK_TB_MDM_TERM_ALIASES_JSON CHECK (ALIASES IS NULL OR json_valid(ALIASES)),
    SYSTEMS TEXT CONSTRAINT CK_TB_MDM_TERM_SYSTEMS_JSON CHECK (SYSTEMS IS NULL OR json_valid(SYSTEMS)),
    STD_BASIS TEXT,
    OWNER_DEPT TEXT,
    OWNER_ID VARCHAR(50),
    SRC_ORIGIN TEXT,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER INTEGER
);
CREATE UNIQUE INDEX UX_TB_MDM_TERM_NAME_SENSE ON TB_MDM_TERM (TERM_NAME, SENSE_NO);
-- TSK-04-02 V4 로 실제 배포 스키마(src/backend/mdm)는 이 유일 인덱스를 비유일 IX_TB_MDM_TERM_ABBR 로
-- 교체했다(수용 기준 "약어 중복 경고"와 상충, design.md D1). 이 파일은 TSK-02-03 원문 스냅샷이라 각주만
-- 달고 DDL 자체는 고치지 않는다.
CREATE UNIQUE INDEX UX_TB_MDM_TERM_ABBR ON TB_MDM_TERM (ENG_ABBR) WHERE ENG_ABBR IS NOT NULL;

CREATE TABLE TB_MDM_DOMAIN (
    DOMAIN_ID INTEGER CONSTRAINT PK_TB_MDM_DOMAIN PRIMARY KEY AUTOINCREMENT,
    DOMAIN_NAME TEXT NOT NULL,
    STD_NAME VARCHAR(50) NOT NULL,
    PARENT_DOMAIN_ID INTEGER,
    DOMAIN_KIND VARCHAR(20) NOT NULL,
    DATA_TYPE VARCHAR(20) NOT NULL,
    LENGTH INTEGER,
    SCALE INTEGER,
    UNIT_CODE VARCHAR(20),
    MARU_CODE_ID VARCHAR(50),
    CATE_ID VARCHAR(50),
    STD_RULE TEXT,
    STD_AST TEXT CONSTRAINT CK_TB_MDM_DOMAIN_STD_AST_JSON CHECK (STD_AST IS NULL OR json_valid(STD_AST)),
    BIZ_RULE TEXT,
    BIZ_AST TEXT CONSTRAINT CK_TB_MDM_DOMAIN_BIZ_AST_JSON CHECK (BIZ_AST IS NULL OR json_valid(BIZ_AST)),
    DESCRIPTION TEXT,
    EXAMPLES TEXT CONSTRAINT CK_TB_MDM_DOMAIN_EXAMPLES_JSON CHECK (EXAMPLES IS NULL OR json_valid(EXAMPLES)),
    TEST_CASES TEXT CONSTRAINT CK_TB_MDM_DOMAIN_TEST_CASES_JSON CHECK (TEST_CASES IS NULL OR json_valid(TEST_CASES)),
    CHG_SEQ INTEGER NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER INTEGER,
    CONSTRAINT FK_TB_MDM_DOMAIN_DOMAIN FOREIGN KEY (PARENT_DOMAIN_ID) REFERENCES TB_MDM_DOMAIN (DOMAIN_ID),
    CONSTRAINT FK_TB_MDM_DOMAIN_UNIT FOREIGN KEY (UNIT_CODE) REFERENCES TB_MDM_UNIT (UNIT_CODE),
    CONSTRAINT FK_TB_MDM_DOMAIN_CODE FOREIGN KEY (MARU_CODE_ID) REFERENCES TB_MDM_CODE (MARU_CODE_ID),
    CONSTRAINT CK_TB_MDM_DOMAIN_CODE CHECK (DOMAIN_KIND <> 'CODE' OR STD_RULE IS NULL),
    CONSTRAINT CK_TB_MDM_DOMAIN_FLAG CHECK (DOMAIN_KIND <> 'FLAG' OR PARENT_DOMAIN_ID IS NOT NULL OR STD_RULE IS NOT NULL)
);
CREATE INDEX IX_TB_MDM_DOMAIN_PARENT ON TB_MDM_DOMAIN (PARENT_DOMAIN_ID);

CREATE TABLE TB_MDM_COLUMN (
    COLUMN_ID INTEGER CONSTRAINT PK_TB_MDM_COLUMN PRIMARY KEY AUTOINCREMENT,
    COLUMN_NAME TEXT NOT NULL,
    LABEL_LONG TEXT,
    LABEL_MID TEXT,
    LABEL_SHORT TEXT,
    PHYS_NAME VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT,
    DOMAIN_ID INTEGER NOT NULL,
    REQUIRED INTEGER NOT NULL DEFAULT 0,
    DEFAULT_VALUE VARCHAR(50),
    REF_KIND VARCHAR(20),
    REF_TARGET VARCHAR(50),
    REF_CATE_ID VARCHAR(50),
    TERM_IDS TEXT CONSTRAINT CK_TB_MDM_COLUMN_TERM_IDS_JSON CHECK (TERM_IDS IS NULL OR json_valid(TERM_IDS)),
    USAGE_NOTE TEXT,
    CHG_SEQ INTEGER NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER INTEGER,
    CONSTRAINT FK_TB_MDM_COLUMN_DOMAIN FOREIGN KEY (DOMAIN_ID) REFERENCES TB_MDM_DOMAIN (DOMAIN_ID),
    CONSTRAINT CK_TB_MDM_COLUMN_REQUIRED CHECK (REQUIRED IN (0,1))
);
CREATE UNIQUE INDEX UX_TB_MDM_COLUMN_NAME ON TB_MDM_COLUMN (COLUMN_NAME);
CREATE UNIQUE INDEX UX_TB_MDM_COLUMN_PHYS_NAME ON TB_MDM_COLUMN (PHYS_NAME);

CREATE TABLE TB_MDM_COLUMN_SYSTEM (
    COLUMN_ID INTEGER NOT NULL,
    SYSTEM_CODE VARCHAR(20) NOT NULL,
    PHYS_NAME VARCHAR(50) NOT NULL,
    TRANSFORM VARCHAR(50),
    NOTE TEXT,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER INTEGER,
    CONSTRAINT PK_TB_MDM_COLUMN_SYSTEM PRIMARY KEY (COLUMN_ID, SYSTEM_CODE, PHYS_NAME),
    CONSTRAINT FK_TB_MDM_COLUMN_SYSTEM_COLUMN FOREIGN KEY (COLUMN_ID) REFERENCES TB_MDM_COLUMN (COLUMN_ID),
    CONSTRAINT FK_TB_MDM_COLUMN_SYSTEM_SYSTEM FOREIGN KEY (SYSTEM_CODE) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE)
);
CREATE INDEX IX_TB_MDM_COLUMN_SYSTEM_SYS_PHYS ON TB_MDM_COLUMN_SYSTEM (SYSTEM_CODE, PHYS_NAME);

-- 보류 테이블(배포 안 함). 감사 9칼럼 예외 — 두지 않는다(design.md §6.1).
CREATE TABLE TB_MDM_DICT_SEQ (
    DICT_CODE VARCHAR(20) NOT NULL,
    LAST_CHG_SEQ INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT PK_TB_MDM_DICT_SEQ PRIMARY KEY (DICT_CODE),
    CONSTRAINT CK_TB_MDM_DICT_SEQ_CODE CHECK (DICT_CODE = 'DOMAIN')
);
INSERT INTO TB_MDM_DICT_SEQ (DICT_CODE, LAST_CHG_SEQ) VALUES ('DOMAIN', 0);

-- 보류 테이블(배포 안 함).
CREATE TABLE TB_MDM_DICT_SYSTEM (
    DICT_CODE VARCHAR(20) NOT NULL,
    SYSTEM_CODE VARCHAR(20) NOT NULL,
    NOTE TEXT,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER INTEGER,
    CONSTRAINT PK_TB_MDM_DICT_SYSTEM PRIMARY KEY (DICT_CODE, SYSTEM_CODE),
    CONSTRAINT FK_TB_MDM_DICT_SYSTEM_DICT_SEQ FOREIGN KEY (DICT_CODE) REFERENCES TB_MDM_DICT_SEQ (DICT_CODE),
    CONSTRAINT FK_TB_MDM_DICT_SYSTEM_SYSTEM FOREIGN KEY (SYSTEM_CODE) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_DICT_SYSTEM_CODE CHECK (DICT_CODE = 'DOMAIN')
);
