-- TSK-02-03 영역 03 (dmb) MSSQL DDL — TB_MDM_EAI · LAYOUT · LAYOUT_ITEM · LAYOUT_HEADER(신설) · LAYOUT_CONST(신설)
-- 근거: docs/mdm/tasks/TSK-02-03/design.md §6.2. 실행·실측하지 않는다(F4).
-- EAI↔LAYOUT 순환 FK 배치(D7, §6.6): ① LAYOUT 을 EAI_CODE 칼럼은 두되 FK 없이 생성
-- ② EAI 를 HEADER_LAYOUT_ID FK 포함해 생성(LAYOUT 이미 존재) ③ 파일 끝에서 LAYOUT 에 FK_TB_MDM_LAYOUT_EAI 후행 추가.

-- ① LAYOUT — EAI_CODE 칼럼은 있으나 FK 는 아직 걸지 않는다.
CREATE TABLE TB_MDM_LAYOUT (
    LAYOUT_ID BIGINT IDENTITY(1,1) NOT NULL,
    LAYOUT_KIND VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    LAYOUT_NAME NVARCHAR(100) NOT NULL,
    EAI_CODE VARCHAR(20) COLLATE Latin1_General_100_BIN2 NULL,
    SND_SYSTEM VARCHAR(20) COLLATE Latin1_General_100_BIN2 NULL,
    RCV_SYSTEM VARCHAR(20) COLLATE Latin1_General_100_BIN2 NULL,
    TOTAL_LENGTH INT NOT NULL CONSTRAINT DF_TB_MDM_LAYOUT_TOTAL_LENGTH DEFAULT (0),
    [VERSION] BIGINT NOT NULL CONSTRAINT DF_TB_MDM_LAYOUT_VERSION DEFAULT (0),
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_LAYOUT PRIMARY KEY (LAYOUT_ID),
    CONSTRAINT FK_TB_MDM_LAYOUT_SYSTEM_SND FOREIGN KEY (SND_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT FK_TB_MDM_LAYOUT_SYSTEM_RCV FOREIGN KEY (RCV_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_LAYOUT_KIND CHECK (LAYOUT_KIND IN ('HEADER','MESSAGE'))
);

-- ② EAI — LAYOUT 이 이미 있으므로 HEADER_LAYOUT_ID FK 를 인라인으로 건다.
CREATE TABLE TB_MDM_EAI (
    EAI_CODE VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EAI_NAME NVARCHAR(100) NOT NULL,
    ENCODING VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PAD_RULE NVARCHAR(MAX) NULL,
    HEADER_LAYOUT_ID BIGINT NULL,
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_EAI PRIMARY KEY (EAI_CODE),
    CONSTRAINT FK_TB_MDM_EAI_LAYOUT FOREIGN KEY (HEADER_LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID)
);

CREATE TABLE TB_MDM_LAYOUT_ITEM (
    LAYOUT_ID BIGINT NOT NULL,
    SEQ INT NOT NULL,
    FILL_KIND VARCHAR(20) COLLATE Latin1_General_100_BIN2 NOT NULL,
    COLUMN_PHYS VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    TRANS_UNIT VARCHAR(20) COLLATE Latin1_General_100_BIN2 NULL,
    UNIT_ITEM VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    NUM_FORMAT VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    DEFAULT_VALUE VARCHAR(50) COLLATE Latin1_General_100_BIN2 NULL,
    FILLER_LENGTH INT NULL,
    [OFFSET] INT NOT NULL CONSTRAINT DF_TB_MDM_LAYOUT_ITEM_OFFSET DEFAULT (0),
    [LENGTH] INT NOT NULL CONSTRAINT DF_TB_MDM_LAYOUT_ITEM_LENGTH DEFAULT (0),
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_LAYOUT_ITEM PRIMARY KEY (LAYOUT_ID, SEQ),
    CONSTRAINT FK_TB_MDM_LAYOUT_ITEM_LAYOUT FOREIGN KEY (LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID),
    CONSTRAINT FK_TB_MDM_LAYOUT_ITEM_COLUMN FOREIGN KEY (COLUMN_PHYS) REFERENCES TB_MDM_COLUMN (PHYS_NAME),
    CONSTRAINT FK_TB_MDM_LAYOUT_ITEM_UNIT FOREIGN KEY (TRANS_UNIT) REFERENCES TB_MDM_UNIT (UNIT_CODE),
    CONSTRAINT CK_TB_MDM_LAYOUT_ITEM_FILL_KIND CHECK (FILL_KIND IN ('DATA','CONST','AUTO','FILLER')),
    CONSTRAINT CK_TB_MDM_LAYOUT_ITEM_UNIT CHECK (TRANS_UNIT IS NULL OR UNIT_ITEM IS NULL)
);

CREATE TABLE TB_MDM_LAYOUT_HEADER (
    LAYOUT_ID BIGINT NOT NULL,
    SEQ INT NOT NULL,
    HEADER_LAYOUT_ID BIGINT NOT NULL,
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_LAYOUT_HEADER PRIMARY KEY (LAYOUT_ID, SEQ),
    CONSTRAINT FK_TB_MDM_LAYOUT_HEADER_LAYOUT FOREIGN KEY (LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID),
    CONSTRAINT FK_TB_MDM_LAYOUT_HEADER_HEADER FOREIGN KEY (HEADER_LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID)
);
CREATE UNIQUE INDEX UX_TB_MDM_LAYOUT_HEADER_HDR ON TB_MDM_LAYOUT_HEADER (LAYOUT_ID, HEADER_LAYOUT_ID);

CREATE TABLE TB_MDM_LAYOUT_CONST (
    LAYOUT_ID BIGINT NOT NULL,
    HEADER_LAYOUT_ID BIGINT NOT NULL,
    HEADER_SEQ INT NOT NULL,
    CONST_VALUE VARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    C_USR_ID VARCHAR(100) NULL,
    C_AT DATETIME2 NULL,
    C_SVC_ID VARCHAR(100) NULL,
    C_PGM_ID VARCHAR(100) NULL,
    U_USR_ID VARCHAR(100) NULL,
    U_AT DATETIME2 NULL,
    U_SVC_ID VARCHAR(100) NULL,
    U_PGM_ID VARCHAR(100) NULL,
    VER BIGINT NULL,
    CONSTRAINT PK_TB_MDM_LAYOUT_CONST PRIMARY KEY (LAYOUT_ID, HEADER_LAYOUT_ID, HEADER_SEQ),
    CONSTRAINT FK_TB_MDM_LAYOUT_CONST_LAYOUT FOREIGN KEY (LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID),
    CONSTRAINT FK_TB_MDM_LAYOUT_CONST_ITEM FOREIGN KEY (HEADER_LAYOUT_ID, HEADER_SEQ) REFERENCES TB_MDM_LAYOUT_ITEM (LAYOUT_ID, SEQ),
    CONSTRAINT FK_TB_MDM_LAYOUT_CONST_HEADER FOREIGN KEY (LAYOUT_ID, HEADER_LAYOUT_ID) REFERENCES TB_MDM_LAYOUT_HEADER (LAYOUT_ID, HEADER_LAYOUT_ID)
);

-- ③ 순환 FK 후행 추가.
ALTER TABLE TB_MDM_LAYOUT ADD CONSTRAINT FK_TB_MDM_LAYOUT_EAI FOREIGN KEY (EAI_CODE) REFERENCES TB_MDM_EAI (EAI_CODE);
