-- 영역 03 (dmb) SQLite DDL — TB_MDM_LAYOUT · EAI · LAYOUT_VER · LAYOUT_ITEM · LAYOUT_HEADER · LAYOUT_CONST
-- 정본: src/backend/mdm/api/src/main/resources/db/migration/mdm/sqlite/V21__layout_version.sql 의 ④ 새 표(D-144 3단계, D-148, ADR-0006).
--   이 파일은 V21 이 만든 최종 모양을 옮겨 적은 것이다 — 고칠 때는 마이그레이션을 먼저 바꾸고 여기를 맞춘다.
-- 3단계 모양 요약:
--   · 부모 TB_MDM_LAYOUT 은 ID·종류·이름·송수신 시스템·상태만 둔다. EAI_CODE·TOTAL_LENGTH·업무 VERSION 은 없다(EAI ↔ 레이아웃 순환 FK 해소).
--   · 버전 행 TB_MDM_LAYOUT_VER 의 키는 (LAYOUT_ID, VER NUMERIC(7,3)) 이다. EAI_CODE·OWN_LENGTH(그 버전 자신의 항목 길이 합)·확정 기록·
--     이행 전 스냅샷(LEGACY_SNAPSHOT_YN='Y' 면 SNAPSHOT_JSON 필수)을 가진다. 전문 총 길이는 저장하지 않는다(판정 시각 T 의 헤더 버전으로 합성).
--   · 항목·헤더 구성·상수 재정의는 버전 키 (LAYOUT_ID, VER) 아래에 있다. 버전 표 4개의 감사 카운터는 AUD_VER 다(업무 VER 와 이름 충돌, D-034).
--   · 상수 재정의 대상은 헤더 항목 물리명(HEADER_COLUMN_PHYS)이다 — 헤더 항목 FK 는 없다(헤더 버전은 판정 시각에 정해진다).
--   · TB_MDM_EAI.HEADER_LAYOUT_ID 는 남아 있으나 운영 코드는 읽지 않는다 — EAI 표준 헤더는 헤더 버전 행 EAI_CODE 를 시각 T 로 해석한다.
-- 예약어 칼럼(ITEM 의 OFFSET·LENGTH)은 V21 과 같이 백틱으로 감싼다(SQLite 가 받는다). 부모 FK 를 먼저 만들도록 순서는 V21 과 같다.

CREATE TABLE TB_MDM_LAYOUT (
    LAYOUT_ID INTEGER CONSTRAINT PK_TB_MDM_LAYOUT PRIMARY KEY AUTOINCREMENT,
    LAYOUT_KIND VARCHAR(20) NOT NULL,
    LAYOUT_NAME TEXT NOT NULL,
    SND_SYSTEM VARCHAR(20),
    RCV_SYSTEM VARCHAR(20),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT FK_TB_MDM_LAYOUT_SYSTEM_SND FOREIGN KEY (SND_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT FK_TB_MDM_LAYOUT_SYSTEM_RCV FOREIGN KEY (RCV_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_LAYOUT_KIND CHECK (LAYOUT_KIND IN ('HEADER','MESSAGE')),
    CONSTRAINT CK_TB_MDM_LAYOUT_STATUS CHECK (STATUS IN ('CREATED','INUSE','DEPRECATED'))
);

CREATE TABLE TB_MDM_EAI (
    EAI_CODE VARCHAR(20) NOT NULL,
    EAI_NAME TEXT NOT NULL,
    ENCODING VARCHAR(20) NOT NULL,
    PAD_RULE TEXT,
    HEADER_LAYOUT_ID INTEGER,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER BIGINT,
    CONSTRAINT PK_TB_MDM_EAI PRIMARY KEY (EAI_CODE),
    CONSTRAINT FK_TB_MDM_EAI_LAYOUT FOREIGN KEY (HEADER_LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID)
);

CREATE TABLE TB_MDM_LAYOUT_VER (
    LAYOUT_ID INTEGER NOT NULL,
    VER NUMERIC(7,3) NOT NULL,
    VER_KIND VARCHAR(20) NOT NULL DEFAULT 'MAJOR',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    BASE_VER NUMERIC(7,3),
    OWNER_ID VARCHAR(50),
    APPLY_FROM TEXT,
    APPLY_TO TEXT,
    REQUESTED_BY VARCHAR(50),
    REQUESTED_AT TEXT,
    RELEASED_AT TEXT,
    ROW_VERSION BIGINT NOT NULL DEFAULT 0,
    EAI_CODE VARCHAR(20),
    OWN_LENGTH INTEGER NOT NULL DEFAULT 0,
    SWITCH_MODE VARCHAR(20),
    CHANGE_KINDS VARCHAR(200),
    CHANGE_SUMMARY TEXT,
    SNAPSHOT_JSON TEXT CONSTRAINT CK_TB_MDM_LAYOUT_VER_SNAPSHOT_JSON CHECK (SNAPSHOT_JSON IS NULL OR json_valid(SNAPSHOT_JSON)),
    LEGACY_SNAPSHOT_YN VARCHAR(1) NOT NULL DEFAULT 'N',
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    AUD_VER BIGINT,
    CONSTRAINT PK_TB_MDM_LAYOUT_VER PRIMARY KEY (LAYOUT_ID, VER),
    CONSTRAINT FK_TB_MDM_LAYOUT_VER_LAYOUT FOREIGN KEY (LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID),
    CONSTRAINT FK_TB_MDM_LAYOUT_VER_EAI FOREIGN KEY (EAI_CODE) REFERENCES TB_MDM_EAI (EAI_CODE),
    CONSTRAINT CK_TB_MDM_LAYOUT_VER_STATUS CHECK (STATUS IN ('DRAFT','REQUESTED','APPROVED','RELEASED','CANCELLED')),
    CONSTRAINT CK_TB_MDM_LAYOUT_VER_KIND CHECK (VER_KIND IN ('MAJOR','MINOR')),
    CONSTRAINT CK_TB_MDM_LAYOUT_VER_APPLY CHECK (STATUS = 'DRAFT' OR (APPLY_FROM IS NOT NULL AND APPLY_TO IS NOT NULL)),
    CONSTRAINT CK_TB_MDM_LAYOUT_VER_SWITCH CHECK (SWITCH_MODE IS NULL OR SWITCH_MODE IN ('SEQUENTIAL','SIMULTANEOUS')),
    CONSTRAINT CK_TB_MDM_LAYOUT_VER_LEGACY CHECK (LEGACY_SNAPSHOT_YN IN ('Y','N') AND (LEGACY_SNAPSHOT_YN = 'N' OR SNAPSHOT_JSON IS NOT NULL))
);

CREATE TABLE TB_MDM_LAYOUT_ITEM (
    LAYOUT_ID INTEGER NOT NULL,
    VER NUMERIC(7,3) NOT NULL,
    SEQ INTEGER NOT NULL,
    FILL_KIND VARCHAR(20) NOT NULL,
    COLUMN_PHYS VARCHAR(50),
    TRANS_UNIT VARCHAR(20),
    UNIT_ITEM VARCHAR(50),
    NUM_FORMAT VARCHAR(50),
    DEFAULT_VALUE VARCHAR(50),
    FILLER_LENGTH INTEGER,
    `OFFSET` INTEGER NOT NULL DEFAULT 0,
    `LENGTH` INTEGER NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    AUD_VER BIGINT,
    CONSTRAINT PK_TB_MDM_LAYOUT_ITEM PRIMARY KEY (LAYOUT_ID, VER, SEQ),
    CONSTRAINT FK_TB_MDM_LAYOUT_ITEM_VER FOREIGN KEY (LAYOUT_ID, VER) REFERENCES TB_MDM_LAYOUT_VER (LAYOUT_ID, VER),
    CONSTRAINT FK_TB_MDM_LAYOUT_ITEM_COLUMN FOREIGN KEY (COLUMN_PHYS) REFERENCES TB_MDM_COLUMN (PHYS_NAME),
    CONSTRAINT FK_TB_MDM_LAYOUT_ITEM_UNIT FOREIGN KEY (TRANS_UNIT) REFERENCES TB_MDM_UNIT (UNIT_CODE),
    CONSTRAINT CK_TB_MDM_LAYOUT_ITEM_FILL_KIND CHECK (FILL_KIND IN ('DATA','CONST','AUTO','FILLER')),
    CONSTRAINT CK_TB_MDM_LAYOUT_ITEM_UNIT CHECK (TRANS_UNIT IS NULL OR UNIT_ITEM IS NULL)
);

CREATE TABLE TB_MDM_LAYOUT_HEADER (
    LAYOUT_ID INTEGER NOT NULL,
    VER NUMERIC(7,3) NOT NULL,
    SEQ INTEGER NOT NULL,
    HEADER_LAYOUT_ID INTEGER NOT NULL,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    AUD_VER BIGINT,
    CONSTRAINT PK_TB_MDM_LAYOUT_HEADER PRIMARY KEY (LAYOUT_ID, VER, SEQ),
    CONSTRAINT FK_TB_MDM_LAYOUT_HEADER_VER FOREIGN KEY (LAYOUT_ID, VER) REFERENCES TB_MDM_LAYOUT_VER (LAYOUT_ID, VER),
    CONSTRAINT FK_TB_MDM_LAYOUT_HEADER_HEADER FOREIGN KEY (HEADER_LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID)
);
-- 상수 표의 FK 대상 — CONST 를 넣기 전에 있어야 한다(SQLite 는 부모 키에 유일 인덱스를 요구한다)
CREATE UNIQUE INDEX UX_TB_MDM_LAYOUT_HEADER_HDR ON TB_MDM_LAYOUT_HEADER (LAYOUT_ID, VER, HEADER_LAYOUT_ID);

-- 재정의 대상은 헤더 항목 물리명이다 — 헤더 버전이 바뀌어 SEQ 가 움직여도 짝이 유지된다(D-144 3단계). 헤더 항목 FK 는 둘 수 없다
-- (어느 헤더 버전인지는 판정 시각에 정해진다, K1)
CREATE TABLE TB_MDM_LAYOUT_CONST (
    LAYOUT_ID INTEGER NOT NULL,
    VER NUMERIC(7,3) NOT NULL,
    HEADER_LAYOUT_ID INTEGER NOT NULL,
    HEADER_COLUMN_PHYS VARCHAR(50) NOT NULL,
    CONST_VALUE VARCHAR(50) NOT NULL,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    AUD_VER BIGINT,
    CONSTRAINT PK_TB_MDM_LAYOUT_CONST PRIMARY KEY (LAYOUT_ID, VER, HEADER_LAYOUT_ID, HEADER_COLUMN_PHYS),
    CONSTRAINT FK_TB_MDM_LAYOUT_CONST_HEADER FOREIGN KEY (LAYOUT_ID, VER, HEADER_LAYOUT_ID)
        REFERENCES TB_MDM_LAYOUT_HEADER (LAYOUT_ID, VER, HEADER_LAYOUT_ID)
);
