-- TSK-02-03 영역 03 (dmb) SQLite DDL — TB_MDM_EAI · LAYOUT · LAYOUT_ITEM · LAYOUT_HEADER(신설) · LAYOUT_CONST(신설)
-- 근거: docs/mdm/tasks/TSK-02-03/design.md §6.2. D1(헤더 적층)·D2(상수 재정의) 신설 테이블 포함.
-- EAI↔LAYOUT 은 영역 내부 순환 FK(F19) — SQLite 는 인라인 전방 참조를 허용해 문제 없다.
-- 예약어 충돌 칼럼(LAYOUT."VERSION", LAYOUT_ITEM."OFFSET"·"LENGTH")은 큰따옴표로 감싼다(F18).

CREATE TABLE TB_MDM_EAI (
    EAI_CODE VARCHAR(20) NOT NULL,
    EAI_NAME TEXT NOT NULL,
    ENCODING VARCHAR(20) NOT NULL,
    PAD_RULE TEXT,
    HEADER_LAYOUT_ID INTEGER,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER INTEGER,
    CONSTRAINT PK_TB_MDM_EAI PRIMARY KEY (EAI_CODE),
    CONSTRAINT FK_TB_MDM_EAI_LAYOUT FOREIGN KEY (HEADER_LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID)
);

CREATE TABLE TB_MDM_LAYOUT (
    LAYOUT_ID INTEGER CONSTRAINT PK_TB_MDM_LAYOUT PRIMARY KEY AUTOINCREMENT,
    LAYOUT_KIND VARCHAR(20) NOT NULL,
    LAYOUT_NAME TEXT NOT NULL,
    EAI_CODE VARCHAR(20),
    SND_SYSTEM VARCHAR(20),
    RCV_SYSTEM VARCHAR(20),
    TOTAL_LENGTH INTEGER NOT NULL DEFAULT 0,
    "VERSION" INTEGER NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER INTEGER,
    CONSTRAINT FK_TB_MDM_LAYOUT_EAI FOREIGN KEY (EAI_CODE) REFERENCES TB_MDM_EAI (EAI_CODE),
    CONSTRAINT FK_TB_MDM_LAYOUT_SYSTEM_SND FOREIGN KEY (SND_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT FK_TB_MDM_LAYOUT_SYSTEM_RCV FOREIGN KEY (RCV_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_LAYOUT_KIND CHECK (LAYOUT_KIND IN ('HEADER','MESSAGE'))
);

CREATE TABLE TB_MDM_LAYOUT_ITEM (
    LAYOUT_ID INTEGER NOT NULL,
    SEQ INTEGER NOT NULL,
    FILL_KIND VARCHAR(20) NOT NULL,
    COLUMN_PHYS VARCHAR(50),
    TRANS_UNIT VARCHAR(20),
    UNIT_ITEM VARCHAR(50),
    NUM_FORMAT VARCHAR(50),
    DEFAULT_VALUE VARCHAR(50),
    FILLER_LENGTH INTEGER,
    "OFFSET" INTEGER NOT NULL DEFAULT 0,
    "LENGTH" INTEGER NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER INTEGER,
    CONSTRAINT PK_TB_MDM_LAYOUT_ITEM PRIMARY KEY (LAYOUT_ID, SEQ),
    CONSTRAINT FK_TB_MDM_LAYOUT_ITEM_LAYOUT FOREIGN KEY (LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID),
    CONSTRAINT FK_TB_MDM_LAYOUT_ITEM_COLUMN FOREIGN KEY (COLUMN_PHYS) REFERENCES TB_MDM_COLUMN (PHYS_NAME),
    CONSTRAINT FK_TB_MDM_LAYOUT_ITEM_UNIT FOREIGN KEY (TRANS_UNIT) REFERENCES TB_MDM_UNIT (UNIT_CODE),
    CONSTRAINT CK_TB_MDM_LAYOUT_ITEM_FILL_KIND CHECK (FILL_KIND IN ('DATA','CONST','AUTO','FILLER')),
    CONSTRAINT CK_TB_MDM_LAYOUT_ITEM_UNIT CHECK (TRANS_UNIT IS NULL OR UNIT_ITEM IS NULL)
);

-- 신설(D1) — 헤더 적층 구성. N=1 이면 md 「전문당 헤더 하나」와 동일하게 동작한다.
CREATE TABLE TB_MDM_LAYOUT_HEADER (
    LAYOUT_ID INTEGER NOT NULL,
    SEQ INTEGER NOT NULL,
    HEADER_LAYOUT_ID INTEGER NOT NULL,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER INTEGER,
    CONSTRAINT PK_TB_MDM_LAYOUT_HEADER PRIMARY KEY (LAYOUT_ID, SEQ),
    CONSTRAINT FK_TB_MDM_LAYOUT_HEADER_LAYOUT FOREIGN KEY (LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID),
    CONSTRAINT FK_TB_MDM_LAYOUT_HEADER_HEADER FOREIGN KEY (HEADER_LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID)
);
CREATE UNIQUE INDEX UX_TB_MDM_LAYOUT_HEADER_HDR ON TB_MDM_LAYOUT_HEADER (LAYOUT_ID, HEADER_LAYOUT_ID);

-- 신설(D2) — 전문별 헤더 상수 재정의. FILL_KIND=CONST 여부는 앱 검사(cross-table CHECK 불가).
CREATE TABLE TB_MDM_LAYOUT_CONST (
    LAYOUT_ID INTEGER NOT NULL,
    HEADER_LAYOUT_ID INTEGER NOT NULL,
    HEADER_SEQ INTEGER NOT NULL,
    CONST_VALUE VARCHAR(50) NOT NULL,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER INTEGER,
    CONSTRAINT PK_TB_MDM_LAYOUT_CONST PRIMARY KEY (LAYOUT_ID, HEADER_LAYOUT_ID, HEADER_SEQ),
    CONSTRAINT FK_TB_MDM_LAYOUT_CONST_LAYOUT FOREIGN KEY (LAYOUT_ID) REFERENCES TB_MDM_LAYOUT (LAYOUT_ID),
    CONSTRAINT FK_TB_MDM_LAYOUT_CONST_ITEM FOREIGN KEY (HEADER_LAYOUT_ID, HEADER_SEQ) REFERENCES TB_MDM_LAYOUT_ITEM (LAYOUT_ID, SEQ),
    CONSTRAINT FK_TB_MDM_LAYOUT_CONST_HEADER FOREIGN KEY (LAYOUT_ID, HEADER_LAYOUT_ID) REFERENCES TB_MDM_LAYOUT_HEADER (LAYOUT_ID, HEADER_LAYOUT_ID)
);
