-- TSK-02-03 영역 05 (dmd) SQLite DDL — TB_MDM_DATA · DATA_SYSTEM · DATA_ITEM · DATA_CATE · DATA_CATE_ITEM · DATA_RECV · DATA_RECV_ITEM
-- 근거: docs/mdm/tasks/TSK-02-03/design.md §6.4. 변경분 배포 방식(F11) — 행 단위 chg_seq NOT NULL.
-- TB_MDM_DATA_CATE_EFF(사본 전용 REGEX 캐시)는 spec 대상 밖이라 포함하지 않는다.
-- 예약어 충돌 칼럼(DATA_RECV_ITEM."ACTION")은 큰따옴표로 감싼다(F18).

CREATE TABLE TB_MDM_DATA (
    MARU_DATA_ID VARCHAR(50) NOT NULL,
    MARU_DATA_NAME TEXT NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'INUSE',
    SOURCE_KIND VARCHAR(20) NOT NULL,
    SOURCE_SYSTEM VARCHAR(20),
    CODE_PATTERN TEXT NOT NULL DEFAULT '^[0-9A-Z]{1,20}$',
    DESCRIPTION TEXT,
    ATTR01_NAME TEXT, ATTR02_NAME TEXT, ATTR03_NAME TEXT, ATTR04_NAME TEXT, ATTR05_NAME TEXT,
    ATTR06_NAME TEXT, ATTR07_NAME TEXT, ATTR08_NAME TEXT, ATTR09_NAME TEXT, ATTR10_NAME TEXT,
    LVL_CNT INTEGER NOT NULL DEFAULT 0,
    CLOSED_AT TEXT,
    LAST_CHG_SEQ INTEGER NOT NULL DEFAULT 0,
    CHG_SEQ INTEGER NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER INTEGER,
    CONSTRAINT PK_TB_MDM_DATA PRIMARY KEY (MARU_DATA_ID),
    CONSTRAINT FK_TB_MDM_DATA_SYSTEM_SRC FOREIGN KEY (SOURCE_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_DATA_STATUS CHECK (STATUS IN ('INUSE','DEPRECATED')),
    CONSTRAINT CK_TB_MDM_DATA_SRC_KIND CHECK (SOURCE_KIND IN ('MDM','EXTERNAL')),
    CONSTRAINT CK_TB_MDM_DATA_SRC_SYS CHECK ((SOURCE_KIND = 'EXTERNAL' AND SOURCE_SYSTEM IS NOT NULL) OR (SOURCE_KIND = 'MDM' AND SOURCE_SYSTEM IS NULL)),
    CONSTRAINT CK_TB_MDM_DATA_LVL_CNT CHECK (LVL_CNT BETWEEN 0 AND 5)
);

-- 보류 테이블(배포 안 함).
CREATE TABLE TB_MDM_DATA_SYSTEM (
    MARU_DATA_ID VARCHAR(50) NOT NULL,
    SYSTEM_CODE VARCHAR(20) NOT NULL,
    DESCRIPTION TEXT,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER INTEGER,
    CONSTRAINT PK_TB_MDM_DATA_SYSTEM PRIMARY KEY (MARU_DATA_ID, SYSTEM_CODE),
    CONSTRAINT FK_TB_MDM_DATA_SYSTEM_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID),
    CONSTRAINT FK_TB_MDM_DATA_SYSTEM_SYSTEM FOREIGN KEY (SYSTEM_CODE) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE)
);

CREATE TABLE TB_MDM_DATA_ITEM (
    MARU_DATA_ID VARCHAR(50) NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    VALID_FROM TEXT NOT NULL,
    NAME TEXT NOT NULL,
    ALTER_NAME TEXT,
    SEQ INTEGER,
    DESCRIPTION TEXT,
    VALID_TO TEXT NOT NULL DEFAULT '9999-12-31 00:00:00',
    ROW_VERSION INTEGER NOT NULL DEFAULT 0,
    CHG_SEQ INTEGER NOT NULL DEFAULT 0,
    LVL1 VARCHAR(50), LVL2 VARCHAR(50), LVL3 VARCHAR(50), LVL4 VARCHAR(50), LVL5 VARCHAR(50),
    ATTR01 TEXT, ATTR02 TEXT, ATTR03 TEXT, ATTR04 TEXT, ATTR05 TEXT,
    ATTR06 TEXT, ATTR07 TEXT, ATTR08 TEXT, ATTR09 TEXT, ATTR10 TEXT,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER INTEGER,
    CONSTRAINT PK_TB_MDM_DATA_ITEM PRIMARY KEY (MARU_DATA_ID, CODE, VALID_FROM),
    CONSTRAINT FK_TB_MDM_DATA_ITEM_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID)
);
CREATE INDEX IX_TB_MDM_DATA_ITEM_NAME ON TB_MDM_DATA_ITEM (MARU_DATA_ID, NAME);

CREATE TABLE TB_MDM_DATA_CATE (
    MARU_DATA_ID VARCHAR(50) NOT NULL,
    CATE_ID VARCHAR(50) NOT NULL,
    VALID_FROM TEXT NOT NULL,
    CATE_NAME TEXT,
    DEF_KIND VARCHAR(20) NOT NULL,
    DEF_EXPR TEXT,
    DEF_TARGET VARCHAR(20),
    DESCRIPTION TEXT,
    VALID_TO TEXT NOT NULL DEFAULT '9999-12-31 00:00:00',
    CHG_SEQ INTEGER NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER INTEGER,
    CONSTRAINT PK_TB_MDM_DATA_CATE PRIMARY KEY (MARU_DATA_ID, CATE_ID, VALID_FROM),
    CONSTRAINT FK_TB_MDM_DATA_CATE_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID),
    CONSTRAINT CK_TB_MDM_DATA_CATE_KIND CHECK (DEF_KIND IN ('REGEX','TABLE')),
    CONSTRAINT CK_TB_MDM_DATA_CATE_DEF CHECK ((DEF_KIND = 'REGEX' AND DEF_EXPR IS NOT NULL AND DEF_TARGET IS NOT NULL) OR (DEF_KIND = 'TABLE' AND DEF_EXPR IS NULL AND DEF_TARGET IS NULL))
);

-- CATE_ID·CODE 는 FK 없음(F12, 저장 시·상신 시 앱 검사).
CREATE TABLE TB_MDM_DATA_CATE_ITEM (
    MARU_DATA_ID VARCHAR(50) NOT NULL,
    CATE_ID VARCHAR(50) NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    VALID_FROM TEXT NOT NULL,
    VALID_TO TEXT NOT NULL DEFAULT '9999-12-31 00:00:00',
    CHG_SEQ INTEGER NOT NULL DEFAULT 0,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER INTEGER,
    CONSTRAINT PK_TB_MDM_DATA_CATE_ITEM PRIMARY KEY (MARU_DATA_ID, CATE_ID, CODE, VALID_FROM),
    CONSTRAINT FK_TB_MDM_DATA_CATE_ITEM_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID)
);

CREATE TABLE TB_MDM_DATA_RECV (
    RECV_ID INTEGER CONSTRAINT PK_TB_MDM_DATA_RECV PRIMARY KEY AUTOINCREMENT,
    MARU_DATA_ID VARCHAR(50),
    SOURCE_SYSTEM VARCHAR(20) NOT NULL,
    SOURCE_REF VARCHAR(50),
    RECEIVED_AT TEXT NOT NULL,
    BODY TEXT NOT NULL,
    ROW_COUNT INTEGER NOT NULL DEFAULT 0,
    "RESULT" VARCHAR(20),
    RESULT_DETAIL TEXT,
    CHG_SEQ INTEGER,
    PROCESSED_AT TEXT,
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER INTEGER,
    CONSTRAINT FK_TB_MDM_DATA_RECV_DATA FOREIGN KEY (MARU_DATA_ID) REFERENCES TB_MDM_DATA (MARU_DATA_ID),
    CONSTRAINT FK_TB_MDM_DATA_RECV_SYSTEM FOREIGN KEY (SOURCE_SYSTEM) REFERENCES TB_MDM_SYSTEM (SYSTEM_CODE),
    CONSTRAINT CK_TB_MDM_DATA_RECV_RESULT CHECK ("RESULT" IS NULL OR "RESULT" IN ('OK','REJECTED','FAILED'))
);

CREATE TABLE TB_MDM_DATA_RECV_ITEM (
    RECV_ID INTEGER NOT NULL,
    SEQ INTEGER NOT NULL,
    CODE VARCHAR(50),
    "ACTION" VARCHAR(20),
    C_USR_ID VARCHAR(100),
    C_AT TIMESTAMP,
    C_SVC_ID VARCHAR(100),
    C_PGM_ID VARCHAR(100),
    U_USR_ID VARCHAR(100),
    U_AT TIMESTAMP,
    U_SVC_ID VARCHAR(100),
    U_PGM_ID VARCHAR(100),
    VER INTEGER,
    CONSTRAINT PK_TB_MDM_DATA_RECV_ITEM PRIMARY KEY (RECV_ID, SEQ),
    CONSTRAINT FK_TB_MDM_DATA_RECV_ITEM_RECV FOREIGN KEY (RECV_ID) REFERENCES TB_MDM_DATA_RECV (RECV_ID),
    CONSTRAINT CK_TB_MDM_DATA_RECV_ITEM_ACTION CHECK ("ACTION" IS NULL OR "ACTION" IN ('INSERT','UPDATE','CLOSE','REOPEN','NONE'))
);
